-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- Components reused across many pages: CookieBanner, NotFound, AboutPreview (homepage-embedded bio
-- teaser), Testimonials, CategorySection, VideoPreviewCard, FreeGuideKit, LeadMagnet.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('shared_about_preview_badge', 'About Me', 'About Me', 'O mně — náhled na homepage — Odznak nad nadpisem', 'shared', 'about_preview', 'text', 'Odznak nad nadpisem', 10), -- from src/components/AboutPreview.tsx:52
  ('shared_about_preview_title_prefix', 'Hi, I''m', 'Hi, I''m', 'O mně — náhled na homepage — Nadpis — první část', 'shared', 'about_preview', 'text', 'Nadpis — první část', 20), -- from src/components/AboutPreview.tsx:57
  ('shared_about_preview_title_highlight', 'Silvie', 'Silvie', 'O mně — náhled na homepage — Nadpis — zvýrazněné jméno', 'shared', 'about_preview', 'text', 'Nadpis — zvýrazněné jméno', 30), -- from src/components/AboutPreview.tsx:57
  ('shared_about_preview_text_2', 'My journey began in the Czech Republic, where I completed my Master''s degree in Economics and Management. Life presented me with unexpected challenges: a diagnosis of endometriosis, multiple surgeries, and navigating new cultures and healthcare systems far from home.', 'My journey began in the Czech Republic, where I completed my Master''s degree in Economics and Management. Life presented me with unexpected challenges: a diagnosis of endometriosis, multiple surgeries, and navigating new cultures and healthcare systems far from home.', 'O mně — náhled na homepage — Odstavec 2 — příběh', 'shared', 'about_preview', 'textarea', 'Odstavec 2 — příběh', 40), -- from src/components/AboutPreview.tsx:68
  ('shared_about_preview_text_3', 'Over the years, I''ve devoted myself to holistic approaches, obtaining a Certificate in Holistic Counselling, an Art Therapy Diploma (HH Dip A.Th), and Reiki level III certification. Through Resilient Mind, I guide individuals—especially women living abroad—toward inner strength and clarity.', 'Over the years, I''ve devoted myself to holistic approaches, obtaining a Certificate in Holistic Counselling, an Art Therapy Diploma (HH Dip A.Th), and Reiki level III certification. Through Resilient Mind, I guide individuals—especially women living abroad—toward inner strength and clarity.', 'O mně — náhled na homepage — Odstavec 3 — certifikace', 'shared', 'about_preview', 'textarea', 'Odstavec 3 — certifikace', 50), -- from src/components/AboutPreview.tsx:72
  ('shared_about_preview_skill_1', 'Holistic Counselling', 'Holistic Counselling', 'O mně — náhled na homepage — Štítek dovednosti 1', 'shared', 'about_preview', 'text', 'Štítek dovednosti 1', 60), -- from src/components/AboutPreview.tsx:82
  ('shared_about_preview_skill_2', 'Art Therapy Diploma', 'Art Therapy Diploma', 'O mně — náhled na homepage — Štítek dovednosti 2', 'shared', 'about_preview', 'text', 'Štítek dovednosti 2', 70), -- from src/components/AboutPreview.tsx:83
  ('shared_about_preview_skill_3', 'Reiki level III', 'Reiki level III', 'O mně — náhled na homepage — Štítek dovednosti 3', 'shared', 'about_preview', 'text', 'Štítek dovednosti 3', 80), -- from src/components/AboutPreview.tsx:84
  ('shared_about_preview_cta', 'Read My Full Story', 'Read My Full Story', 'O mně — náhled na homepage — Odkaz — Číst celý příběh', 'shared', 'about_preview', 'text', 'Odkaz — Číst celý příběh', 90), -- from src/components/AboutPreview.tsx:94
  ('shared_about_preview_location_label', 'Based in', 'Based in', 'O mně — náhled na homepage — Plovoucí kartička — popisek lokace', 'shared', 'about_preview', 'text', 'Plovoucí kartička — popisek lokace', 100), -- from src/components/AboutPreview.tsx:37
  ('shared_about_preview_location_value', 'Spain', 'Spain', 'O mně — náhled na homepage — Plovoucí kartička — název země', 'shared', 'about_preview', 'text', 'Plovoucí kartička — název země', 110), -- from src/components/AboutPreview.tsx:38
  ('shared_about_preview_location_previous', 'Previously Australia', 'Previously Australia', 'O mně — náhled na homepage — Plovoucí kartička — předchozí lokace', 'shared', 'about_preview', 'text', 'Plovoucí kartička — předchozí lokace', 120), -- from src/components/AboutPreview.tsx:42
  ('shared_category_section_month_label', 'Month', 'Month', 'Sekce měsíce programu — Předpona — "Month" před číslem', 'shared', 'category_section', 'text', 'Předpona — "Month" před číslem', 10), -- from src/components/CategorySection.tsx:38
  ('shared_category_section_bonus_label', 'Bonus', 'Bonus', 'Sekce měsíce programu — Štítek — Bonus měsíc', 'shared', 'category_section', 'text', 'Štítek — Bonus měsíc', 20), -- from src/components/CategorySection.tsx:38
  ('shared_category_section_locked_badge', 'Locked', 'Locked', 'Sekce měsíce programu — Štítek — Uzamčeno', 'shared', 'category_section', 'text', 'Štítek — Uzamčeno', 30), -- from src/components/CategorySection.tsx:42
  ('shared_category_section_view_all', 'View All', 'View All', 'Sekce měsíce programu — Tlačítko — Zobrazit vše', 'shared', 'category_section', 'text', 'Tlačítko — Zobrazit vše', 40), -- from src/components/CategorySection.tsx:64
  ('cookiebanner_title', 'We use cookies', 'We use cookies', 'Cookie lišta — Nadpis', 'shared', 'cookie_banner', 'text', 'Nadpis', 10), -- from src/components/CookieBanner.tsx:46
  ('cookiebanner_text', 'We use cookies to improve your experience. Non-essential cookies are only used with your consent.', 'We use cookies to improve your experience. Non-essential cookies are only used with your consent.', 'Cookie lišta — Text', 'shared', 'cookie_banner', 'textarea', 'Text', 20), -- from src/components/CookieBanner.tsx:49
  ('cookiebanner_link_learn_more', 'Learn more', 'Learn more', 'Cookie lišta — Odkaz — Zjistit více', 'shared', 'cookie_banner', 'text', 'Odkaz — Zjistit více', 30), -- from src/components/CookieBanner.tsx:51
  ('cookiebanner_button_accept', 'Accept All', 'Accept All', 'Cookie lišta — Tlačítko — Přijmout vše', 'shared', 'cookie_banner', 'text', 'Tlačítko — Přijmout vše', 40), -- from src/components/CookieBanner.tsx:60
  ('cookiebanner_button_decline', 'Essential Only', 'Essential Only', 'Cookie lišta — Tlačítko — Pouze nezbytné', 'shared', 'cookie_banner', 'text', 'Tlačítko — Pouze nezbytné', 50), -- from src/components/CookieBanner.tsx:68
  ('leadmagnet_form_title', 'Get Free Access', 'Get Free Access', 'Formulář (lead magnet) — Nadpis formuláře', 'shared', 'formular', 'text', 'Nadpis formuláře', 90), -- from src/components/LeadMagnet.tsx:153
  ('leadmagnet_form_subtitle', 'Enter your email and receive the materials instantly.', 'Enter your email and receive the materials instantly.', 'Formulář (lead magnet) — Podnadpis formuláře', 'shared', 'formular', 'text', 'Podnadpis formuláře', 100), -- from src/components/LeadMagnet.tsx:156
  ('leadmagnet_form_name_placeholder', 'Your name (optional)', 'Your name (optional)', 'Formulář (lead magnet) — Placeholder pole Jméno', 'shared', 'formular', 'text', 'Placeholder pole Jméno', 110), -- from src/components/LeadMagnet.tsx:165
  ('leadmagnet_form_email_placeholder', 'Your email', 'Your email', 'Formulář (lead magnet) — Placeholder pole E-mail', 'shared', 'formular', 'text', 'Placeholder pole E-mail', 120), -- from src/components/LeadMagnet.tsx:178
  ('leadmagnet_form_submit_label', 'Send Me Free Materials', 'Send Me Free Materials', 'Formulář (lead magnet) — Text tlačítka Odeslat', 'shared', 'formular', 'text', 'Text tlačítka Odeslat', 130), -- from src/components/LeadMagnet.tsx:191
  ('leadmagnet_form_submit_loading', 'Sending...', 'Sending...', 'Formulář (lead magnet) — Text tlačítka během odesílání', 'shared', 'formular', 'text', 'Text tlačítka během odesílání', 140), -- from src/components/LeadMagnet.tsx:190
  ('leadmagnet_form_footer_note', 'No spam. Unsubscribe anytime. Your data is safe.', 'No spam. Unsubscribe anytime. Your data is safe.', 'Formulář (lead magnet) — Poznámka pod formulářem (bez spamu)', 'shared', 'formular', 'text', 'Poznámka pod formulářem (bez spamu)', 150), -- from src/components/LeadMagnet.tsx:195
  ('freeguidekit_title', 'Your Free Guide Kit', 'Your Free Guide Kit', 'Hlavička balíčku (Free Guide Kit) — Nadpis widgetu', 'shared', 'hlavicka', 'text', 'Nadpis widgetu', 10), -- from src/components/FreeGuideKit.tsx:44
  ('freeguidekit_subtitle', '3 Tools to Shift Your Energy — 7 Days to Calm, Clarity & Resilience', '3 Tools to Shift Your Energy — 7 Days to Calm, Clarity & Resilience', 'Hlavička balíčku (Free Guide Kit) — Podnadpis widgetu', 'shared', 'hlavicka', 'text', 'Podnadpis widgetu', 20), -- from src/components/FreeGuideKit.tsx:47
  ('freeguidekit_intro', 'Follow this simple 30-minute daily practice. Each tool builds on the other to calm your nervous system, release stress, and rebuild confidence while living abroad.', 'Follow this simple 30-minute daily practice. Each tool builds on the other to calm your nervous system, release stress, and rebuild confidence while living abroad.', 'Hlavička balíčku (Free Guide Kit) — Úvodní text nad kartami', 'shared', 'hlavicka', 'textarea', 'Úvodní text nad kartami', 30), -- from src/components/FreeGuideKit.tsx:55
  ('notfound_heading', 'Page Not Found', 'Page Not Found', 'Stránka 404 — Nadpis', 'shared', 'not_found', 'text', 'Nadpis', 10), -- from src/pages/NotFound.tsx:27
  ('notfound_description', 'Sorry, the page you''re looking for doesn''t exist or has been moved.', 'Sorry, the page you''re looking for doesn''t exist or has been moved.', 'Stránka 404 — Popisný text', 'shared', 'not_found', 'textarea', 'Popisný text', 20), -- from src/pages/NotFound.tsx:30
  ('notfound_button_home', 'Go to Homepage', 'Go to Homepage', 'Stránka 404 — Tlačítko — Na hlavní stránku', 'shared', 'not_found', 'text', 'Tlačítko — Na hlavní stránku', 30), -- from src/pages/NotFound.tsx:38
  ('notfound_button_back', 'Go Back', 'Go Back', 'Stránka 404 — Tlačítko — Zpět', 'shared', 'not_found', 'text', 'Tlačítko — Zpět', 40), -- from src/pages/NotFound.tsx:45
  ('leadmagnet_toast_error_title', 'Error', 'Error', 'Notifikace (toast) — Nadpis – obecná chyba', 'shared', 'notifikace', 'text', 'Nadpis – obecná chyba', 200), -- from src/components/LeadMagnet.tsx:26
  ('leadmagnet_toast_invalid_email', 'Please enter a valid email address', 'Please enter a valid email address', 'Notifikace (toast) — Text – neplatný e-mail', 'shared', 'notifikace', 'text', 'Text – neplatný e-mail', 210), -- from src/components/LeadMagnet.tsx:27
  ('leadmagnet_toast_already_title', 'Already registered', 'Already registered', 'Notifikace (toast) — Nadpis – e-mail už registrován', 'shared', 'notifikace', 'text', 'Nadpis – e-mail už registrován', 220), -- from src/components/LeadMagnet.tsx:42
  ('leadmagnet_toast_already_description', 'This email is already in our list', 'This email is already in our list', 'Notifikace (toast) — Text – e-mail už registrován', 'shared', 'notifikace', 'text', 'Text – e-mail už registrován', 230), -- from src/components/LeadMagnet.tsx:43
  ('leadmagnet_toast_generic_error', 'Something went wrong. Please try again.', 'Something went wrong. Please try again.', 'Notifikace (toast) — Text – obecná chyba při odeslání', 'shared', 'notifikace', 'text', 'Text – obecná chyba při odeslání', 240), -- from src/components/LeadMagnet.tsx:49
  ('leadmagnet_toast_doi_title', 'Almost there!', 'Almost there!', 'Notifikace (toast) — Nadpis – čekání na potvrzení e-mailu', 'shared', 'notifikace', 'text', 'Nadpis – čekání na potvrzení e-mailu', 250), -- from src/components/LeadMagnet.tsx:70
  ('leadmagnet_toast_doi_description', 'Check your inbox and click the confirmation link to receive your materials.', 'Check your inbox and click the confirmation link to receive your materials.', 'Notifikace (toast) — Text – čekání na potvrzení e-mailu', 'shared', 'notifikace', 'text', 'Text – čekání na potvrzení e-mailu', 260), -- from src/components/LeadMagnet.tsx:73
  ('leadmagnet_toast_thanks_title', 'Thank you!', 'Thank you!', 'Notifikace (toast) — Nadpis – poděkování', 'shared', 'notifikace', 'text', 'Nadpis – poděkování', 270), -- from src/components/LeadMagnet.tsx:71
  ('leadmagnet_toast_thanks_description', 'You will receive an email with the materials soon', 'You will receive an email with the materials soon', 'Notifikace (toast) — Text – poděkování', 'shared', 'notifikace', 'text', 'Text – poděkování', 280), -- from src/components/LeadMagnet.tsx:74
  ('leadmagnet_badge', 'Free Download', 'Free Download', 'Obsah bloku (lead magnet) — Odznak "Free Download"', 'shared', 'obsah', 'text', 'Odznak "Free Download"', 10), -- from src/components/LeadMagnet.tsx:102
  ('leadmagnet_title', 'Shift Your Energy & Calm Your Mind in Just 30 Minutes a Day', 'Shift Your Energy & Calm Your Mind in Just 30 Minutes a Day', 'Obsah bloku (lead magnet) — Nadpis bloku', 'shared', 'obsah', 'text', 'Nadpis bloku', 20), -- from src/components/LeadMagnet.tsx:107
  ('leadmagnet_intro_1', 'Feeling anxious, stressed, or stuck while living abroad? Struggling with work, language barriers, or just fitting into a new life?', 'Feeling anxious, stressed, or stuck while living abroad? Struggling with work, language barriers, or just fitting into a new life?', 'Obsah bloku (lead magnet) — Úvodní odstavec 1', 'shared', 'obsah', 'textarea', 'Úvodní odstavec 1', 30), -- from src/components/LeadMagnet.tsx:111
  ('leadmagnet_intro_2', 'This free 7-day practice is designed specifically for expats like you. In just 30 minutes a day, you''ll:', 'This free 7-day practice is designed specifically for expats like you. In just 30 minutes a day, you''ll:', 'Obsah bloku (lead magnet) — Úvodní odstavec 2', 'shared', 'obsah', 'textarea', 'Úvodní odstavec 2', 40), -- from src/components/LeadMagnet.tsx:115
  ('leadmagnet_bullet_1', 'Ground your energy with morning gratitude', 'Ground your energy with morning gratitude', 'Obsah bloku (lead magnet) — Odrážka 1', 'shared', 'obsah', 'text', 'Odrážka 1', 50), -- from src/components/LeadMagnet.tsx:82
  ('leadmagnet_bullet_2', 'Release stress and tension with a simple EFT tapping practice', 'Release stress and tension with a simple EFT tapping practice', 'Obsah bloku (lead magnet) — Odrážka 2', 'shared', 'obsah', 'text', 'Odrážka 2', 60), -- from src/components/LeadMagnet.tsx:83
  ('leadmagnet_bullet_3', 'Quiet your mind and reflect in the evening to end the day calmer and more in control', 'Quiet your mind and reflect in the evening to end the day calmer and more in control', 'Obsah bloku (lead magnet) — Odrážka 3', 'shared', 'obsah', 'text', 'Odrážka 3', 70), -- from src/components/LeadMagnet.tsx:84
  ('leadmagnet_quote', 'Even after the first day, you''ll notice: "Wow, I feel lighter. I can handle this. I''m not ruled by anxiety."', 'Even after the first day, you''ll notice: "Wow, I feel lighter. I can handle this. I''m not ruled by anxiety."', 'Obsah bloku (lead magnet) — Citát pod odrážkami', 'shared', 'obsah', 'textarea', 'Citát pod odrážkami', 80), -- from src/components/LeadMagnet.tsx:128
  ('freeguidekit_midday_badge', 'Midday — 10 min', 'Midday — 10 min', 'Karta – poledne — Odznak (čas)', 'shared', 'poledne', 'text', 'Odznak (čas)', 80), -- from src/components/FreeGuideKit.tsx:91
  ('freeguidekit_midday_title', 'EFT Tapping', 'EFT Tapping', 'Karta – poledne — Nadpis karty', 'shared', 'poledne', 'text', 'Nadpis karty', 90), -- from src/components/FreeGuideKit.tsx:95
  ('freeguidekit_midday_description', 'Release stress and tension with guided EFT tapping. Calm your nervous system and regain focus.', 'Release stress and tension with guided EFT tapping. Calm your nervous system and regain focus.', 'Karta – poledne — Popis karty', 'shared', 'poledne', 'textarea', 'Popis karty', 100), -- from src/components/FreeGuideKit.tsx:98
  ('freeguidekit_midday_video_button', 'Watch Free EFT Video', 'Watch Free EFT Video', 'Karta – poledne — Text tlačítka (přehrát video)', 'shared', 'poledne', 'text', 'Text tlačítka (přehrát video)', 110), -- from src/components/FreeGuideKit.tsx:109
  ('freeguidekit_midday_button', 'EFT Workbook', 'EFT Workbook', 'Karta – poledne — Text tlačítka (stáhnout workbook)', 'shared', 'poledne', 'text', 'Text tlačítka (stáhnout workbook)', 120), -- from src/components/FreeGuideKit.tsx:119
  ('leadmagnet_success_thanks_title', 'Thank you!', 'Thank you!', 'Potvrzení po odeslání — Nadpis – jednorázový opt-in', 'shared', 'potvrzeni', 'text', 'Nadpis – jednorázový opt-in', 160), -- from src/components/LeadMagnet.tsx:142
  ('leadmagnet_success_thanks_text', 'Check your inbox for your free materials and access link.', 'Check your inbox for your free materials and access link.', 'Potvrzení po odeslání — Text – jednorázový opt-in', 'shared', 'potvrzeni', 'textarea', 'Text – jednorázový opt-in', 170), -- from src/components/LeadMagnet.tsx:147
  ('leadmagnet_success_doi_title', 'Almost there!', 'Almost there!', 'Potvrzení po odeslání — Nadpis – dvoufázové potvrzení (DOI)', 'shared', 'potvrzeni', 'text', 'Nadpis – dvoufázové potvrzení (DOI)', 180), -- from src/components/LeadMagnet.tsx:141
  ('leadmagnet_success_doi_text', 'Check your inbox and click the confirmation link. We’ll send your free materials right after you confirm.', 'Check your inbox and click the confirmation link. We’ll send your free materials right after you confirm.', 'Potvrzení po odeslání — Text – dvoufázové potvrzení (DOI)', 'shared', 'potvrzeni', 'textarea', 'Text – dvoufázové potvrzení (DOI)', 190), -- from src/components/LeadMagnet.tsx:146
  ('freeguidekit_morning_badge', 'Morning — 10 min', 'Morning — 10 min', 'Karta – ráno — Odznak (čas)', 'shared', 'rano', 'text', 'Odznak (čas)', 40), -- from src/components/FreeGuideKit.tsx:64
  ('freeguidekit_morning_title', 'Gratitude Practice', 'Gratitude Practice', 'Karta – ráno — Nadpis karty', 'shared', 'rano', 'text', 'Nadpis karty', 50), -- from src/components/FreeGuideKit.tsx:68
  ('freeguidekit_morning_description', 'Ground yourself in presence and awareness. Notice what gives you stability, even when life feels unfamiliar.', 'Ground yourself in presence and awareness. Notice what gives you stability, even when life feels unfamiliar.', 'Karta – ráno — Popis karty', 'shared', 'rano', 'textarea', 'Popis karty', 60), -- from src/components/FreeGuideKit.tsx:71
  ('freeguidekit_morning_button', 'Gratitude Workbook', 'Gratitude Workbook', 'Karta – ráno — Text tlačítka (stáhnout workbook)', 'shared', 'rano', 'text', 'Text tlačítka (stáhnout workbook)', 70), -- from src/components/FreeGuideKit.tsx:82
  ('shared_testimonials_title_prefix', 'Stories of', 'Stories of', 'Reference — nadpis a popisek — Nadpis — první část', 'shared', 'testimonials', 'text', 'Nadpis — první část', 10), -- from src/components/Testimonials.tsx:46
  ('shared_testimonials_title_highlight', 'Transformation', 'Transformation', 'Reference — nadpis a popisek — Nadpis — zvýrazněné slovo', 'shared', 'testimonials', 'text', 'Nadpis — zvýrazněné slovo', 20), -- from src/components/Testimonials.tsx:46
  ('shared_testimonials_subtitle', 'Hear from other expat families who have walked this path.', 'Hear from other expat families who have walked this path.', 'Reference — nadpis a popisek — Podnadpis', 'shared', 'testimonials', 'text', 'Podnadpis', 30), -- from src/components/Testimonials.tsx:49
  ('freeguidekit_evening_badge', 'Evening — 10 min', 'Evening — 10 min', 'Karta – večer — Odznak (čas)', 'shared', 'vecer', 'text', 'Odznak (čas)', 130), -- from src/components/FreeGuideKit.tsx:128
  ('freeguidekit_evening_title', 'Evening Reflection', 'Evening Reflection', 'Karta – večer — Nadpis karty', 'shared', 'vecer', 'text', 'Nadpis karty', 140), -- from src/components/FreeGuideKit.tsx:132
  ('freeguidekit_evening_description', 'Pause, reflect, and gently reframe your thoughts. End the day with clarity and a calmer mindset.', 'Pause, reflect, and gently reframe your thoughts. End the day with clarity and a calmer mindset.', 'Karta – večer — Popis karty', 'shared', 'vecer', 'textarea', 'Popis karty', 150), -- from src/components/FreeGuideKit.tsx:135
  ('freeguidekit_evening_button', 'Gratitude Workbook', 'Gratitude Workbook', 'Karta – večer — Text tlačítka (stáhnout workbook)', 'shared', 'vecer', 'text', 'Text tlačítka (stáhnout workbook)', 160), -- from src/components/FreeGuideKit.tsx:146
  ('shared_video_card_badge_free', 'Free', 'Free', 'Karta videa — členské štítky — Štítek — Free', 'shared', 'video_card', 'text', 'Štítek — Free', 10), -- from src/components/VideoPreviewCard.tsx:19
  ('shared_video_card_badge_basic', 'Basic', 'Basic', 'Karta videa — členské štítky — Štítek — Basic', 'shared', 'video_card', 'text', 'Štítek — Basic', 20), -- from src/components/VideoPreviewCard.tsx:20
  ('shared_video_card_badge_premium', 'Premium', 'Premium', 'Karta videa — členské štítky — Štítek — Premium', 'shared', 'video_card', 'text', 'Štítek — Premium', 30), -- from src/components/VideoPreviewCard.tsx:21
  ('shared_video_card_duration_suffix', 'min', 'min', 'Karta videa — členské štítky — Jednotka délky videa ("min")', 'shared', 'video_card', 'text', 'Jednotka délky videa ("min")', 40), -- from src/components/VideoPreviewCard.tsx:83
  ('shared_video_card_button_unlock', 'Unlock Access', 'Unlock Access', 'Karta videa — členské štítky — Tlačítko — Odemknout přístup', 'shared', 'video_card', 'text', 'Tlačítko — Odemknout přístup', 50), -- from src/components/VideoPreviewCard.tsx:111
  ('freeguidekit_cta_text', 'Ready for the full 12-month transformation?', 'Ready for the full 12-month transformation?', 'Výzva k přechodu na členství — Text nad tlačítkem', 'shared', 'vyzva_k_akci', 'text', 'Text nad tlačítkem', 170), -- from src/components/FreeGuideKit.tsx:155
  ('freeguidekit_cta_button', 'Explore Full Membership', 'Explore Full Membership', 'Výzva k přechodu na členství — Text tlačítka', 'shared', 'vyzva_k_akci', 'text', 'Text tlačítka', 180) -- from src/components/FreeGuideKit.tsx:160
ON CONFLICT (key) DO NOTHING;
