-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- PricingSuccess.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('pricing_success_no_session_title', 'No Payment Session Found', 'No Payment Session Found', 'Stav: platba nenalezena — Nadpis', 'pricing-success', 'bez_session', 'text', 'Nadpis', 40), -- from src/pages/PricingSuccess.tsx:168
  ('pricing_success_no_session_text', 'If you completed a purchase, check your email or contact support.', 'If you completed a purchase, check your email or contact support.', 'Stav: platba nenalezena — Text', 'pricing-success', 'bez_session', 'textarea', 'Text', 50), -- from src/pages/PricingSuccess.tsx:171
  ('pricing_success_no_session_button', 'Go to Dashboard', 'Go to Dashboard', 'Stav: platba nenalezena — Text tlačítka', 'pricing-success', 'bez_session', 'text', 'Text tlačítka', 60), -- from src/pages/PricingSuccess.tsx:175
  ('pricing_success_pending_title', 'Payment Processing', 'Payment Processing', 'Stav: platba prošla, členství se ještě aktivuje — Nadpis', 'pricing-success', 'cekani_na_aktivaci', 'text', 'Nadpis', 90), -- from src/pages/PricingSuccess.tsx:208
  ('pricing_success_pending_text', 'We''re still processing your payment. If your membership isn''t active within a few minutes, please contact support at', 'We''re still processing your payment. If your membership isn''t active within a few minutes, please contact support at', 'Stav: platba prošla, členství se ještě aktivuje — Text (před e-mailem podpory)', 'pricing-success', 'cekani_na_aktivaci', 'textarea', 'Text (před e-mailem podpory)', 100), -- from src/pages/PricingSuccess.tsx:212
  ('pricing_success_pending_badge', 'Activation Pending', 'Activation Pending', 'Stav: platba prošla, členství se ještě aktivuje — Odznak „Čeká se na aktivaci"', 'pricing-success', 'cekani_na_aktivaci', 'text', 'Odznak „Čeká se na aktivaci"', 110), -- from src/pages/PricingSuccess.tsx:224
  ('pricing_success_support_prefix', 'Need help?', 'Need help?', 'Stav čekání — kontaktní box — Text „Potřebujete pomoc?"', 'pricing-success', 'cekani_podpora', 'text', 'Text „Potřebujete pomoc?"', 120), -- from src/pages/PricingSuccess.tsx:234
  ('pricing_success_support_link', 'Book a free discovery call', 'Book a free discovery call', 'Stav čekání — kontaktní box — Odkaz „Rezervovat konzultaci zdarma"', 'pricing-success', 'cekani_podpora', 'text', 'Odkaz „Rezervovat konzultaci zdarma"', 130), -- from src/pages/PricingSuccess.tsx:236
  ('pricing_success_support_middle', 'or reach out to us at', 'or reach out to us at', 'Stav čekání — kontaktní box — Text „nebo nás kontaktujte na"', 'pricing-success', 'cekani_podpora', 'text', 'Text „nebo nás kontaktujte na"', 140), -- from src/pages/PricingSuccess.tsx:238
  ('pricing_success_next_title', 'What Happens Next?', 'What Happens Next?', 'Box „Co bude dál?" — Nadpis', 'pricing-success', 'co_dal', 'text', 'Nadpis', 180), -- from src/pages/PricingSuccess.tsx:279
  ('pricing_success_next_subtitle', 'Here''s what you can expect in the coming moments', 'Here''s what you can expect in the coming moments', 'Box „Co bude dál?" — Podnadpis', 'pricing-success', 'co_dal', 'text', 'Podnadpis', 190), -- from src/pages/PricingSuccess.tsx:282
  ('pricing_success_next_1_title', 'Email Confirmation', 'Email Confirmation', 'Box „Co bude dál?" — Krok 1 – název (potvrzovací e-mail)', 'pricing-success', 'co_dal', 'text', 'Krok 1 – název (potvrzovací e-mail)', 200), -- from src/pages/PricingSuccess.tsx:293
  ('pricing_success_next_1_text', 'You''ll receive a confirmation email with your membership details and receipt within the next few minutes.', 'You''ll receive a confirmation email with your membership details and receipt within the next few minutes.', 'Box „Co bude dál?" — Krok 1 – text', 'pricing-success', 'co_dal', 'textarea', 'Krok 1 – text', 210), -- from src/pages/PricingSuccess.tsx:295
  ('pricing_success_next_2_title', 'Dashboard Access', 'Dashboard Access', 'Box „Co bude dál?" — Krok 2 – název (přístup do nástěnky)', 'pricing-success', 'co_dal', 'text', 'Krok 2 – název (přístup do nástěnky)', 220), -- from src/pages/PricingSuccess.tsx:310
  ('pricing_success_next_2_text', 'Your dashboard is now unlocked with all the content available for your membership tier.', 'Your dashboard is now unlocked with all the content available for your membership tier.', 'Box „Co bude dál?" — Krok 2 – text', 'pricing-success', 'co_dal', 'textarea', 'Krok 2 – text', 230), -- from src/pages/PricingSuccess.tsx:312
  ('pricing_success_next_3_title', 'Start Learning', 'Start Learning', 'Box „Co bude dál?" — Krok 3 – název (začněte se učit)', 'pricing-success', 'co_dal', 'text', 'Krok 3 – název (začněte se učit)', 240), -- from src/pages/PricingSuccess.tsx:327
  ('pricing_success_next_3_text', 'Begin with the introduction videos and explore your personalized 12-month program.', 'Begin with the introduction videos and explore your personalized 12-month program.', 'Box „Co bude dál?" — Krok 3 – text', 'pricing-success', 'co_dal', 'textarea', 'Krok 3 – text', 250), -- from src/pages/PricingSuccess.tsx:329
  ('pricing_success_final_support_prefix', 'Need help getting started? Have questions?', 'Need help getting started? Have questions?', 'Kontaktní box úplně dole — Text „Potřebujete pomoct se začátkem? Máte otázky?"', 'pricing-success', 'podpora', 'text', 'Text „Potřebujete pomoct se začátkem? Máte otázky?"', 380), -- from src/pages/PricingSuccess.tsx:427
  ('pricing_success_final_support_link', 'Book a free discovery call', 'Book a free discovery call', 'Kontaktní box úplně dole — Odkaz „Rezervovat konzultaci zdarma"', 'pricing-success', 'podpora', 'text', 'Odkaz „Rezervovat konzultaci zdarma"', 390), -- from src/pages/PricingSuccess.tsx:429
  ('pricing_success_final_support_middle', 'or reach out to us at', 'or reach out to us at', 'Kontaktní box úplně dole — Text „nebo nás kontaktujte na"', 'pricing-success', 'podpora', 'text', 'Text „nebo nás kontaktujte na"', 400), -- from src/pages/PricingSuccess.tsx:431
  ('pricing_success_login_title', 'Please Log In to Activate Your Membership', 'Please Log In to Activate Your Membership', 'Stav: nutné přihlášení — Nadpis', 'pricing-success', 'prihlaseni', 'text', 'Nadpis', 10), -- from src/pages/PricingSuccess.tsx:145
  ('pricing_success_login_text', 'You need to be logged in so we can activate your membership.', 'You need to be logged in so we can activate your membership.', 'Stav: nutné přihlášení — Text', 'pricing-success', 'prihlaseni', 'textarea', 'Text', 20), -- from src/pages/PricingSuccess.tsx:148
  ('pricing_success_login_button', 'Log In', 'Log In', 'Stav: nutné přihlášení — Text tlačítka', 'pricing-success', 'prihlaseni', 'text', 'Text tlačítka', 30), -- from src/pages/PricingSuccess.tsx:152
  ('pricing_success_card1_title', 'Watch Videos', 'Watch Videos', 'Karty rychlého přístupu — Karta 1 – nadpis (Sledovat videa)', 'pricing-success', 'rychly_pristup', 'text', 'Karta 1 – nadpis (Sledovat videa)', 260), -- from src/pages/PricingSuccess.tsx:347
  ('pricing_success_card1_text', 'Access your weekly video content and start your transformation journey.', 'Access your weekly video content and start your transformation journey.', 'Karty rychlého přístupu — Karta 1 – text', 'pricing-success', 'rychly_pristup', 'textarea', 'Karta 1 – text', 270), -- from src/pages/PricingSuccess.tsx:352
  ('pricing_success_card1_button', 'Go to Dashboard', 'Go to Dashboard', 'Karty rychlého přístupu — Karta 1 – text tlačítka', 'pricing-success', 'rychly_pristup', 'text', 'Karta 1 – text tlačítka', 280), -- from src/pages/PricingSuccess.tsx:356
  ('pricing_success_card2_title', 'Download Resources', 'Download Resources', 'Karty rychlého přístupu — Karta 2 – nadpis (Stáhnout materiály)', 'pricing-success', 'rychly_pristup', 'text', 'Karta 2 – nadpis (Stáhnout materiály)', 290), -- from src/pages/PricingSuccess.tsx:368
  ('pricing_success_card2_text', 'Get your workbooks, worksheets, and meditation guides.', 'Get your workbooks, worksheets, and meditation guides.', 'Karty rychlého přístupu — Karta 2 – text', 'pricing-success', 'rychly_pristup', 'textarea', 'Karta 2 – text', 300), -- from src/pages/PricingSuccess.tsx:373
  ('pricing_success_card2_button', 'View Resources', 'View Resources', 'Karty rychlého přístupu — Karta 2 – text tlačítka', 'pricing-success', 'rychly_pristup', 'text', 'Karta 2 – text tlačítka', 310), -- from src/pages/PricingSuccess.tsx:377
  ('pricing_success_card3_title', 'Book a Session', 'Book a Session', 'Karty rychlého přístupu — Karta 3 – nadpis (Rezervovat konzultaci)', 'pricing-success', 'rychly_pristup', 'text', 'Karta 3 – nadpis (Rezervovat konzultaci)', 320), -- from src/pages/PricingSuccess.tsx:389
  ('pricing_success_card3_text', 'Premium members can schedule their consultation sessions.', 'Premium members can schedule their consultation sessions.', 'Karty rychlého přístupu — Karta 3 – text', 'pricing-success', 'rychly_pristup', 'textarea', 'Karta 3 – text', 330), -- from src/pages/PricingSuccess.tsx:394
  ('pricing_success_card3_button', 'Book Now', 'Book Now', 'Karty rychlého přístupu — Karta 3 – text tlačítka', 'pricing-success', 'rychly_pristup', 'text', 'Karta 3 – text tlačítka', 340), -- from src/pages/PricingSuccess.tsx:398
  ('pricing_success_title', 'Welcome to Your Journey!', 'Welcome to Your Journey!', 'Stav: úspěšná platba a aktivace — Nadpis', 'pricing-success', 'uspech', 'text', 'Nadpis', 150), -- from src/pages/PricingSuccess.tsx:259
  ('pricing_success_text', 'Your payment was successful and your membership is now active.', 'Your payment was successful and your membership is now active.', 'Stav: úspěšná platba a aktivace — Text', 'pricing-success', 'uspech', 'textarea', 'Text', 160), -- from src/pages/PricingSuccess.tsx:263
  ('pricing_success_badge', 'Membership Activated', 'Membership Activated', 'Stav: úspěšná platba a aktivace — Odznak „Členství aktivováno"', 'pricing-success', 'uspech', 'text', 'Odznak „Členství aktivováno"', 170), -- from src/pages/PricingSuccess.tsx:269
  ('pricing_success_cta_title', 'Ready to Start Your Transformation?', 'Ready to Start Your Transformation?', 'Výzva k akci (dole na stránce) — Nadpis', 'pricing-success', 'vyzva', 'text', 'Nadpis', 350), -- from src/pages/PricingSuccess.tsx:409
  ('pricing_success_cta_text', 'Head to your dashboard and begin exploring your personalized program.', 'Head to your dashboard and begin exploring your personalized program.', 'Výzva k akci (dole na stránce) — Text', 'pricing-success', 'vyzva', 'textarea', 'Text', 360), -- from src/pages/PricingSuccess.tsx:412
  ('pricing_success_cta_button', 'Go to Dashboard', 'Go to Dashboard', 'Výzva k akci (dole na stránce) — Text tlačítka', 'pricing-success', 'vyzva', 'text', 'Text tlačítka', 370), -- from src/pages/PricingSuccess.tsx:416
  ('pricing_success_processing_title', 'Processing Your Payment...', 'Processing Your Payment...', 'Stav: zpracování platby — Nadpis', 'pricing-success', 'zpracovani', 'text', 'Nadpis', 70), -- from src/pages/PricingSuccess.tsx:189
  ('pricing_success_processing_text', 'Please wait while we activate your membership.', 'Please wait while we activate your membership.', 'Stav: zpracování platby — Text', 'pricing-success', 'zpracovani', 'text', 'Text', 80) -- from src/pages/PricingSuccess.tsx:192
ON CONFLICT (key) DO NOTHING;
