-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- ResilientHubs.tsx. Includes the 19 keys shared with Membership.tsx/Membership2.tsx -- see
-- 20260814120300_seed_cms_membership.sql's header.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('hubs_content_title_prefix', 'Explore the ', 'Explore the ', 'Náhled obsahu programu — Nadpis — text před zvýrazněním', 'resilient-hubs', 'content', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/ResilientHubs.tsx:393
  ('hubs_content_title_highlight', 'Program Content', 'Program Content', 'Náhled obsahu programu — Nadpis — zvýrazněná část', 'resilient-hubs', 'content', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/ResilientHubs.tsx:393
  ('hubs_content_subtitle', 'Preview the monthly video lessons, workbooks, and exercises included in your membership.', 'Preview the monthly video lessons, workbooks, and exercises included in your membership.', 'Náhled obsahu programu — Podnadpis', 'resilient-hubs', 'content', 'text', 'Podnadpis', 30), -- from src/pages/ResilientHubs.tsx:396
  ('hubs_details_intro', 'I offer a gentle online membership combining Emotional Freedom Techniques (EFT) and other holistic practices, with practical PDF tools for daily practice.', 'I offer a gentle online membership combining Emotional Freedom Techniques (EFT) and other holistic practices, with practical PDF tools for daily practice.', '12měsíční členství — popis — Úvodní odstavec', 'resilient-hubs', 'details', 'textarea', 'Úvodní odstavec', 10), -- from src/pages/ResilientHubs.tsx:127
  ('hubs_details_title_prefix', 'A 12-Month Online Membership for ', 'A 12-Month Online Membership for ', '12měsíční členství — popis — Nadpis — text před zvýrazněním', 'resilient-hubs', 'details', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/ResilientHubs.tsx:130
  ('hubs_details_title_highlight', 'Expat Women', 'Expat Women', '12měsíční členství — popis — Nadpis — zvýrazněná část', 'resilient-hubs', 'details', 'text', 'Nadpis — zvýrazněná část', 30), -- from src/pages/ResilientHubs.tsx:130
  ('hubs_details_subtitle', 'Steady emotional support, nervous system regulation and gentle structure while living abroad.', 'Steady emotional support, nervous system regulation and gentle structure while living abroad.', '12měsíční členství — popis — Podnadpis', 'resilient-hubs', 'details', 'textarea', 'Podnadpis', 40), -- from src/pages/ResilientHubs.tsx:133
  ('hubs_details_body', 'This ongoing membership supports you month by month as you transform loneliness, uncertainty and cultural stress into emotional stability, self-trust and inner safety.', 'This ongoing membership supports you month by month as you transform loneliness, uncertainty and cultural stress into emotional stability, self-trust and inner safety.', '12měsíční členství — popis — Odstavec — popis programu', 'resilient-hubs', 'details', 'textarea', 'Odstavec — popis programu', 50), -- from src/pages/ResilientHubs.tsx:136
  ('hubs_details_foryou_title', 'This is for you if:', 'This is for you if:', '12měsíční členství — popis — Nadpis boxu "Toto je pro tebe, pokud:"', 'resilient-hubs', 'details', 'text', 'Nadpis boxu "Toto je pro tebe, pokud:"', 60), -- from src/pages/ResilientHubs.tsx:142
  ('hubs_details_foryou_1', 'You live abroad and feel emotionally overwhelmed', 'You live abroad and feel emotionally overwhelmed', '12měsíční členství — popis — Položka seznamu "Pro tebe, pokud" 1', 'resilient-hubs', 'details', 'text', 'Položka seznamu "Pro tebe, pokud" 1', 70), -- from src/pages/ResilientHubs.tsx:145
  ('hubs_details_foryou_2', 'You miss stability and inner safety', 'You miss stability and inner safety', '12měsíční členství — popis — Položka seznamu "Pro tebe, pokud" 2', 'resilient-hubs', 'details', 'text', 'Položka seznamu "Pro tebe, pokud" 2', 80), -- from src/pages/ResilientHubs.tsx:146
  ('hubs_details_foryou_3', 'You want gentle, practical tools', 'You want gentle, practical tools', '12měsíční členství — popis — Položka seznamu "Pro tebe, pokud" 3', 'resilient-hubs', 'details', 'text', 'Položka seznamu "Pro tebe, pokud" 3', 90), -- from src/pages/ResilientHubs.tsx:147
  ('hubs_details_foryou_4', 'You value continuity over quick fixes', 'You value continuity over quick fixes', '12měsíční členství — popis — Položka seznamu "Pro tebe, pokud" 4', 'resilient-hubs', 'details', 'text', 'Položka seznamu "Pro tebe, pokud" 4', 100), -- from src/pages/ResilientHubs.tsx:148
  ('hubs_details_theme_title', 'Each month focuses on one core theme:', 'Each month focuses on one core theme:', '12měsíční členství — popis — Nadpis boxu "Každý měsíc jedno téma"', 'resilient-hubs', 'details', 'text', 'Nadpis boxu "Každý měsíc jedno téma"', 110), -- from src/pages/ResilientHubs.tsx:161
  ('hubs_details_theme_1', 'Emotional overwhelm', 'Emotional overwhelm', '12měsíční členství — popis — Položka tématu 1', 'resilient-hubs', 'details', 'text', 'Položka tématu 1', 120), -- from src/pages/ResilientHubs.tsx:164
  ('hubs_details_theme_2', 'Loneliness and belonging', 'Loneliness and belonging', '12měsíční členství — popis — Položka tématu 2', 'resilient-hubs', 'details', 'text', 'Položka tématu 2', 130), -- from src/pages/ResilientHubs.tsx:165
  ('hubs_details_theme_3', 'Boundaries and self-trust', 'Boundaries and self-trust', '12měsíční členství — popis — Položka tématu 3', 'resilient-hubs', 'details', 'text', 'Položka tématu 3', 140), -- from src/pages/ResilientHubs.tsx:166
  ('hubs_details_theme_4', 'Stability during constant change', 'Stability during constant change', '12měsíční členství — popis — Položka tématu 4', 'resilient-hubs', 'details', 'text', 'Položka tématu 4', 150), -- from src/pages/ResilientHubs.tsx:167
  ('hubs_details_theme_link', 'See the full 12-month overview', 'See the full 12-month overview', '12měsíční členství — popis — Odkaz — Zobrazit celý 12měsíční přehled', 'resilient-hubs', 'details', 'text', 'Odkaz — Zobrazit celý 12měsíční přehled', 160), -- from src/pages/ResilientHubs.tsx:178
  ('hubs_details_theme_link_suffix', 'for details on each month.', 'for details on each month.', '12měsíční členství — popis — Text za odkazem ("for details on each month.")', 'resilient-hubs', 'details', 'text', 'Text za odkazem ("for details on each month.")', 170), -- from src/pages/ResilientHubs.tsx:178
  ('hubs_details_closing', 'This membership helps you feel more stable, supported and at home within yourself — wherever you live.', 'This membership helps you feel more stable, supported and at home within yourself — wherever you live.', '12měsíční členství — popis — Uzavírací odstavec 2', 'resilient-hubs', 'details', 'textarea', 'Uzavírací odstavec 2', 190), -- from src/pages/ResilientHubs.tsx:189
  ('membership_faq_title', 'Frequently Asked Questions', 'Frequently Asked Questions', 'Časté dotazy — nadpis (samotné otázky/odpovědi se editují ve správě FAQ, skupina "hubs") — Nadpis sekce (sdíleno se stránkou Membership)', 'resilient-hubs', 'faq', 'text', 'Nadpis sekce (sdíleno se stránkou Membership)', 10), -- from src/pages/Membership.tsx:574
  ('membership_faq_subtitle', 'Everything you need to know before starting your journey.', 'Everything you need to know before starting your journey.', 'Časté dotazy — nadpis (samotné otázky/odpovědi se editují ve správě FAQ, skupina "hubs") — Podnadpis (sdíleno se stránkou Membership)', 'resilient-hubs', 'faq', 'text', 'Podnadpis (sdíleno se stránkou Membership)', 20), -- from src/pages/Membership.tsx:577
  ('hubs_finalcta_title_line1', 'Your Inner Strength Goes', 'Your Inner Strength Goes', 'Závěrečná výzva — Nadpis — první řádek', 'resilient-hubs', 'finalcta', 'text', 'Nadpis — první řádek', 10), -- from src/pages/ResilientHubs.tsx:537
  ('hubs_finalcta_title_highlight', 'Wherever Life Takes You', 'Wherever Life Takes You', 'Závěrečná výzva — Nadpis — druhý řádek (zvýrazněný)', 'resilient-hubs', 'finalcta', 'text', 'Nadpis — druhý řádek (zvýrazněný)', 20), -- from src/pages/ResilientHubs.tsx:539
  ('hubs_finalcta_body', 'You moved abroad for a reason. You took one of the bravest steps most people never will. Now it''s time to build the resilience that matches your courage.', 'You moved abroad for a reason. You took one of the bravest steps most people never will. Now it''s time to build the resilience that matches your courage.', 'Závěrečná výzva — Odstavec', 'resilient-hubs', 'finalcta', 'textarea', 'Odstavec', 30), -- from src/pages/ResilientHubs.tsx:542
  ('hubs_finalcta_quote', '"The moment I stopped fighting against my expatriate challenges and started transforming them instead, everything changed."', '"The moment I stopped fighting against my expatriate challenges and started transforming them instead, everything changed."', 'Závěrečná výzva — Citát (včetně uvozovek)', 'resilient-hubs', 'finalcta', 'textarea', 'Citát (včetně uvozovek)', 40), -- from src/pages/ResilientHubs.tsx:545
  ('hubs_finalcta_attribution', '— Silvie, Founder of Resilient Mind', '— Silvie, Founder of Resilient Mind', 'Závěrečná výzva — Podpis pod citátem', 'resilient-hubs', 'finalcta', 'text', 'Podpis pod citátem', 50), -- from src/pages/ResilientHubs.tsx:547
  ('hubs_finalcta_cta_primary', 'Start Your Transformation Today', 'Start Your Transformation Today', 'Závěrečná výzva — Text tlačítka — Start Your Transformation Today', 'resilient-hubs', 'finalcta', 'text', 'Text tlačítka — Start Your Transformation Today', 60), -- from src/pages/ResilientHubs.tsx:555
  ('hubs_finalcta_cta_secondary', 'Download Free Guide First', 'Download Free Guide First', 'Závěrečná výzva — Text tlačítka — Download Free Guide First', 'resilient-hubs', 'finalcta', 'text', 'Text tlačítka — Download Free Guide First', 70), -- from src/pages/ResilientHubs.tsx:563
  ('hubs_hero_badge', 'For Expats Ready to Thrive', 'For Expats Ready to Thrive', 'Úvodní obrazovka — Odznak nad nadpisem', 'resilient-hubs', 'hero', 'text', 'Odznak nad nadpisem', 10), -- from src/pages/ResilientHubs.tsx:75
  ('hubs_hero_title_prefix', 'From Navigating Life Abroad to', 'From Navigating Life Abroad to', 'Úvodní obrazovka — Nadpis — text před zvýrazněním', 'resilient-hubs', 'hero', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/ResilientHubs.tsx:80
  ('hubs_hero_title_highlight', 'Truly Thriving', 'Truly Thriving', 'Úvodní obrazovka — Nadpis — zvýrazněná část', 'resilient-hubs', 'hero', 'text', 'Nadpis — zvýrazněná část', 30), -- from src/pages/ResilientHubs.tsx:81
  ('hubs_hero_lead', 'Expat life can be rewarding, but it also comes with challenges—loneliness, cultural differences, uncertainty, and navigating health challenges while away from your familiar support network.', 'Expat life can be rewarding, but it also comes with challenges—loneliness, cultural differences, uncertainty, and navigating health challenges while away from your familiar support network.', 'Úvodní obrazovka — Odstavec 1 — úvod', 'resilient-hubs', 'hero', 'textarea', 'Odstavec 1 — úvod', 40), -- from src/pages/ResilientHubs.tsx:85
  ('hubs_hero_body', 'Using my 13 years of experience living abroad and my expertise in personal development, expressive arts, and holistic therapies, I created an online membership program that transforms these challenges into opportunities for growth and inner strength.', 'Using my 13 years of experience living abroad and my expertise in personal development, expressive arts, and holistic therapies, I created an online membership program that transforms these challenges into opportunities for growth and inner strength.', 'Úvodní obrazovka — Odstavec 2 — o metodě', 'resilient-hubs', 'hero', 'textarea', 'Odstavec 2 — o metodě', 50), -- from src/pages/ResilientHubs.tsx:88
  ('hubs_hero_created_by', 'Created by Silvie — an expatriate of 13+ years who developed a practical, accessible methodology designed to support people globally through an online membership and educational programs.', 'Created by Silvie — an expatriate of 13+ years who developed a practical, accessible methodology designed to support people globally through an online membership and educational programs.', 'Úvodní obrazovka — Odstavec 3 — o Silvii', 'resilient-hubs', 'hero', 'textarea', 'Odstavec 3 — o Silvii', 60), -- from src/pages/ResilientHubs.tsx:92
  ('hubs_hero_cta_primary', 'See Plans & Pricing', 'See Plans & Pricing', 'Úvodní obrazovka — Text tlačítka — Zobrazit ceník', 'resilient-hubs', 'hero', 'text', 'Text tlačítka — Zobrazit ceník', 70), -- from src/pages/ResilientHubs.tsx:100
  ('hubs_hero_cta_secondary', 'Try Free Guide First', 'Try Free Guide First', 'Úvodní obrazovka — Text tlačítka — Stáhnout průvodce zdarma', 'resilient-hubs', 'hero', 'text', 'Text tlačítka — Stáhnout průvodce zdarma', 80), -- from src/pages/ResilientHubs.tsx:108
  ('hubs_hero_stat_1', '48 video lessons', '48 video lessons', 'Úvodní obrazovka — Statistika 1 — video lekce', 'resilient-hubs', 'hero', 'text', 'Statistika 1 — video lekce', 90), -- from src/pages/ResilientHubs.tsx:114
  ('hubs_hero_stat_2', '48 workbooks', '48 workbooks', 'Úvodní obrazovka — Statistika 2 — pracovní sešity', 'resilient-hubs', 'hero', 'text', 'Statistika 2 — pracovní sešity', 100), -- from src/pages/ResilientHubs.tsx:115
  ('hubs_hero_stat_3', '15 min/week', '15 min/week', 'Úvodní obrazovka — Statistika 3 — čas týdně', 'resilient-hubs', 'hero', 'text', 'Statistika 3 — čas týdně', 110), -- from src/pages/ResilientHubs.tsx:116
  ('hubs_howworks_title', 'How It Works', 'How It Works', 'Jak to funguje — Nadpis sekce', 'resilient-hubs', 'howworks', 'text', 'Nadpis sekce', 10), -- from src/pages/ResilientHubs.tsx:361
  ('hubs_howworks_step_1_title', 'Choose Your Plan', 'Choose Your Plan', 'Jak to funguje — Krok 1 — nadpis', 'resilient-hubs', 'howworks', 'text', 'Krok 1 — nadpis', 20), -- from src/pages/ResilientHubs.tsx:366
  ('hubs_howworks_step_1_desc', 'Pick Basic for self-guided learning or Premium for the full experience with personal consultations and art therapy kit.', 'Pick Basic for self-guided learning or Premium for the full experience with personal consultations and art therapy kit.', 'Jak to funguje — Krok 1 — popis', 'resilient-hubs', 'howworks', 'textarea', 'Krok 1 — popis', 30), -- from src/pages/ResilientHubs.tsx:366
  ('hubs_howworks_step_2_title', 'Start This Month''s Theme', 'Start This Month''s Theme', 'Jak to funguje — Krok 2 — nadpis', 'resilient-hubs', 'howworks', 'text', 'Krok 2 — nadpis', 40), -- from src/pages/ResilientHubs.tsx:367
  ('hubs_howworks_step_2_desc', 'Each month, a new module unlocks with video lessons, workbooks, and guided exercises tailored to a specific aspect of resilience.', 'Each month, a new module unlocks with video lessons, workbooks, and guided exercises tailored to a specific aspect of resilience.', 'Jak to funguje — Krok 2 — popis', 'resilient-hubs', 'howworks', 'textarea', 'Krok 2 — popis', 50), -- from src/pages/ResilientHubs.tsx:367
  ('hubs_howworks_step_3_title', 'Practice at Your Own Pace', 'Practice at Your Own Pace', 'Jak to funguje — Krok 3 — nadpis', 'resilient-hubs', 'howworks', 'text', 'Krok 3 — nadpis', 60), -- from src/pages/ResilientHubs.tsx:368
  ('hubs_howworks_step_3_desc', 'Watch 1 video per week (5-10 min), complete the workbook exercises, and integrate the techniques into your daily life. (4 x videos per month)', 'Watch 1 video per week (5-10 min), complete the workbook exercises, and integrate the techniques into your daily life. (4 x videos per month)', 'Jak to funguje — Krok 3 — popis', 'resilient-hubs', 'howworks', 'textarea', 'Krok 3 — popis', 70), -- from src/pages/ResilientHubs.tsx:368
  ('hubs_howworks_step_4_title', 'Transform Over 12 Months', 'Transform Over 12 Months', 'Jak to funguje — Krok 4 — nadpis', 'resilient-hubs', 'howworks', 'text', 'Krok 4 — nadpis', 80), -- from src/pages/ResilientHubs.tsx:369
  ('hubs_howworks_step_4_desc', 'By month 12, you''ll have a complete toolkit of resilience techniques and an unshakable inner foundation — your ''inner home'' that travels with you.', 'By month 12, you''ll have a complete toolkit of resilience techniques and an unshakable inner foundation — your ''inner home'' that travels with you.', 'Jak to funguje — Krok 4 — popis', 'resilient-hubs', 'howworks', 'textarea', 'Krok 4 — popis', 90), -- from src/pages/ResilientHubs.tsx:369
  ('hubs_membership_title_prefix', 'Resilient Mind ', 'Resilient Mind ', 'Resilient Mind Membership — shrnutí — Nadpis — text před zvýrazněním', 'resilient-hubs', 'membership', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/ResilientHubs.tsx:236
  ('hubs_membership_title_highlight', 'Membership', 'Membership', 'Resilient Mind Membership — shrnutí — Nadpis — zvýrazněná část', 'resilient-hubs', 'membership', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/ResilientHubs.tsx:236
  ('hubs_membership_body', 'Ongoing emotional support and nervous system regulation for expat women. An online membership with guided practical tools and video support within a holistic approach. Pay as you go — no auto-renewal.', 'Ongoing emotional support and nervous system regulation for expat women. An online membership with guided practical tools and video support within a holistic approach. Pay as you go — no auto-renewal.', 'Resilient Mind Membership — shrnutí — Odstavec', 'resilient-hubs', 'membership', 'textarea', 'Odstavec', 30), -- from src/pages/ResilientHubs.tsx:239
  ('hubs_membership_lead', 'Every month you receive:', 'Every month you receive:', 'Resilient Mind Membership — shrnutí — Text před seznamem "Every month you receive"', 'resilient-hubs', 'membership', 'text', 'Text před seznamem "Every month you receive"', 40), -- from src/pages/ResilientHubs.tsx:242
  ('hubs_membership_item_1', 'Guided EFT sessions and other holistic practices (audio & video)', 'Guided EFT sessions and other holistic practices (audio & video)', 'Resilient Mind Membership — shrnutí — Položka seznamu 1', 'resilient-hubs', 'membership', 'text', 'Položka seznamu 1', 50), -- from src/pages/ResilientHubs.tsx:245
  ('hubs_membership_item_2', 'Expressive creative tools (no artistic experience needed)', 'Expressive creative tools (no artistic experience needed)', 'Resilient Mind Membership — shrnutí — Položka seznamu 2', 'resilient-hubs', 'membership', 'text', 'Položka seznamu 2', 60), -- from src/pages/ResilientHubs.tsx:246
  ('hubs_membership_item_3', 'Simple integration practices (journaling & reflection)', 'Simple integration practices (journaling & reflection)', 'Resilient Mind Membership — shrnutí — Položka seznamu 3', 'resilient-hubs', 'membership', 'text', 'Položka seznamu 3', 70), -- from src/pages/ResilientHubs.tsx:247
  ('hubs_membership_item_4', 'Access to a private community for Premium members', 'Access to a private community for Premium members', 'Resilient Mind Membership — shrnutí — Položka seznamu 4', 'resilient-hubs', 'membership', 'text', 'Položka seznamu 4', 80), -- from src/pages/ResilientHubs.tsx:248
  ('hubs_membership_closing', 'Resilience isn''t something you''re born with — it''s something you practice gently, one month at a time.', 'Resilience isn''t something you''re born with — it''s something you practice gently, one month at a time.', 'Resilient Mind Membership — shrnutí — Závěrečná věta', 'resilient-hubs', 'membership', 'text', 'Závěrečná věta', 90), -- from src/pages/ResilientHubs.tsx:260
  ('hubs_pain_title', 'Does This Sound Like You?', 'Does This Sound Like You?', 'Poznáváte se v tom? — Nadpis', 'resilient-hubs', 'pain', 'text', 'Nadpis', 10), -- from src/pages/ResilientHubs.tsx:271
  ('hubs_pain_subtitle', 'If you''re nodding to any of these, this program was built for you.', 'If you''re nodding to any of these, this program was built for you.', 'Poznáváte se v tom? — Podnadpis', 'resilient-hubs', 'pain', 'text', 'Podnadpis', 20), -- from src/pages/ResilientHubs.tsx:274
  ('hubs_pain_item_1', 'You feel like you don''t fully belong — not here, not back home', 'You feel like you don''t fully belong — not here, not back home', 'Poznáváte se v tom? — Položka seznamu 1', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 1', 30), -- from src/pages/ResilientHubs.tsx:279
  ('hubs_pain_item_2', 'Loneliness hits you at unexpected moments, even in a crowd', 'Loneliness hits you at unexpected moments, even in a crowd', 'Poznáváte se v tom? — Položka seznamu 2', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 2', 40), -- from src/pages/ResilientHubs.tsx:280
  ('hubs_pain_item_3', 'You struggle to explain what you''re going through to people who haven''t lived abroad', 'You struggle to explain what you''re going through to people who haven''t lived abroad', 'Poznáváte se v tom? — Položka seznamu 3', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 3', 50), -- from src/pages/ResilientHubs.tsx:281
  ('hubs_pain_item_4', 'Cultural differences exhaust you — small things feel overwhelming', 'Cultural differences exhaust you — small things feel overwhelming', 'Poznáváte se v tom? — Položka seznamu 4', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 4', 60), -- from src/pages/ResilientHubs.tsx:282
  ('hubs_pain_item_5', 'You miss your support network and feel isolated in health challenges', 'You miss your support network and feel isolated in health challenges', 'Poznáváte se v tom? — Položka seznamu 5', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 5', 70), -- from src/pages/ResilientHubs.tsx:283
  ('hubs_pain_item_6', 'You''ve lost parts of your identity and don''t know who you''re becoming', 'You''ve lost parts of your identity and don''t know who you''re becoming', 'Poznáváte se v tom? — Položka seznamu 6', 'resilient-hubs', 'pain', 'text', 'Položka seznamu 6', 80), -- from src/pages/ResilientHubs.tsx:284
  ('hubs_pain_quote', '"You don''t need to figure this out alone. I''ve been exactly where you are — and I built this program to be the guide I wished I had."', '"You don''t need to figure this out alone. I''ve been exactly where you are — and I built this program to be the guide I wished I had."', 'Poznáváte se v tom? — Citát (včetně uvozovek)', 'resilient-hubs', 'pain', 'textarea', 'Citát (včetně uvozovek)', 90), -- from src/pages/ResilientHubs.tsx:297
  ('hubs_pain_attribution', '— Silvie, Founder', '— Silvie, Founder', 'Poznáváte se v tom? — Podpis pod citátem', 'resilient-hubs', 'pain', 'text', 'Podpis pod citátem', 100), -- from src/pages/ResilientHubs.tsx:299
  ('hubs_pricing_badge', 'Choose Your Path', 'Choose Your Path', 'Ceník a jak začít — Odznak nad nadpisem', 'resilient-hubs', 'pricing', 'text', 'Odznak nad nadpisem', 10), -- from src/pages/ResilientHubs.tsx:443
  ('hubs_pricing_title_prefix', 'Invest in Your ', 'Invest in Your ', 'Ceník a jak začít — Nadpis — text před zvýrazněním', 'resilient-hubs', 'pricing', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/ResilientHubs.tsx:446
  ('hubs_pricing_title_highlight', 'Transformation', 'Transformation', 'Ceník a jak začít — Nadpis — zvýrazněná část', 'resilient-hubs', 'pricing', 'text', 'Nadpis — zvýrazněná část', 30), -- from src/pages/ResilientHubs.tsx:446
  ('hubs_pricing_subtitle', 'Now is your moment to invest in your body, mind, and resilience — and step into a life of clarity, calm and confidence, no matter where the world takes you.', 'Now is your moment to invest in your body, mind, and resilience — and step into a life of clarity, calm and confidence, no matter where the world takes you.', 'Ceník a jak začít — Podnadpis', 'resilient-hubs', 'pricing', 'textarea', 'Podnadpis', 40), -- from src/pages/ResilientHubs.tsx:449
  ('membership_howto_title', 'How to Get Started', 'How to Get Started', 'Ceník a jak začít — Nadpis boxu "Jak začít" (sdíleno se stránkou Membership)', 'resilient-hubs', 'pricing', 'text', 'Nadpis boxu "Jak začít" (sdíleno se stránkou Membership)', 50), -- from src/pages/Membership.tsx:471
  ('membership_howto_step_1', 'Choose the membership that suits you.', 'Choose the membership that suits you.', 'Ceník a jak začít — Krok 1 (sdíleno se stránkou Membership)', 'resilient-hubs', 'pricing', 'text', 'Krok 1 (sdíleno se stránkou Membership)', 60), -- from src/pages/Membership.tsx:476
  ('membership_howto_step_2', 'Click Sign Up to create your personal account.', 'Click Sign Up to create your personal account.', 'Ceník a jak začít — Krok 2 (sdíleno se stránkou Membership)', 'resilient-hubs', 'pricing', 'text', 'Krok 2 (sdíleno se stránkou Membership)', 70), -- from src/pages/Membership.tsx:477
  ('membership_howto_step_3', 'Complete your secure payment via Stripe.', 'Complete your secure payment via Stripe.', 'Ceník a jak začít — Krok 3 (sdíleno se stránkou Membership)', 'resilient-hubs', 'pricing', 'text', 'Krok 3 (sdíleno se stránkou Membership)', 80), -- from src/pages/Membership.tsx:478
  ('membership_howto_step_4', 'You''ll receive a welcome email and instant access to your private Dashboard with the full 12-month programme.', 'You''ll receive a welcome email and instant access to your private Dashboard with the full 12-month programme.', 'Ceník a jak začít — Krok 4 (sdíleno se stránkou Membership)', 'resilient-hubs', 'pricing', 'text', 'Krok 4 (sdíleno se stránkou Membership)', 90), -- from src/pages/Membership.tsx:479
  ('membership_howto_note', 'The Membership program teaches you how to look after your mind, regulate stress, and grow self-awareness — one gentle practice at a time.', 'The Membership program teaches you how to look after your mind, regulate stress, and grow self-awareness — one gentle practice at a time.', 'Ceník a jak začít — Uzavírací věta pod krokovým návodem (sdíleno, stejný klíč jako v sekci 12měsíční členství)', 'resilient-hubs', 'pricing', 'textarea', 'Uzavírací věta pod krokovým návodem (sdíleno, stejný klíč jako v sekci 12měsíční členství)', 100), -- from src/pages/Membership.tsx:494
  ('hubs_pricing_freeguide_prefix', 'Not sure yet? ', 'Not sure yet? ', 'Ceník a jak začít — Text před odkazem "Not sure yet?"', 'resilient-hubs', 'pricing', 'text', 'Text před odkazem "Not sure yet?"', 110), -- from src/pages/ResilientHubs.tsx:485
  ('hubs_pricing_freeguide_link', 'Download our free guide', 'Download our free guide', 'Ceník a jak začít — Odkaz — Stáhnout průvodce zdarma', 'resilient-hubs', 'pricing', 'text', 'Odkaz — Stáhnout průvodce zdarma', 120), -- from src/pages/ResilientHubs.tsx:485
  ('hubs_pricing_freeguide_suffix', 'and experience the program first.', 'and experience the program first.', 'Ceník a jak začít — Text za odkazem', 'resilient-hubs', 'pricing', 'text', 'Text za odkazem', 130), -- from src/pages/ResilientHubs.tsx:485
  ('hubs_resilience_title', 'What if resilience wasn''t about pushing harder — but about learning how to care for your mind and nervous system, step by step?', 'What if resilience wasn''t about pushing harder — but about learning how to care for your mind and nervous system, step by step?', 'Co když odolnost... — motivační sekce — Nadpis (otázka)', 'resilient-hubs', 'resilience', 'textarea', 'Nadpis (otázka)', 10), -- from src/pages/ResilientHubs.tsx:201
  ('hubs_resilience_body', 'The Membership Online Program is built on a simple idea: you don''t need more information — you need practical tools you can actually use when life feels overwhelming.', 'The Membership Online Program is built on a simple idea: you don''t need more information — you need practical tools you can actually use when life feels overwhelming.', 'Co když odolnost... — motivační sekce — Odstavec', 'resilient-hubs', 'resilience', 'textarea', 'Odstavec', 20), -- from src/pages/ResilientHubs.tsx:204
  ('hubs_resilience_lead', 'Instead of trying to "fix yourself," you learn how to:', 'Instead of trying to "fix yourself," you learn how to:', 'Co když odolnost... — motivační sekce — Text před seznamem', 'resilient-hubs', 'resilience', 'text', 'Text před seznamem', 30), -- from src/pages/ResilientHubs.tsx:207
  ('hubs_resilience_item_1', 'Understand your reactions', 'Understand your reactions', 'Co když odolnost... — motivační sekce — Položka seznamu 1', 'resilient-hubs', 'resilience', 'text', 'Položka seznamu 1', 40), -- from src/pages/ResilientHubs.tsx:210
  ('hubs_resilience_item_2', 'Regulate stress and emotions', 'Regulate stress and emotions', 'Co když odolnost... — motivační sekce — Položka seznamu 2', 'resilient-hubs', 'resilience', 'text', 'Položka seznamu 2', 50), -- from src/pages/ResilientHubs.tsx:211
  ('hubs_resilience_item_3', 'Build self-awareness and confidence', 'Build self-awareness and confidence', 'Co když odolnost... — motivační sekce — Položka seznamu 3', 'resilient-hubs', 'resilience', 'text', 'Položka seznamu 3', 60), -- from src/pages/ResilientHubs.tsx:212
  ('hubs_resilience_item_4', 'Respond to challenges with more calm and clarity', 'Respond to challenges with more calm and clarity', 'Co když odolnost... — motivační sekce — Položka seznamu 4', 'resilient-hubs', 'resilience', 'text', 'Položka seznamu 4', 70), -- from src/pages/ResilientHubs.tsx:213
  ('hubs_resilience_closing', 'This is where resilience becomes something you practice, not something you force.', 'This is where resilience becomes something you practice, not something you force.', 'Co když odolnost... — motivační sekce — Závěrečná věta', 'resilient-hubs', 'resilience', 'text', 'Závěrečná věta', 80), -- from src/pages/ResilientHubs.tsx:225
  ('hubs_transform_title_prefix', 'Your ', 'Your ', '12měsíční transformace — Nadpis — text před zvýrazněním', 'resilient-hubs', 'transform', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/ResilientHubs.tsx:311
  ('hubs_transform_title_highlight', '12-Month Transformation', '12-Month Transformation', '12měsíční transformace — Nadpis — zvýrazněná část', 'resilient-hubs', 'transform', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/ResilientHubs.tsx:311
  ('hubs_transform_subtitle', 'Each month tackles a different dimension of expat resilience. By the end, you''ll have an unshakable inner foundation.', 'Each month tackles a different dimension of expat resilience. By the end, you''ll have an unshakable inner foundation.', '12měsíční transformace — Podnadpis', 'resilient-hubs', 'transform', 'textarea', 'Podnadpis', 30), -- from src/pages/ResilientHubs.tsx:314
  ('hubs_transform_item_1_title', 'Inner Stability', 'Inner Stability', '12měsíční transformace — Karta 1 — nadpis (Inner Stability)', 'resilient-hubs', 'transform', 'text', 'Karta 1 — nadpis (Inner Stability)', 40), -- from src/pages/ResilientHubs.tsx:320
  ('hubs_transform_item_1_desc', 'Build emotional resilience that doesn''t depend on your external circumstances', 'Build emotional resilience that doesn''t depend on your external circumstances', '12měsíční transformace — Karta 1 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 1 — popis', 50), -- from src/pages/ResilientHubs.tsx:320
  ('hubs_transform_item_2_title', 'Stress Management', 'Stress Management', '12měsíční transformace — Karta 2 — nadpis (Stress Management)', 'resilient-hubs', 'transform', 'text', 'Karta 2 — nadpis (Stress Management)', 60), -- from src/pages/ResilientHubs.tsx:321
  ('hubs_transform_item_2_desc', 'Master EFT tapping, Byron Katie''s method, and mindfulness for real-world challenges', 'Master EFT tapping, Byron Katie''s method, and mindfulness for real-world challenges', '12měsíční transformace — Karta 2 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 2 — popis', 70), -- from src/pages/ResilientHubs.tsx:321
  ('hubs_transform_item_3_title', 'Cultural Navigation', 'Cultural Navigation', '12měsíční transformace — Karta 3 — nadpis (Cultural Navigation)', 'resilient-hubs', 'transform', 'text', 'Karta 3 — nadpis (Cultural Navigation)', 80), -- from src/pages/ResilientHubs.tsx:322
  ('hubs_transform_item_3_desc', 'Turn cultural differences from a source of stress into a source of strength', 'Turn cultural differences from a source of stress into a source of strength', '12měsíční transformace — Karta 3 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 3 — popis', 90), -- from src/pages/ResilientHubs.tsx:322
  ('hubs_transform_item_4_title', 'Relationships', 'Relationships', '12měsíční transformace — Karta 4 — nadpis (Relationships)', 'resilient-hubs', 'transform', 'text', 'Karta 4 — nadpis (Relationships)', 100), -- from src/pages/ResilientHubs.tsx:323
  ('hubs_transform_item_4_desc', 'Strengthen bonds with loved ones — both far away and in your new home', 'Strengthen bonds with loved ones — both far away and in your new home', '12měsíční transformace — Karta 4 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 4 — popis', 110), -- from src/pages/ResilientHubs.tsx:323
  ('hubs_transform_item_5_title', 'Creative Expression', 'Creative Expression', '12měsíční transformace — Karta 5 — nadpis (Creative Expression)', 'resilient-hubs', 'transform', 'text', 'Karta 5 — nadpis (Creative Expression)', 120), -- from src/pages/ResilientHubs.tsx:324
  ('hubs_transform_item_5_desc', 'Process complex emotions through art therapy — no artistic talent needed', 'Process complex emotions through art therapy — no artistic talent needed', '12měsíční transformace — Karta 5 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 5 — popis', 130), -- from src/pages/ResilientHubs.tsx:324
  ('hubs_transform_item_6_title', 'Identity & Growth', 'Identity & Growth', '12měsíční transformace — Karta 6 — nadpis (Identity & Growth)', 'resilient-hubs', 'transform', 'text', 'Karta 6 — nadpis (Identity & Growth)', 140), -- from src/pages/ResilientHubs.tsx:325
  ('hubs_transform_item_6_desc', 'Transform your expatriate identity into your greatest asset', 'Transform your expatriate identity into your greatest asset', '12měsíční transformace — Karta 6 — popis', 'resilient-hubs', 'transform', 'text', 'Karta 6 — popis', 150), -- from src/pages/ResilientHubs.tsx:325
  ('hubs_transform_stat_1_label', 'Video Lessons', 'Video Lessons', '12měsíční transformace — Číselný pásek — štítek 1 (počet 48 je zafixovaný v kódu)', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — štítek 1 (počet 48 je zafixovaný v kódu)', 160), -- from src/pages/ResilientHubs.tsx:340
  ('hubs_transform_stat_1_sub', '10-15 min each', '10-15 min each', '12měsíční transformace — Číselný pásek — popisek 1', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — popisek 1', 170), -- from src/pages/ResilientHubs.tsx:340
  ('hubs_transform_stat_2_label', 'Workbooks', 'Workbooks', '12měsíční transformace — Číselný pásek — štítek 2 (počet 48 je zafixovaný v kódu)', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — štítek 2 (počet 48 je zafixovaný v kódu)', 180), -- from src/pages/ResilientHubs.tsx:341
  ('hubs_transform_stat_2_sub', 'With practical exercises', 'With practical exercises', '12měsíční transformace — Číselný pásek — popisek 2', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — popisek 2', 190), -- from src/pages/ResilientHubs.tsx:341
  ('hubs_transform_stat_3_label', 'Monthly Themes', 'Monthly Themes', '12měsíční transformace — Číselný pásek — štítek 3 (počet 12 je zafixovaný v kódu)', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — štítek 3 (počet 12 je zafixovaný v kódu)', 200), -- from src/pages/ResilientHubs.tsx:342
  ('hubs_transform_stat_3_sub', 'Comprehensive journey', 'Comprehensive journey', '12měsíční transformace — Číselný pásek — popisek 3', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — popisek 3', 210), -- from src/pages/ResilientHubs.tsx:342
  ('hubs_transform_stat_4_label', 'Therapy Methods', 'Therapy Methods', '12měsíční transformace — Číselný pásek — štítek 4 (počet 3 je zafixovaný v kódu)', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — štítek 4 (počet 3 je zafixovaný v kódu)', 220), -- from src/pages/ResilientHubs.tsx:343
  ('hubs_transform_stat_4_sub', 'EFT, Art, Meditation', 'EFT, Art, Meditation', '12měsíční transformace — Číselný pásek — popisek 4', 'resilient-hubs', 'transform', 'text', 'Číselný pásek — popisek 4', 230), -- from src/pages/ResilientHubs.tsx:343
  ('membership_whydifferent_title_prefix', 'Why Resilient Mind Is ', 'Why Resilient Mind Is ', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Nadpis — text před zvýrazněním', 'resilient-hubs', 'whydifferent', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/Membership.tsx:520
  ('membership_whydifferent_title_highlight', 'Different', 'Different', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Nadpis — zvýrazněná část', 'resilient-hubs', 'whydifferent', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/Membership.tsx:520
  ('membership_whydifferent_subtitle', 'This isn''t generic self-help. It''s a program built from real expatriate experience.', 'This isn''t generic self-help. It''s a program built from real expatriate experience.', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Podnadpis', 'resilient-hubs', 'whydifferent', 'text', 'Podnadpis', 30), -- from src/pages/Membership.tsx:523
  ('membership_whydifferent_1_title', 'Built by someone who''s lived it', 'Built by someone who''s lived it', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 1 — nadpis', 'resilient-hubs', 'whydifferent', 'text', 'Karta 1 — nadpis', 40), -- from src/pages/Membership.tsx:529
  ('shared_silvie_bio_long', 'Silvie has 13+ years of expatriate experience across multiple countries. Every technique in this program was forged in real life — not a textbook.', 'Silvie has 13+ years of expatriate experience across multiple countries. Every technique in this program was forged in real life — not a textbook.', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 1 — popis (životopis Silvie)', 'resilient-hubs', 'whydifferent', 'textarea', 'Karta 1 — popis (životopis Silvie)', 50), -- from src/pages/Membership.tsx:530
  ('membership_whydifferent_2_title', 'Three proven methods, one program', 'Three proven methods, one program', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 2 — nadpis', 'resilient-hubs', 'whydifferent', 'text', 'Karta 2 — nadpis', 60), -- from src/pages/Membership.tsx:534
  ('membership_whydifferent_2_desc', 'We combine EFT tapping (evidence-based stress relief), expressive art therapy (emotional processing), and guided meditation (inner calm) into a single, cohesive journey.', 'We combine EFT tapping (evidence-based stress relief), expressive art therapy (emotional processing), and guided meditation (inner calm) into a single, cohesive journey.', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 2 — popis', 'resilient-hubs', 'whydifferent', 'textarea', 'Karta 2 — popis', 70), -- from src/pages/Membership.tsx:535
  ('membership_whydifferent_3_title', 'Made for busy expat lives', 'Made for busy expat lives', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 3 — nadpis', 'resilient-hubs', 'whydifferent', 'text', 'Karta 3 — nadpis', 80), -- from src/pages/Membership.tsx:539
  ('membership_whydifferent_3_desc', '15–30 minutes daily. No live schedules. Group calls included with Premium membership. Watch when you want, practice at your own pace.', '15–30 minutes daily. No live schedules. Group calls included with Premium membership. Watch when you want, practice at your own pace.', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 3 — popis', 'resilient-hubs', 'whydifferent', 'textarea', 'Karta 3 — popis', 90), -- from src/pages/Membership.tsx:540
  ('membership_whydifferent_4_title', 'Not just coping — transforming', 'Not just coping — transforming', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 4 — nadpis', 'resilient-hubs', 'whydifferent', 'text', 'Karta 4 — nadpis', 100), -- from src/pages/Membership.tsx:544
  ('membership_whydifferent_4_desc', 'Other programs teach you to ''manage'' challenges. We help you turn uncertainty, cultural stress, and identity shifts into actual sources of strength and growth.', 'Other programs teach you to ''manage'' challenges. We help you turn uncertainty, cultural stress, and identity shifts into actual sources of strength and growth.', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership) — Karta 4 — popis', 'resilient-hubs', 'whydifferent', 'textarea', 'Karta 4 — popis', 110) -- from src/pages/Membership.tsx:545
ON CONFLICT (key) DO NOTHING;
