-- CMS phase 2: cms_sections rows for every (page, section) introduced by
-- 20260814120000_seed_cms_navbar.sql .. 20260814122100_seed_cms_legal.sql
-- (docs/cms-final-seed.md). One row per section actually rendered on a page;
-- title/anchor/route come from the same docs/cms-keys-*.json metadata used to
-- generate those cms_content rows (membership's own sections are hand-authored,
-- see docs/cms-final-seed.md). sort_order is the section's position on the page,
-- in steps of 10, taken from the lowest sort_order among its fields.
-- ON CONFLICT (page, section_key) DO NOTHING, same reasoning as cms_content:
-- never overwrite a row a client may already be seeing/editing.

INSERT INTO public.cms_sections (page, section_key, title, description, anchor, route, sort_order) VALUES
  ('blog', 'hero', 'Úvodní hlavička', NULL, 'cms-blog-hero', '/blog', 10),
  ('blog', 'seznam_clanku', 'Seznam článků', NULL, 'cms-blog-list', '/blog', 20),
  ('blog', 'newsletter', 'Prázdný stav a přihlášení k odběru', NULL, 'cms-blog-newsletter', '/blog', 30),
  ('blog-post', 'loading', 'Načítání článku', NULL, 'cms-blogpost-loading', '/blog/:slug', 10),
  ('blog-post', 'navigace', 'Navigace', NULL, 'cms-blogpost-nav', '/blog/:slug', 20),
  ('blog-post', 'paywall', 'Placená zeď (nedostatečné členství)', NULL, 'cms-blogpost-paywall', '/blog/:slug', 30),
  ('booking', 'hero', 'Úvodní hlavička', NULL, 'cms-booking-hero', '/booking', 10),
  ('booking', 'krok1', 'Krok 1 – výběr typu sezení', NULL, 'cms-booking-step1', '/booking', 20),
  ('booking', 'krok2', 'Krok 2 – výběr data', NULL, 'cms-booking-step2', '/booking', 30),
  ('booking', 'krok3', 'Krok 3 – výběr času', NULL, 'cms-booking-step3', '/booking', 40),
  ('booking', 'krok4', 'Krok 4 – kontaktní údaje a shrnutí', NULL, 'cms-booking-step4', '/booking', 50),
  ('booking-success', 'nacitani', 'Stav: načítání rezervace', NULL, 'cms-booking-success-loading', '/booking/success', 10),
  ('booking-success', 'chyba', 'Stav: rezervace nenalezena', NULL, 'cms-booking-success-error', '/booking/success', 20),
  ('booking-success', 'typy_sluzeb', 'Názvy typů sezení', NULL, 'cms-booking-success-details', '/booking/success', 30),
  ('booking-success', 'hlavicka', 'Hlavička — potvrzeno / vytvořeno', NULL, 'cms-booking-success-header', '/booking/success', 40),
  ('booking-success', 'detaily', 'Karta „Detaily rezervace"', NULL, 'cms-booking-success-details', '/booking/success', 50),
  ('booking-success', 'akce', 'Tlačítka pod detaily rezervace', NULL, 'cms-booking-success-actions', '/booking/success', 60),
  ('booking-success', 'co_dal', 'Box „Co bude dál?"', NULL, 'cms-booking-success-next', '/booking/success', 70),
  ('booking-success', 'kontakt', 'Kontaktní informace úplně dole', NULL, 'cms-booking-success-contact', '/booking/success', 80),
  ('checkout', 'navigace', 'Navigace', NULL, 'cms-checkout-summary', '/checkout', 10),
  ('checkout', 'shrnuti', 'Shrnutí objednávky', NULL, 'cms-checkout-summary', '/checkout', 20),
  ('checkout', 'chyby', 'Chybové hlášky', NULL, 'cms-checkout-summary', '/checkout', 30),
  ('checkout', 'akce', 'Akce a doplňkové texty', NULL, 'cms-checkout-summary', '/checkout', 40),
  ('checkout-success', 'prihlaseni', 'Stav: nutné přihlášení', NULL, 'cms-checkout-success-login', '/checkout/success', 10),
  ('checkout-success', 'bez_session', 'Stav: platba nenalezena', NULL, 'cms-checkout-success-no-session', '/checkout/success', 20),
  ('checkout-success', 'zpracovani', 'Stav: zpracování platby', NULL, 'cms-checkout-success-processing', '/checkout/success', 30),
  ('checkout-success', 'cekani_na_aktivaci', 'Stav: platba prošla, členství se ještě aktivuje', NULL, 'cms-checkout-success-pending', '/checkout/success', 40),
  ('checkout-success', 'uspech', 'Stav: úspěšná platba a aktivace', NULL, 'cms-checkout-success-success', '/checkout/success', 50),
  ('endometriosis', 'hero', 'Úvodní obrazovka', NULL, 'cms-endo-hero', '/endometriosis-hub', 10),
  ('endometriosis', 'focus', 'Co je zahrnuto — měsíce programu', NULL, 'cms-endo-focus', '/endometriosis-hub', 20),
  ('endometriosis', 'whatget', 'Co získáte', NULL, 'cms-endo-whatget', '/endometriosis-hub', 30),
  ('endometriosis', 'cta', 'Výzva k akci', NULL, 'cms-endo-cta', '/endometriosis-hub', 40),
  ('free-guide', 'navigace', 'Navigace', NULL, 'cms-freeguide-back', '/free-guide', 10),
  ('free-guide', 'hero', 'Úvodní obrazovka', NULL, 'cms-freeguide-hero', '/free-guide', 20),
  ('free-guide', 'obsah_baliku', 'Co balíček obsahuje', NULL, 'cms-freeguide-included', '/free-guide', 30),
  ('free-guide', 'reference', 'Reference / citát', NULL, 'cms-freeguide-social_proof', '/free-guide', 40),
  ('free-guide', 'formular', 'Formulář pro stažení', NULL, 'cms-freeguide-form', '/free-guide', 50),
  ('free-guide', 'upsell', 'Doplňkový text pod formulářem', NULL, 'cms-freeguide-upsell', '/free-guide', 60),
  ('homepage', 'session_header', 'Sekce ceníku na homepage — nadpis', NULL, 'cms-homepage-session', '/', 10),
  ('homepage', 'session_kroky', 'Jak začít (4 kroky)', NULL, 'cms-homepage-session', '/', 20),
  ('homepage', 'session_popis', 'Popisný odstavec o programu', NULL, 'cms-homepage-session', '/', 30),
  ('homepage', 'session_karta', 'Karta „1:1 Session" (cena zůstává mimo CMS)', NULL, 'cms-homepage-session', '/', 40),
  ('legal', 'terms_hero', 'Obchodní podmínky — Úvodní hlavička', NULL, 'cms-terms-hero', '/terms', 10),
  ('legal', 'terms_intro', 'Obchodní podmínky — Podnadpis', NULL, 'cms-terms-intro', '/terms', 20),
  ('legal', 'terms_s1', 'Obchodní podmínky — 1. Obecná ustanovení', NULL, 'cms-terms-s1', '/terms', 30),
  ('legal', 'terms_s2', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy', NULL, 'cms-terms-s2', '/terms', 40),
  ('legal', 'terms_s3', 'Obchodní podmínky — 3. Cena a platební podmínky', NULL, 'cms-terms-s3', '/terms', 50),
  ('legal', 'terms_s4', 'Obchodní podmínky — 4. Dodací podmínky', NULL, 'cms-terms-s4', '/terms', 60),
  ('legal', 'terms_s5', 'Obchodní podmínky — 5. Autorská práva a zabezpečení přístupu', NULL, 'cms-terms-s5', '/terms', 70),
  ('legal', 'terms_s6', 'Obchodní podmínky — 6. Odstoupení od smlouvy', NULL, 'cms-terms-s6', '/terms', 80),
  ('legal', 'terms_s7', 'Obchodní podmínky — 7. Vadné plnění', NULL, 'cms-terms-s7', '/terms', 90),
  ('legal', 'terms_s8', 'Obchodní podmínky — 8. Záruka vrácení peněz', NULL, 'cms-terms-s8', '/terms', 100),
  ('legal', 'terms_s9', 'Obchodní podmínky — 9. Vyloučení odpovědnosti', NULL, 'cms-terms-s9', '/terms', 110),
  ('legal', 'terms_s10', 'Obchodní podmínky — 10. Ochrana osobních údajů', NULL, 'cms-terms-s10', '/terms', 120),
  ('legal', 'terms_s11', 'Obchodní podmínky — 11. Závěrečná ustanovení', NULL, 'cms-terms-s11', '/terms', 130),
  ('legal', 'privacy_hero', 'Zásady ochrany osobních údajů (GDPR) — Úvodní hlavička', NULL, 'cms-privacy-hero', '/privacy', 140),
  ('legal', 'privacy_intro', 'Zásady ochrany osobních údajů (GDPR) — Úvod', NULL, 'cms-privacy-intro', '/privacy', 150),
  ('legal', 'privacy_s1', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů', NULL, 'cms-privacy-s1', '/privacy', 160),
  ('legal', 'privacy_s2', 'Zásady ochrany osobních údajů (GDPR) — 2. Kontaktní údaje', NULL, 'cms-privacy-s2', '/privacy', 170),
  ('legal', 'privacy_s3', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce', NULL, 'cms-privacy-s3', '/privacy', 180),
  ('legal', 'privacy_s4', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů', NULL, 'cms-privacy-s4', '/privacy', 190),
  ('legal', 'privacy_s5', 'Zásady ochrany osobních údajů (GDPR) — 5. Fotografie a audiovizuální záznamy', NULL, 'cms-privacy-s5', '/privacy', 200),
  ('legal', 'privacy_s6', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies', NULL, 'cms-privacy-s6', '/privacy', 210),
  ('legal', 'privacy_s7', 'Zásady ochrany osobních údajů (GDPR) — 7. Zabezpečení údajů', NULL, 'cms-privacy-s7', '/privacy', 220),
  ('legal', 'privacy_s8', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám', NULL, 'cms-privacy-s8', '/privacy', 230),
  ('legal', 'privacy_s9', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva', NULL, 'cms-privacy-s9', '/privacy', 240),
  ('legal', 'privacy_s10', 'Zásady ochrany osobních údajů (GDPR) — 10. Mlčenlivost', NULL, 'cms-privacy-s10', '/privacy', 250),
  ('legal', 'cookies_hero', 'Zásady používání cookies — Úvodní hlavička', NULL, 'cms-cookies-hero', '/cookies', 260),
  ('legal', 'cookies_intro', 'Zásady používání cookies — Úvod', NULL, 'cms-cookies-intro', '/cookies', 270),
  ('legal', 'cookies_s1', 'Zásady používání cookies — 1. Co jsou cookies?', NULL, 'cms-cookies-s1', '/cookies', 280),
  ('legal', 'cookies_s2', 'Zásady používání cookies — 2. Typy cookies, které používáme', NULL, 'cms-cookies-s2', '/cookies', 290),
  ('legal', 'cookies_s2a', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies', NULL, 'cms-cookies-s2a', '/cookies', 300),
  ('legal', 'cookies_s2b', 'Zásady používání cookies — 2b) Funkční cookies / cookies pro předvolby', NULL, 'cms-cookies-s2b', '/cookies', 310),
  ('legal', 'cookies_s2c', 'Zásady používání cookies — 2c) Registrační / autentizační cookies', NULL, 'cms-cookies-s2c', '/cookies', 320),
  ('legal', 'cookies_s2d', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies', NULL, 'cms-cookies-s2d', '/cookies', 330),
  ('legal', 'cookies_s2e', 'Zásady používání cookies — 2e) Geolokační cookies', NULL, 'cms-cookies-s2e', '/cookies', 340),
  ('legal', 'cookies_s3', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies', NULL, 'cms-cookies-s3', '/cookies', 350),
  ('legal', 'cookies_s4', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran', NULL, 'cms-cookies-s4', '/cookies', 360),
  ('legal', 'cookies_s5', 'Zásady používání cookies — 5. Cookies sociálních sítí', NULL, 'cms-cookies-s5', '/cookies', 370),
  ('legal', 'cookies_s6', 'Zásady používání cookies — 6. Správa a zakázání cookies', NULL, 'cms-cookies-s6', '/cookies', 380),
  ('legal', 'cookies_s7', 'Zásady používání cookies — 7. Souhlas s cookies', NULL, 'cms-cookies-s7', '/cookies', 390),
  ('legal', 'cookies_s8', 'Zásady používání cookies — 8. Aktualizace zásad', NULL, 'cms-cookies-s8', '/cookies', 400),
  ('membership', 'hero', 'Úvodní obrazovka', 'Levý sloupec s textem a pravý se fotkou hned pod navigací.', 'cms-membership-hero', '/membership', 10),
  ('membership', 'problem', 'Problém', 'Krátká sekce pojmenovávající problém čtenářky.', 'cms-membership-problem', '/membership', 20),
  ('membership', 'empathy', 'Empatie', 'Sekce vyjadřující pochopení situace čtenářky.', 'cms-membership-empathy', '/membership', 30),
  ('membership', 'solution', 'Řešení', 'Nadpis a text představující členství jako řešení. Odznak navíc se zobrazuje jen na /membership2.', 'cms-membership-solution', '/membership', 40),
  ('membership', 'getitems', 'Co v členství získáte', 'Čtyři karty s tím, co je součástí členství.', 'cms-membership-getitems', '/membership', 50),
  ('membership', 'benefits', 'Přínosy v běžném životě', 'Seznam čtyř přínosů členství.', 'cms-membership-benefits', '/membership', 60),
  ('membership', 'transformation', 'Proměna — obrázek a popisek', 'Fotka „před/po“ a popisek pod ní. Jen na /membership — na /membership2 je místo toho interaktivní sekce „Před / Po“ (viz sekce transformation2).', 'cms-membership-transformation', '/membership', 70),
  ('membership', 'transformation2', 'Proměna — Před / Po (jen /membership2)', 'Interaktivní sloupce „Před“ a „Po“ — jen na /membership2.', 'cms-membership-transformation2', '/membership2', 80),
  ('membership', 'about', 'O programu a autorce', 'Přemostění mezi obsahem a nabídkou, s krátkým životopisem Silvie.', 'cms-membership-about', '/membership', 90),
  ('membership', 'offer', 'Nabídka — nadpis a odznaky', 'Nadpis nabídkové sekce, tři odznaky nad cenovými kartami a odkaz na 12měsíční členství (Resilient Hubs).', 'cms-membership-offer', '/membership', 100),
  ('membership', 'teaser_basic', 'Cenová karta — Basic', 'Karta plánu Basic. Cena €37 zůstává mimo CMS.', 'cms-membership-teaser_basic', '/membership', 110),
  ('membership', 'teaser_premium', 'Cenová karta — Premium', 'Karta plánu Premium. Cena €47 zůstává mimo CMS.', 'cms-membership-teaser_premium', '/membership', 120),
  ('membership', 'howto', '12měsíční členství — doplňkové odznaky', 'Jen tři odznaky pod krokovým návodem — samotný nadpis, kroky a závěrečná poznámka téhož bloku se editují na stránce Resilient Hubs (sdílené klíče membership_howto_title/step_*/note).', 'cms-membership-howto', '/membership', 130),
  ('membership', 'final_cta', 'Závěrečná výzva k akci', 'Poslední sekce stránky s tlačítkem na nabídku.', 'cms-membership-final_cta', '/membership', 140),
  ('membership', 'membership2_seo', 'SEO (jen /membership2)', 'Meta title/description pro záložní verzi stránky, mimo viditelný obsah.', NULL, '/membership2', 150),
  ('navbar', 'menu', 'Hlavní menu', NULL, 'cms-navbar-menu', '/', 10),
  ('navbar', 'account', 'Účet a přihlášení', NULL, 'cms-navbar-menu', '/', 20),
  ('pricing', 'hero', 'Úvodní obrazovka', NULL, 'cms-pricing-hero', '/pricing', 10),
  ('pricing', 'uvod', 'Úvodní text pod hero sekcí', NULL, 'cms-pricing-intro', '/pricing', 20),
  ('pricing', 'programy', 'Členské programy', NULL, 'cms-pricing-tiers', '/pricing', 30),
  ('pricing', 'obsah_clenstvi', 'Co je součástí členství', NULL, 'cms-pricing-included', '/pricing', 40),
  ('pricing', 'vyzva', 'Výzva k akci (dole na stránce)', NULL, 'cms-pricing-cta', '/pricing', 50),
  ('pricing-success', 'prihlaseni', 'Stav: nutné přihlášení', NULL, 'cms-pricing-success-login', '/pricing/success', 10),
  ('pricing-success', 'bez_session', 'Stav: platba nenalezena', NULL, 'cms-pricing-success-no-session', '/pricing/success', 20),
  ('pricing-success', 'zpracovani', 'Stav: zpracování platby', NULL, 'cms-pricing-success-processing', '/pricing/success', 30),
  ('pricing-success', 'cekani_na_aktivaci', 'Stav: platba prošla, členství se ještě aktivuje', NULL, 'cms-pricing-success-pending', '/pricing/success', 40),
  ('pricing-success', 'cekani_podpora', 'Stav čekání — kontaktní box', NULL, 'cms-pricing-success-pending', '/pricing/success', 50),
  ('pricing-success', 'uspech', 'Stav: úspěšná platba a aktivace', NULL, 'cms-pricing-success-success', '/pricing/success', 60),
  ('pricing-success', 'co_dal', 'Box „Co bude dál?"', NULL, 'cms-pricing-success-next', '/pricing/success', 70),
  ('pricing-success', 'rychly_pristup', 'Karty rychlého přístupu', NULL, 'cms-pricing-success-cards', '/pricing/success', 80),
  ('pricing-success', 'vyzva', 'Výzva k akci (dole na stránce)', NULL, 'cms-pricing-success-cta', '/pricing/success', 90),
  ('pricing-success', 'podpora', 'Kontaktní box úplně dole', NULL, 'cms-pricing-success-success', '/pricing/success', 100),
  ('resilient-hub', 'hero', 'Úvodní obrazovka', NULL, 'cms-hub-hero', '/resilient-hub', 10),
  ('resilient-hub', 'intro_video', 'Úvodní video', NULL, 'cms-hub-intro_video', '/resilient-hub', 20),
  ('resilient-hub', 'intro', 'Co je odolnost — úvodní text', NULL, 'cms-hub-intro', '/resilient-hub', 30),
  ('resilient-hub', 'what', 'Co je Resilient Hub', NULL, 'cms-hub-what', '/resilient-hub', 40),
  ('resilient-hub', 'receive', 'Co v programu získáte', NULL, 'cms-hub-receive', '/resilient-hub', 50),
  ('resilient-hub', 'program', 'Program — přepínač video/přehled', NULL, 'cms-hub-program', '/resilient-hub', 60),
  ('resilient-hub', 'program_q1', 'Program — 1. čtvrtletí (měsíce 1–3)', NULL, 'cms-hub-program', '/resilient-hub', 70),
  ('resilient-hub', 'program_q2', 'Program — 2. čtvrtletí (měsíce 4–6)', NULL, 'cms-hub-program', '/resilient-hub', 80),
  ('resilient-hub', 'program_q3', 'Program — 3. čtvrtletí (měsíce 7–9)', NULL, 'cms-hub-program', '/resilient-hub', 90),
  ('resilient-hub', 'program_q4', 'Program — 4. čtvrtletí (měsíce 10–12)', NULL, 'cms-hub-program', '/resilient-hub', 100),
  ('resilient-hub', 'videos_tab', 'Video lekce — stavy a CTA', NULL, 'cms-hub-videos_tab', '/resilient-hub', 110),
  ('resilient-hub', 'additional', 'Doplňkové Resilient Huby', NULL, 'cms-hub-additional', '/resilient-hub', 120),
  ('resilient-hub', 'additional_hub1', 'Doplňkový hub 1 — The Transformed Self', NULL, 'cms-hub-additional', '/resilient-hub', 130),
  ('resilient-hub', 'additional_hub2', 'Doplňkový hub 2 — Endometrióza a chronická bolest', NULL, 'cms-hub-additional', '/resilient-hub', 140),
  ('resilient-hub', 'additional_summary', 'Doplňkové huby — sdílené štítky a souhrn', NULL, 'cms-hub-additional', '/resilient-hub', 150),
  ('resilient-hubs', 'hero', 'Úvodní obrazovka', NULL, 'cms-hubs-hero', '/resilient-hubs', 10),
  ('resilient-hubs', 'details', '12měsíční členství — popis', NULL, 'cms-hubs-details', '/resilient-hubs', 20),
  ('resilient-hubs', 'resilience', 'Co když odolnost... — motivační sekce', NULL, 'cms-hubs-resilience', '/resilient-hubs', 30),
  ('resilient-hubs', 'membership', 'Resilient Mind Membership — shrnutí', NULL, 'cms-hubs-membership', '/resilient-hubs', 40),
  ('resilient-hubs', 'pain', 'Poznáváte se v tom?', NULL, 'cms-hubs-pain', '/resilient-hubs', 50),
  ('resilient-hubs', 'transform', '12měsíční transformace', NULL, 'cms-hubs-transform', '/resilient-hubs', 60),
  ('resilient-hubs', 'howworks', 'Jak to funguje', NULL, 'cms-hubs-howworks', '/resilient-hubs', 70),
  ('resilient-hubs', 'content', 'Náhled obsahu programu', NULL, 'cms-hubs-content', '/resilient-hubs', 80),
  ('resilient-hubs', 'whydifferent', 'Proč je Resilient Mind jiný (sdíleno se stránkou Membership)', NULL, 'cms-hubs-whydifferent', '/resilient-hubs', 90),
  ('resilient-hubs', 'pricing', 'Ceník a jak začít', NULL, 'cms-hubs-pricing', '/resilient-hubs', 100),
  ('resilient-hubs', 'faq', 'Časté dotazy — nadpis (samotné otázky/odpovědi se editují ve správě FAQ, skupina "hubs")', NULL, 'cms-hubs-faq', '/resilient-hubs', 110),
  ('resilient-hubs', 'finalcta', 'Závěrečná výzva', NULL, 'cms-hubs-finalcta', '/resilient-hubs', 120),
  ('shared', 'hlavicka', 'Hlavička balíčku (Free Guide Kit)', NULL, 'cms-freeguidekit-main', '/dashboard', 10),
  ('shared', 'obsah', 'Obsah bloku (lead magnet)', NULL, 'cms-leadmagnet-content', '/', 20),
  ('shared', 'cookie_banner', 'Cookie lišta', NULL, 'cms-shared-cookiebanner', '/', 30),
  ('shared', 'not_found', 'Stránka 404', NULL, 'cms-shared-notfound', '/404', 40),
  ('shared', 'about_preview', 'O mně — náhled na homepage', NULL, 'cms-shared-about-preview', '/', 50),
  ('shared', 'testimonials', 'Reference — nadpis a popisek', NULL, 'cms-shared-testimonials', '/', 60),
  ('shared', 'category_section', 'Sekce měsíce programu', NULL, 'cms-shared-category-section', '/dashboard', 70),
  ('shared', 'video_card', 'Karta videa — členské štítky', NULL, 'cms-shared-video-card', '/dashboard', 80),
  ('shared', 'rano', 'Karta – ráno', NULL, 'cms-freeguidekit-morning', '/dashboard', 90),
  ('shared', 'poledne', 'Karta – poledne', NULL, 'cms-freeguidekit-midday', '/dashboard', 100),
  ('shared', 'formular', 'Formulář (lead magnet)', NULL, 'cms-leadmagnet-form', '/', 110),
  ('shared', 'vecer', 'Karta – večer', NULL, 'cms-freeguidekit-evening', '/dashboard', 120),
  ('shared', 'potvrzeni', 'Potvrzení po odeslání', NULL, 'cms-leadmagnet-success', '/', 130),
  ('shared', 'vyzva_k_akci', 'Výzva k přechodu na členství', NULL, 'cms-freeguidekit-cta', '/dashboard', 140),
  ('shared', 'notifikace', 'Notifikace (toast)', NULL, 'cms-leadmagnet-form', '/', 150),
  ('thank-you', 'navigace', 'Navigace', NULL, 'cms-freeguide-thanks_back', '/thank-you', 10),
  ('thank-you', 'hlavicka', 'Hlavička poděkování', NULL, 'cms-freeguide-thanks_main', '/thank-you', 20),
  ('thank-you', 'upozorneni_email', 'Upozornění na e-mail', NULL, 'cms-freeguide-thanks_email_notice', '/thank-you', 30),
  ('thank-you', 'soubory_ke_stazeni', 'Soubory ke stažení', NULL, 'cms-freeguide-thanks_downloads', '/thank-you', 40),
  ('thank-you', 'sdileni', 'Sdílení s přáteli', NULL, 'cms-freeguide-thanks_share', '/thank-you', 50),
  ('thank-you', 'tlacitko', 'Tlačítko zpět', NULL, 'cms-freeguide-thanks_share', '/thank-you', 60),
  ('workshop-inquiry-form', 'potvrzeni', 'Poděkování po odeslání poptávky', NULL, 'cms-workshopform-success', '/workshopy', 10),
  ('workshop-inquiry-form', 'uvod', 'Úvodní text a nabídka', NULL, 'cms-workshopform-intro', '/workshopy', 20),
  ('workshop-inquiry-form', 'formular', 'Formulář poptávky', NULL, 'cms-workshopform-form', '/workshopy', 30),
  ('workshop-post', 'loading', 'Načítání workshopu', NULL, 'cms-workshoppost-loading', '/workshopy/:slug', 10),
  ('workshop-post', 'navigace', 'Navigace', NULL, 'cms-workshoppost-nav', '/workshopy/:slug', 20),
  ('workshop-post', 'videa', 'Videa workshopu', NULL, 'cms-workshoppost-videos', '/workshopy/:slug', 30),
  ('workshop-post', 'paywall', 'Placená zeď (nedostatečné členství)', NULL, 'cms-workshoppost-paywall', '/workshopy/:slug', 40),
  ('workshop-registration', 'potvrzeni', 'Poděkování po registraci', NULL, 'cms-workshopform-reg-success', '/workshopy/:slug', 10),
  ('workshop-registration', 'uvod', 'Úvodní text a platba', NULL, 'cms-workshopform-reg-intro', '/workshopy/:slug', 20),
  ('workshop-registration', 'formular', 'Registrační formulář', NULL, 'cms-workshopform-reg-form', '/workshopy/:slug', 30),
  ('workshopy', 'hero', 'Úvodní hlavička', NULL, 'cms-workshops-hero', '/workshopy', 10),
  ('workshopy', 'silk_paintings', 'Sekce – Malby na hedvábí', NULL, 'cms-workshops-silk', '/workshopy', 20),
  ('workshopy', 'kids_parents', 'Sekce – Workshopy pro děti a rodiče', NULL, 'cms-workshops-kids', '/workshopy', 30),
  ('workshopy', 'adults', 'Sekce – Workshopy pro dospělé', NULL, 'cms-workshops-adults', '/workshopy', 40),
  ('workshopy', 'nadchazejici', 'Nadcházející workshopy (ze systému)', NULL, 'cms-workshops-upcoming', '/workshopy', 50)
ON CONFLICT (page, section_key) DO NOTHING;
