-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- Membership.tsx + Membership2.tsx. 98 of this page's 117 t() keys -- the other 19
-- (membership_whydifferent_*/faq_*/howto_title/howto_step_*/howto_note, shared_silvie_bio_long) are
-- literally the same t() key/fallback as ResilientHubs.tsx's "why different"/"how to get
-- started"/FAQ sections (that content was copy-pasted from /resilient-hubs into both Membership
-- pages, per the code comments "preserved from /resilient-hubs") and are seeded once, under
-- page='resilient-hubs', by 20260814121100_seed_cms_resilient_hubs.sql -- editing them there updates
-- all three pages. See docs/cms-final-seed.md for the full explanation.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('membership_about_body', 'Created for expat women who feel overwhelmed or disconnected, and are ready to reconnect with themselves, understand their inner patterns, and build a sense of calm, resilience, and home within — wherever they are in the world.', 'Created for expat women who feel overwhelmed or disconnected, and are ready to reconnect with themselves, understand their inner patterns, and build a sense of calm, resilience, and home within — wherever they are in the world.', 'O programu a autorce — Hlavní text', 'membership', 'about', 'textarea', 'Hlavní text', 10), -- from src/pages/Membership.tsx:332
  ('shared_silvie_bio_short', 'Developed by Silvie, an expatriate of 13+ years, this approach blends lived experience with personal development, expressive arts, and holistic therapies — creating a supportive, practical path to navigate life abroad with greater ease and inner stability.', 'Developed by Silvie, an expatriate of 13+ years, this approach blends lived experience with personal development, expressive arts, and holistic therapies — creating a supportive, practical path to navigate life abroad with greater ease and inner stability.', 'O programu a autorce — Krátký životopis Silvie', 'membership', 'about', 'textarea', 'Krátký životopis Silvie', 20), -- from src/pages/Membership.tsx:335
  ('membership_about_cta', 'See Plans & Pricing', 'See Plans & Pricing', 'O programu a autorce — Text tlačítka', 'membership', 'about', 'text', 'Text tlačítka', 30), -- from src/pages/Membership.tsx:341
  ('membership_benefits_title_prefix', 'What this looks like in ', 'What this looks like in ', 'Přínosy v běžném životě — Nadpis — text před zvýrazněním', 'membership', 'benefits', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/Membership.tsx:280
  ('membership_benefits_title_highlight', 'your everyday life', 'your everyday life', 'Přínosy v běžném životě — Nadpis — zvýrazněná část (zlatě)', 'membership', 'benefits', 'text', 'Nadpis — zvýrazněná část (zlatě)', 20), -- from src/pages/Membership.tsx:280
  ('membership_benefits_1', 'Recognise your patterns and respond instead of react.', 'Recognise your patterns and respond instead of react.', 'Přínosy v běžném životě — Bod 1', 'membership', 'benefits', 'text', 'Bod 1', 30), -- from src/pages/Membership.tsx:285
  ('membership_benefits_2', 'Calm your nervous system and feel more in control of your emotions.', 'Calm your nervous system and feel more in control of your emotions.', 'Přínosy v běžném životě — Bod 2', 'membership', 'benefits', 'text', 'Bod 2', 40), -- from src/pages/Membership.tsx:286
  ('membership_benefits_3', 'Create lasting inner stability, even during uncertain times.', 'Create lasting inner stability, even during uncertain times.', 'Přínosy v běžném životě — Bod 3', 'membership', 'benefits', 'text', 'Bod 3', 50), -- from src/pages/Membership.tsx:287
  ('membership_benefits_4', 'Feel grounded, safe, and at home within yourself — wherever you are.', 'Feel grounded, safe, and at home within yourself — wherever you are.', 'Přínosy v běžném životě — Bod 4', 'membership', 'benefits', 'text', 'Bod 4', 60), -- from src/pages/Membership.tsx:288
  ('membership_empathy_title', 'Moving abroad is a big emotional shift.', 'Moving abroad is a big emotional shift.', 'Empatie — Nadpis', 'membership', 'empathy', 'text', 'Nadpis', 10), -- from src/pages/Membership.tsx:194
  ('membership_empathy_body', 'Even when everything looks "right" on the outside, it''s completely normal to feel lost, anxious, or disconnected inside.', 'Even when everything looks "right" on the outside, it''s completely normal to feel lost, anxious, or disconnected inside.', 'Empatie — Text', 'membership', 'empathy', 'textarea', 'Text', 20), -- from src/pages/Membership.tsx:197
  ('membership_final_title_prefix', 'Ready to feel like', 'Ready to feel like', 'Závěrečná výzva k akci — Nadpis — první řádek', 'membership', 'final_cta', 'text', 'Nadpis — první řádek', 10), -- from src/pages/Membership.tsx:622
  ('membership_final_title_highlight', 'yourself', 'yourself', 'Závěrečná výzva k akci — Nadpis — zvýrazněné slovo (zlatě)', 'membership', 'final_cta', 'text', 'Nadpis — zvýrazněné slovo (zlatě)', 20), -- from src/pages/Membership.tsx:624
  ('membership_final_title_suffix', ' again?', ' again?', 'Závěrečná výzva k akci — Nadpis — text po zvýraznění', 'membership', 'final_cta', 'text', 'Nadpis — text po zvýraznění', 30), -- from src/pages/Membership.tsx:624
  ('membership_final_body', 'Take the first gentle step today. No pressure — just support.', 'Take the first gentle step today. No pressure — just support.', 'Závěrečná výzva k akci — Text pod nadpisem', 'membership', 'final_cta', 'text', 'Text pod nadpisem', 40), -- from src/pages/Membership.tsx:627
  ('membership_final_cta', 'Start your journey', 'Start your journey', 'Závěrečná výzva k akci — Text tlačítka', 'membership', 'final_cta', 'text', 'Text tlačítka', 50), -- from src/pages/Membership.tsx:633
  ('membership_final_cta_note', 'Pay as you go · Cancel anytime', 'Pay as you go · Cancel anytime', 'Závěrečná výzva k akci — Poznámka pod tlačítkem', 'membership', 'final_cta', 'text', 'Poznámka pod tlačítkem', 60), -- from src/pages/Membership.tsx:637
  ('membership_getitems_title_prefix', 'Inside, you''ll receive simple, ', 'Inside, you''ll receive simple, ', 'Co v členství získáte — Nadpis — text před zvýrazněním', 'membership', 'getitems', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/Membership.tsx:223
  ('membership_getitems_title_highlight', 'supportive tools', 'supportive tools', 'Co v členství získáte — Nadpis — zvýrazněná část (zlatě)', 'membership', 'getitems', 'text', 'Nadpis — zvýrazněná část (zlatě)', 20), -- from src/pages/Membership.tsx:223
  ('membership_getitems_subtitle', 'Everything is designed to fit into your real life abroad — no pressure, just support.', 'Everything is designed to fit into your real life abroad — no pressure, just support.', 'Co v členství získáte — Podnadpis', 'membership', 'getitems', 'textarea', 'Podnadpis', 30), -- from src/pages/Membership.tsx:226
  ('membership_getitems_1_title', 'EFT tapping & expressive creative art', 'EFT tapping & expressive creative art', 'Co v členství získáte — Karta 1 — nadpis', 'membership', 'getitems', 'text', 'Karta 1 — nadpis', 40), -- from src/pages/Membership.tsx:234
  ('membership_getitems_1_desc', 'Practical techniques to calm your nervous system and gently process what you''re feeling.', 'Practical techniques to calm your nervous system and gently process what you''re feeling.', 'Co v členství získáte — Karta 1 — text', 'membership', 'getitems', 'textarea', 'Karta 1 — text', 50), -- from src/pages/Membership.tsx:235
  ('membership_getitems_2_title', 'Guided practices', 'Guided practices', 'Co v členství získáte — Karta 2 — nadpis', 'membership', 'getitems', 'text', 'Karta 2 — nadpis', 60), -- from src/pages/Membership.tsx:239
  ('membership_getitems_2_desc', 'Audio and video sessions to help you regulate your emotions, day by day.', 'Audio and video sessions to help you regulate your emotions, day by day.', 'Co v členství získáte — Karta 2 — text', 'membership', 'getitems', 'text', 'Karta 2 — text', 70), -- from src/pages/Membership.tsx:240
  ('membership_getitems_3_title', 'A workbook to reconnect with yourself', 'A workbook to reconnect with yourself', 'Co v členství získáte — Karta 3 — nadpis', 'membership', 'getitems', 'text', 'Karta 3 — nadpis', 80), -- from src/pages/Membership.tsx:244
  ('membership_getitems_3_desc', 'Reflective exercises that help you understand your patterns and come home to who you are.', 'Reflective exercises that help you understand your patterns and come home to who you are.', 'Co v členství získáte — Karta 3 — text', 'membership', 'getitems', 'textarea', 'Karta 3 — text', 90), -- from src/pages/Membership.tsx:245
  ('membership_getitems_4_title', 'A gentle structure at your own pace', 'A gentle structure at your own pace', 'Co v členství získáte — Karta 4 — nadpis', 'membership', 'getitems', 'text', 'Karta 4 — nadpis', 100), -- from src/pages/Membership.tsx:249
  ('membership_getitems_4_desc', 'On-demand lessons you can follow whenever life allows — no schedules, no pressure.', 'On-demand lessons you can follow whenever life allows — no schedules, no pressure.', 'Co v členství získáte — Karta 4 — text', 'membership', 'getitems', 'textarea', 'Karta 4 — text', 110), -- from src/pages/Membership.tsx:250
  ('membership_hero_badge', 'Resilient Mind Membership', 'Resilient Mind Membership', 'Úvodní obrazovka — Odznak nad nadpisem', 'membership', 'hero', 'text', 'Odznak nad nadpisem', 10), -- from src/pages/Membership.tsx:107
  ('membership_hero_title_prefix', 'You moved abroad…', 'You moved abroad…', 'Úvodní obrazovka — Nadpis — první řádek', 'membership', 'hero', 'text', 'Nadpis — první řádek', 20), -- from src/pages/Membership.tsx:115
  ('membership_hero_title_suffix', 'so why do you still', 'so why do you still', 'Úvodní obrazovka — Nadpis — druhý řádek, úvodní slova', 'membership', 'hero', 'text', 'Nadpis — druhý řádek, úvodní slova', 30), -- from src/pages/Membership.tsx:116
  ('membership_hero_title_highlight', 'feel off?', 'feel off?', 'Úvodní obrazovka — Nadpis — zvýrazněná část (zlatě)', 'membership', 'hero', 'text', 'Nadpis — zvýrazněná část (zlatě)', 40), -- from src/pages/Membership.tsx:116
  ('membership_hero_subtitle_prefix', 'Stop feeling overwhelmed and start feeling like ', 'Stop feeling overwhelmed and start feeling like ', 'Úvodní obrazovka — Podnadpis — text před zvýrazněným slovem', 'membership', 'hero', 'text', 'Podnadpis — text před zvýrazněným slovem', 50), -- from src/pages/Membership.tsx:120
  ('membership_hero_subtitle_em', 'yourself', 'yourself', 'Úvodní obrazovka — Podnadpis — zvýrazněné slovo (kurzívou)', 'membership', 'hero', 'text', 'Podnadpis — zvýrazněné slovo (kurzívou)', 60), -- from src/pages/Membership.tsx:120
  ('membership_hero_subtitle_suffix', ' again.', ' again.', 'Úvodní obrazovka — Podnadpis — text po zvýrazněném slově', 'membership', 'hero', 'text', 'Podnadpis — text po zvýrazněném slově', 70), -- from src/pages/Membership.tsx:120
  ('membership_hero_description', 'Feel like yourself again.', 'Feel like yourself again.', 'Úvodní obrazovka — Popisný text pod podnadpisem', 'membership', 'hero', 'text', 'Popisný text pod podnadpisem', 80), -- from src/pages/Membership.tsx:124
  ('membership_hero_pillar_1', 'Understand your patterns', 'Understand your patterns', 'Úvodní obrazovka — Pilíř 1 — text', 'membership', 'hero', 'text', 'Pilíř 1 — text', 90), -- from src/pages/Membership.tsx:130
  ('membership_hero_pillar_2', 'Regulate emotions', 'Regulate emotions', 'Úvodní obrazovka — Pilíř 2 — text', 'membership', 'hero', 'text', 'Pilíř 2 — text', 100), -- from src/pages/Membership.tsx:131
  ('membership_hero_pillar_3', 'Create inner stability', 'Create inner stability', 'Úvodní obrazovka — Pilíř 3 — text', 'membership', 'hero', 'text', 'Pilíř 3 — text', 110), -- from src/pages/Membership.tsx:132
  ('membership_hero_pillar_4', 'Feel at home within yourself', 'Feel at home within yourself', 'Úvodní obrazovka — Pilíř 4 — text', 'membership', 'hero', 'text', 'Pilíř 4 — text', 120), -- from src/pages/Membership.tsx:133
  ('membership_hero_cta', 'Start your journey now', 'Start your journey now', 'Úvodní obrazovka — Text tlačítka', 'membership', 'hero', 'text', 'Text tlačítka', 130), -- from src/pages/Membership.tsx:151
  ('membership_hero_cta_note', 'Pay as you go · Cancel anytime', 'Pay as you go · Cancel anytime', 'Úvodní obrazovka — Poznámka pod tlačítkem', 'membership', 'hero', 'text', 'Poznámka pod tlačítkem', 140), -- from src/pages/Membership.tsx:155
  ('membership_hero_image_alt', 'A woman writing in her journal, reconnecting with herself while living abroad', 'A woman writing in her journal, reconnecting with herself while living abroad', 'Úvodní obrazovka — Alt text úvodní fotky', 'membership', 'hero', 'image_url', 'Alt text úvodní fotky', 150), -- from src/pages/Membership.tsx:164
  ('membership_howto_badge_1', 'Secure payment via Stripe', 'Secure payment via Stripe', '12měsíční členství — doplňkové odznaky — Odznak 1', 'membership', 'howto', 'text', 'Odznak 1', 10), -- from src/pages/Membership.tsx:500
  ('membership_howto_badge_2', 'One-time payment — no auto-renewal', 'One-time payment — no auto-renewal', '12měsíční členství — doplňkové odznaky — Odznak 2', 'membership', 'howto', 'text', 'Odznak 2', 20), -- from src/pages/Membership.tsx:504
  ('membership_howto_badge_3', 'Instant access after payment', 'Instant access after payment', '12měsíční členství — doplňkové odznaky — Odznak 3', 'membership', 'howto', 'text', 'Odznak 3', 30), -- from src/pages/Membership.tsx:508
  ('membership2_seo_title', 'Resilient Mind Membership (backup) | Resilient Mind', 'Resilient Mind Membership (backup) | Resilient Mind', 'SEO (jen /membership2) — SEO — title', 'membership', 'membership2_seo', 'text', 'SEO — title', 10), -- from src/pages/Membership2.tsx:65
  ('membership2_seo_description', 'Backup version of the Resilient Mind Membership sales page.', 'Backup version of the Resilient Mind Membership sales page.', 'SEO (jen /membership2) — SEO — meta description', 'membership', 'membership2_seo', 'text', 'SEO — meta description', 20), -- from src/pages/Membership2.tsx:66
  ('membership_offer_title_prefix', 'Choose your ', 'Choose your ', 'Nabídka — nadpis a odznaky — Nadpis — text před zvýrazněním', 'membership', 'offer', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/Membership.tsx:354
  ('membership_offer_title_highlight', 'path', 'path', 'Nabídka — nadpis a odznaky — Nadpis — zvýrazněná část (zlatě)', 'membership', 'offer', 'text', 'Nadpis — zvýrazněná část (zlatě)', 20), -- from src/pages/Membership.tsx:354
  ('membership_offer_badge_1', 'Pay as you go', 'Pay as you go', 'Nabídka — nadpis a odznaky — Odznak 1', 'membership', 'offer', 'text', 'Odznak 1', 30), -- from src/pages/Membership.tsx:358
  ('membership_offer_badge_2', 'Cancel anytime', 'Cancel anytime', 'Nabídka — nadpis a odznaky — Odznak 2', 'membership', 'offer', 'text', 'Odznak 2', 40), -- from src/pages/Membership.tsx:359
  ('membership_offer_badge_3', 'No pressure — just support', 'No pressure — just support', 'Nabídka — nadpis a odznaky — Odznak 3', 'membership', 'offer', 'text', 'Odznak 3', 50), -- from src/pages/Membership.tsx:360
  ('membership_offer_explore_cta', 'Explore the full 12-month Membership', 'Explore the full 12-month Membership', 'Nabídka — nadpis a odznaky — Text odkazu na 12měsíční členství (Resilient Hubs)', 'membership', 'offer', 'text', 'Text odkazu na 12měsíční členství (Resilient Hubs)', 60), -- from src/pages/Membership.tsx:458
  ('membership_problem_title', 'You thought moving abroad would feel exciting…', 'You thought moving abroad would feel exciting…', 'Problém — Nadpis', 'membership', 'problem', 'text', 'Nadpis', 10), -- from src/pages/Membership.tsx:177
  ('membership_problem_lead', '…but instead, something feels off.', '…but instead, something feels off.', 'Problém — Úvodní věta', 'membership', 'problem', 'text', 'Úvodní věta', 20), -- from src/pages/Membership.tsx:180
  ('membership_problem_body', 'You feel disconnected, overwhelmed, or not quite like yourself. Your emotions are all over the place. And no matter where you are… it doesn''t fully feel like home.', 'You feel disconnected, overwhelmed, or not quite like yourself. Your emotions are all over the place. And no matter where you are… it doesn''t fully feel like home.', 'Problém — Hlavní text', 'membership', 'problem', 'textarea', 'Hlavní text', 30), -- from src/pages/Membership.tsx:183
  ('membership2_solution_badge', 'The gentle path home', 'The gentle path home', 'Řešení — Odznak nad nadpisem (jen na /membership2)', 'membership', 'solution', 'text', 'Odznak nad nadpisem (jen na /membership2)', 10), -- from src/pages/Membership2.tsx:196
  ('membership_solution_title_prefix', 'A ', 'A ', 'Řešení — Nadpis — text před zvýrazněním', 'membership', 'solution', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/Membership.tsx:208
  ('membership_solution_title_highlight', 'gentle, step-by-step space', 'gentle, step-by-step space', 'Řešení — Nadpis — zvýrazněná část (zlatě)', 'membership', 'solution', 'text', 'Nadpis — zvýrazněná část (zlatě)', 30), -- from src/pages/Membership.tsx:208
  ('membership_solution_title_suffix', ' to help you reconnect with yourself again', ' to help you reconnect with yourself again', 'Řešení — Nadpis — text po zvýraznění', 'membership', 'solution', 'text', 'Nadpis — text po zvýraznění', 40), -- from src/pages/Membership.tsx:208
  ('membership_solution_body', 'A place where you can slow down, understand what''s happening inside you, and start feeling grounded and stable again.', 'A place where you can slow down, understand what''s happening inside you, and start feeling grounded and stable again.', 'Řešení — Text pod nadpisem', 'membership', 'solution', 'textarea', 'Text pod nadpisem', 50), -- from src/pages/Membership.tsx:211
  ('membership_teaser_basic_title', 'Basic', 'Basic', 'Cenová karta — Basic — Nadpis karty', 'membership', 'teaser_basic', 'text', 'Nadpis karty', 10), -- from src/pages/Membership.tsx:378
  ('membership_teaser_basic_subtitle', 'Self-paced guidance you can follow in your own time.', 'Self-paced guidance you can follow in your own time.', 'Cenová karta — Basic — Podnadpis karty', 'membership', 'teaser_basic', 'text', 'Podnadpis karty', 20), -- from src/pages/Membership.tsx:380
  ('membership_teaser_basic_period', '/month', '/month', 'Cenová karta — Basic — Perioda za cenou (např. „/měsíc“)', 'membership', 'teaser_basic', 'text', 'Perioda za cenou (např. „/měsíc“)', 30), -- from src/pages/Membership.tsx:384
  ('membership_teaser_basic_feature_1', '4 weekly videos', '4 weekly videos', 'Cenová karta — Basic — Funkce 1', 'membership', 'teaser_basic', 'text', 'Funkce 1', 40), -- from src/pages/Membership.tsx:389
  ('membership_teaser_basic_feature_2', '4 weekly workbooks & reflective exercises', '4 weekly workbooks & reflective exercises', 'Cenová karta — Basic — Funkce 2', 'membership', 'teaser_basic', 'text', 'Funkce 2', 50), -- from src/pages/Membership.tsx:393
  ('membership_teaser_basic_feature_3', 'Guided meditations', 'Guided meditations', 'Cenová karta — Basic — Funkce 3', 'membership', 'teaser_basic', 'text', 'Funkce 3', 60), -- from src/pages/Membership.tsx:397
  ('membership_teaser_basic_feature_4', 'Unlocks one month at a time', 'Unlocks one month at a time', 'Cenová karta — Basic — Funkce 4', 'membership', 'teaser_basic', 'text', 'Funkce 4', 70), -- from src/pages/Membership.tsx:401
  ('membership_teaser_basic_cta', 'Start Basic Monthly', 'Start Basic Monthly', 'Cenová karta — Basic — Text tlačítka', 'membership', 'teaser_basic', 'text', 'Text tlačítka', 80), -- from src/pages/Membership.tsx:408
  ('membership_teaser_premium_badge', 'Most Popular', 'Most Popular', 'Cenová karta — Premium — Odznak „Nejoblíbenější“', 'membership', 'teaser_premium', 'text', 'Odznak „Nejoblíbenější“', 10), -- from src/pages/Membership.tsx:415
  ('membership_teaser_premium_title', 'Premium', 'Premium', 'Cenová karta — Premium — Nadpis karty', 'membership', 'teaser_premium', 'text', 'Nadpis karty', 20), -- from src/pages/Membership.tsx:417
  ('membership_teaser_premium_subtitle', 'Everything in Basic, plus a private community of like-minded women on the same path.', 'Everything in Basic, plus a private community of like-minded women on the same path.', 'Cenová karta — Premium — Podnadpis karty', 'membership', 'teaser_premium', 'textarea', 'Podnadpis karty', 30), -- from src/pages/Membership.tsx:419
  ('membership_teaser_premium_period', '/month', '/month', 'Cenová karta — Premium — Perioda za cenou', 'membership', 'teaser_premium', 'text', 'Perioda za cenou', 40), -- from src/pages/Membership.tsx:423
  ('membership_teaser_premium_feature_1', 'Everything in Basic', 'Everything in Basic', 'Cenová karta — Premium — Funkce 1', 'membership', 'teaser_premium', 'text', 'Funkce 1', 50), -- from src/pages/Membership.tsx:428
  ('membership_teaser_premium_feature_2', 'Access to the private Skool community', 'Access to the private Skool community', 'Cenová karta — Premium — Funkce 2', 'membership', 'teaser_premium', 'text', 'Funkce 2', 60), -- from src/pages/Membership.tsx:432
  ('membership_teaser_premium_feature_3', 'Additional Hub: The Transformed Self', 'Additional Hub: The Transformed Self', 'Cenová karta — Premium — Funkce 3', 'membership', 'teaser_premium', 'text', 'Funkce 3', 70), -- from src/pages/Membership.tsx:436
  ('membership_teaser_premium_feature_4', 'Additional Hub: Navigating Expat Life with Chronic Pain', 'Additional Hub: Navigating Expat Life with Chronic Pain', 'Cenová karta — Premium — Funkce 4', 'membership', 'teaser_premium', 'text', 'Funkce 4', 80), -- from src/pages/Membership.tsx:440
  ('membership_teaser_premium_cta', 'Go Premium Monthly', 'Go Premium Monthly', 'Cenová karta — Premium — Text tlačítka', 'membership', 'teaser_premium', 'text', 'Text tlačítka', 90), -- from src/pages/Membership.tsx:447
  ('membership_transformation_image_alt', 'From feeling lost to feeling like yourself again — a visualization of the inner transformation', 'From feeling lost to feeling like yourself again — a visualization of the inner transformation', 'Proměna — obrázek a popisek — Alt text obrázku', 'membership', 'transformation', 'image_url', 'Alt text obrázku', 10), -- from src/pages/Membership.tsx:314
  ('membership_transformation_caption', 'Instead of feeling overwhelmed and disconnected, you begin to feel calm, grounded, and like yourself again.', 'Instead of feeling overwhelmed and disconnected, you begin to feel calm, grounded, and like yourself again.', 'Proměna — obrázek a popisek — Popisek pod obrázkem', 'membership', 'transformation', 'textarea', 'Popisek pod obrázkem', 20), -- from src/pages/Membership.tsx:321
  ('membership2_transformation_title_prefix', 'From feeling lost to feeling like ', 'From feeling lost to feeling like ', 'Proměna — Před / Po (jen /membership2) — Nadpis — text před zvýrazněním', 'membership', 'transformation2', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/Membership2.tsx:305
  ('membership2_transformation_title_em', 'yourself', 'yourself', 'Proměna — Před / Po (jen /membership2) — Nadpis — zvýrazněné slovo (kurzívou)', 'membership', 'transformation2', 'text', 'Nadpis — zvýrazněné slovo (kurzívou)', 20), -- from src/pages/Membership2.tsx:305
  ('membership2_transformation_title_suffix', ' again', ' again', 'Proměna — Před / Po (jen /membership2) — Nadpis — text po zvýraznění', 'membership', 'transformation2', 'text', 'Nadpis — text po zvýraznění', 30), -- from src/pages/Membership2.tsx:305
  ('membership2_transformation_subtitle', 'Resilient Mind is a gentle space to help expat women feel stable, grounded, and at home within themselves.', 'Resilient Mind is a gentle space to help expat women feel stable, grounded, and at home within themselves.', 'Proměna — Před / Po (jen /membership2) — Podnadpis', 'membership', 'transformation2', 'textarea', 'Podnadpis', 40), -- from src/pages/Membership2.tsx:308
  ('membership2_transformation_before_label', 'Before', 'Before', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — štítek', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — štítek', 50), -- from src/pages/Membership2.tsx:317
  ('membership2_transformation_before_title', 'Feeling overwhelmed & disconnected', 'Feeling overwhelmed & disconnected', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — nadpis', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — nadpis', 60), -- from src/pages/Membership2.tsx:321
  ('membership2_transformation_before_1', 'Lonely, even in a crowd', 'Lonely, even in a crowd', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — bod 1', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — bod 1', 70), -- from src/pages/Membership2.tsx:325
  ('membership2_transformation_before_2', 'Not fully belonging anywhere', 'Not fully belonging anywhere', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — bod 2', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — bod 2', 80), -- from src/pages/Membership2.tsx:326
  ('membership2_transformation_before_3', 'Overthinking & emotionally drained', 'Overthinking & emotionally drained', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — bod 3', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — bod 3', 90), -- from src/pages/Membership2.tsx:327
  ('membership2_transformation_before_4', 'Lost parts of yourself', 'Lost parts of yourself', 'Proměna — Před / Po (jen /membership2) — Sloupec „Před“ — bod 4', 'membership', 'transformation2', 'text', 'Sloupec „Před“ — bod 4', 100), -- from src/pages/Membership2.tsx:328
  ('membership2_transformation_after_label', 'After', 'After', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — štítek', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — štítek', 110), -- from src/pages/Membership2.tsx:343
  ('membership2_transformation_after_title', 'Feeling calm, grounded & connected', 'Feeling calm, grounded & connected', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — nadpis', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — nadpis', 120), -- from src/pages/Membership2.tsx:347
  ('membership2_transformation_after_1', 'Feel at home within yourself', 'Feel at home within yourself', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — bod 1', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — bod 1', 130), -- from src/pages/Membership2.tsx:351
  ('membership2_transformation_after_2', 'Emotional stability & inner safety', 'Emotional stability & inner safety', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — bod 2', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — bod 2', 140), -- from src/pages/Membership2.tsx:352
  ('membership2_transformation_after_3', 'Understand yourself & your patterns', 'Understand yourself & your patterns', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — bod 3', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — bod 3', 150), -- from src/pages/Membership2.tsx:353
  ('membership2_transformation_after_4', 'Stronger relationships & real connection', 'Stronger relationships & real connection', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — bod 4', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — bod 4', 160), -- from src/pages/Membership2.tsx:354
  ('membership2_transformation_after_5', 'Living with purpose & self-trust', 'Living with purpose & self-trust', 'Proměna — Před / Po (jen /membership2) — Sloupec „Po“ — bod 5', 'membership', 'transformation2', 'text', 'Sloupec „Po“ — bod 5', 170) -- from src/pages/Membership2.tsx:355
ON CONFLICT (key) DO NOTHING;
