-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- WorkshopInquiryForm.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('workshopform_form_title', 'Send Your Inquiry', 'Send Your Inquiry', 'Formulář poptávky — Nadpis formuláře', 'workshop-inquiry-form', 'formular', 'text', 'Nadpis formuláře', 240), -- from src/components/WorkshopInquiryForm.tsx:173
  ('workshopform_form_subtitle', 'Tell me about your vision and I''ll get back to you personally.', 'Tell me about your vision and I''ll get back to you personally.', 'Formulář poptávky — Podnadpis formuláře', 'workshop-inquiry-form', 'formular', 'text', 'Podnadpis formuláře', 250), -- from src/components/WorkshopInquiryForm.tsx:176
  ('workshopform_form_name_placeholder', 'Your name', 'Your name', 'Formulář poptávky — Placeholder pole Jméno', 'workshop-inquiry-form', 'formular', 'text', 'Placeholder pole Jméno', 260), -- from src/components/WorkshopInquiryForm.tsx:189
  ('workshopform_form_email_placeholder', 'Your email', 'Your email', 'Formulář poptávky — Placeholder pole E-mail', 'workshop-inquiry-form', 'formular', 'text', 'Placeholder pole E-mail', 270), -- from src/components/WorkshopInquiryForm.tsx:204
  ('workshopform_form_company_placeholder', 'Company (optional)', 'Company (optional)', 'Formulář poptávky — Placeholder pole Firma (nepovinné)', 'workshop-inquiry-form', 'formular', 'text', 'Placeholder pole Firma (nepovinné)', 280), -- from src/components/WorkshopInquiryForm.tsx:220
  ('workshopform_form_groupsize_placeholder', 'Group size', 'Group size', 'Formulář poptávky — Placeholder výběru velikosti skupiny', 'workshop-inquiry-form', 'formular', 'text', 'Placeholder výběru velikosti skupiny', 290), -- from src/components/WorkshopInquiryForm.tsx:235
  ('workshopform_form_groupsize_1_5', '1–5 people', '1–5 people', 'Formulář poptávky — Možnost velikosti skupiny – 1–5 lidí', 'workshop-inquiry-form', 'formular', 'text', 'Možnost velikosti skupiny – 1–5 lidí', 300), -- from src/components/WorkshopInquiryForm.tsx:236
  ('workshopform_form_groupsize_5_10', '5–10 people', '5–10 people', 'Formulář poptávky — Možnost velikosti skupiny – 5–10 lidí', 'workshop-inquiry-form', 'formular', 'text', 'Možnost velikosti skupiny – 5–10 lidí', 310), -- from src/components/WorkshopInquiryForm.tsx:237
  ('workshopform_form_groupsize_10_20', '10–20 people', '10–20 people', 'Formulář poptávky — Možnost velikosti skupiny – 10–20 lidí', 'workshop-inquiry-form', 'formular', 'text', 'Možnost velikosti skupiny – 10–20 lidí', 320), -- from src/components/WorkshopInquiryForm.tsx:238
  ('workshopform_form_groupsize_20plus', '20+ people', '20+ people', 'Formulář poptávky — Možnost velikosti skupiny – 20+ lidí', 'workshop-inquiry-form', 'formular', 'text', 'Možnost velikosti skupiny – 20+ lidí', 330), -- from src/components/WorkshopInquiryForm.tsx:239
  ('workshopform_form_message_placeholder', 'Tell me about what you''re looking for — preferred dates, group details, goals...', 'Tell me about what you''re looking for — preferred dates, group details, goals...', 'Formulář poptávky — Placeholder pole zprávy', 'workshop-inquiry-form', 'formular', 'textarea', 'Placeholder pole zprávy', 340), -- from src/components/WorkshopInquiryForm.tsx:247
  ('workshopform_form_submit_label', 'Send Inquiry', 'Send Inquiry', 'Formulář poptávky — Text tlačítka Odeslat poptávku', 'workshop-inquiry-form', 'formular', 'text', 'Text tlačítka Odeslat poptávku', 350), -- from src/components/WorkshopInquiryForm.tsx:258
  ('workshopform_form_submit_loading', 'Sending...', 'Sending...', 'Formulář poptávky — Text tlačítka během odesílání', 'workshop-inquiry-form', 'formular', 'text', 'Text tlačítka během odesílání', 360), -- from src/components/WorkshopInquiryForm.tsx:258
  ('workshopform_form_footer_note', 'I''ll respond within 24–48 hours. No spam, ever.', 'I''ll respond within 24–48 hours. No spam, ever.', 'Formulář poptávky — Poznámka pod tlačítkem (doba odezvy)', 'workshop-inquiry-form', 'formular', 'text', 'Poznámka pod tlačítkem (doba odezvy)', 370), -- from src/components/WorkshopInquiryForm.tsx:262
  ('workshopform_success_title', 'Thank You for Reaching Out!', 'Thank You for Reaching Out!', 'Poděkování po odeslání poptávky — Nadpis', 'workshop-inquiry-form', 'potvrzeni', 'text', 'Nadpis', 10), -- from src/components/WorkshopInquiryForm.tsx:69
  ('workshopform_success_text', 'Your message is on its way. I''ll personally review your inquiry and get back to you soon with all the details you need.', 'Your message is on its way. I''ll personally review your inquiry and get back to you soon with all the details you need.', 'Poděkování po odeslání poptávky — Text poděkování', 'workshop-inquiry-form', 'potvrzeni', 'textarea', 'Text poděkování', 20), -- from src/components/WorkshopInquiryForm.tsx:72
  ('workshopform_success_button', 'Send another inquiry', 'Send another inquiry', 'Poděkování po odeslání poptávky — Text tlačítka – odeslat další poptávku', 'workshop-inquiry-form', 'potvrzeni', 'text', 'Text tlačítka – odeslat další poptávku', 30), -- from src/components/WorkshopInquiryForm.tsx:78
  ('workshopform_badge_specific', 'Workshop Inquiry', 'Workshop Inquiry', 'Úvodní text a nabídka — Odznak – na stránce konkrétního workshopu', 'workshop-inquiry-form', 'uvod', 'text', 'Odznak – na stránce konkrétního workshopu', 40), -- from src/components/WorkshopInquiryForm.tsx:97
  ('workshopform_badge_general', 'Our Workshops', 'Our Workshops', 'Úvodní text a nabídka — Odznak – na obecné stránce workshopů', 'workshop-inquiry-form', 'uvod', 'text', 'Odznak – na obecné stránce workshopů', 50), -- from src/components/WorkshopInquiryForm.tsx:97
  ('workshopform_title_specific_pre', 'Interested in', 'Interested in', 'Úvodní text a nabídka — Nadpis (konkrétní workshop) – první část', 'workshop-inquiry-form', 'uvod', 'text', 'Nadpis (konkrétní workshop) – první část', 60), -- from src/components/WorkshopInquiryForm.tsx:103
  ('workshopform_title_specific_highlight', 'This Workshop', 'This Workshop', 'Úvodní text a nabídka — Nadpis (konkrétní workshop) – zvýrazněná část', 'workshop-inquiry-form', 'uvod', 'text', 'Nadpis (konkrétní workshop) – zvýrazněná část', 70), -- from src/components/WorkshopInquiryForm.tsx:103
  ('workshopform_title_specific_suffix', '?', '?', 'Úvodní text a nabídka — Nadpis (konkrétní workshop) – text za zvýrazněnou částí (otazník)', 'workshop-inquiry-form', 'uvod', 'text', 'Nadpis (konkrétní workshop) – text za zvýrazněnou částí (otazník)', 80), -- from src/components/WorkshopInquiryForm.tsx:103
  ('workshopform_title_general_pre', 'Workshops for', 'Workshops for', 'Úvodní text a nabídka — Nadpis (obecná stránka) – první část', 'workshop-inquiry-form', 'uvod', 'text', 'Nadpis (obecná stránka) – první část', 90), -- from src/components/WorkshopInquiryForm.tsx:104
  ('workshopform_title_general_highlight', 'Creativity, Connection & Emotional Wellbeing', 'Creativity, Connection & Emotional Wellbeing', 'Úvodní text a nabídka — Nadpis (obecná stránka) – zvýrazněná část', 'workshop-inquiry-form', 'uvod', 'text', 'Nadpis (obecná stránka) – zvýrazněná část', 100), -- from src/components/WorkshopInquiryForm.tsx:104
  ('workshopform_desc_specific_pre', 'I''d love to hear from you about', 'I''d love to hear from you about', 'Úvodní text a nabídka — Popisek (konkrétní workshop) – text před názvem workshopu', 'workshop-inquiry-form', 'uvod', 'text', 'Popisek (konkrétní workshop) – text před názvem workshopu', 110), -- from src/components/WorkshopInquiryForm.tsx:110
  ('workshopform_desc_specific_post', 'Whether you''re looking for a private session, a group experience, or a corporate event — let''s find the perfect fit.', 'Whether you''re looking for a private session, a group experience, or a corporate event — let''s find the perfect fit.', 'Úvodní text a nabídka — Popisek (konkrétní workshop) – text za názvem workshopu', 'workshop-inquiry-form', 'uvod', 'textarea', 'Popisek (konkrétní workshop) – text za názvem workshopu', 120), -- from src/components/WorkshopInquiryForm.tsx:110
  ('workshopform_desc_general', 'I offer gentle, creative workshops designed for adults, children, teens, and families. Each experience combines creativity, emotional expression, mindfulness, and meaningful human connection in a safe and supportive space.', 'I offer gentle, creative workshops designed for adults, children, teens, and families. Each experience combines creativity, emotional expression, mindfulness, and meaningful human connection in a safe and supportive space.', 'Úvodní text a nabídka — Popisek (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'textarea', 'Popisek (obecná stránka)', 130), -- from src/components/WorkshopInquiryForm.tsx:111
  ('workshopform_specific_feature_1', 'Tailored to your group''s specific needs', 'Tailored to your group''s specific needs', 'Úvodní text a nabídka — Bod výhody 1 (konkrétní workshop)', 'workshop-inquiry-form', 'uvod', 'text', 'Bod výhody 1 (konkrétní workshop)', 140), -- from src/components/WorkshopInquiryForm.tsx:118
  ('workshopform_specific_feature_2', 'Available in-person or online', 'Available in-person or online', 'Úvodní text a nabídka — Bod výhody 2 (konkrétní workshop)', 'workshop-inquiry-form', 'uvod', 'text', 'Bod výhody 2 (konkrétní workshop)', 150), -- from src/components/WorkshopInquiryForm.tsx:119
  ('workshopform_specific_feature_3', 'For teams, communities, and organizations', 'For teams, communities, and organizations', 'Úvodní text a nabídka — Bod výhody 3 (konkrétní workshop)', 'workshop-inquiry-form', 'uvod', 'text', 'Bod výhody 3 (konkrétní workshop)', 160), -- from src/components/WorkshopInquiryForm.tsx:120
  ('workshopform_specific_feature_4', 'Combining art expressive therapy & creative practices', 'Combining art expressive therapy & creative practices', 'Úvodní text a nabídka — Bod výhody 4 (konkrétní workshop)', 'workshop-inquiry-form', 'uvod', 'text', 'Bod výhody 4 (konkrétní workshop)', 170), -- from src/components/WorkshopInquiryForm.tsx:121
  ('workshopform_group_adults_title', 'For Adults', 'For Adults', 'Úvodní text a nabídka — Skupina Dospělí – název (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'text', 'Skupina Dospělí – název (obecná stránka)', 180), -- from src/components/WorkshopInquiryForm.tsx:133
  ('workshopform_group_adults_description', 'Mindful silk painting workshops with optional EFT (Emotional Freedom Techniques) sessions to support relaxation, emotional wellbeing, creativity, and self-expression.', 'Mindful silk painting workshops with optional EFT (Emotional Freedom Techniques) sessions to support relaxation, emotional wellbeing, creativity, and self-expression.', 'Úvodní text a nabídka — Skupina Dospělí – popis (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'textarea', 'Skupina Dospělí – popis (obecná stránka)', 190), -- from src/components/WorkshopInquiryForm.tsx:134
  ('workshopform_group_kids_title', 'For Children & Teens', 'For Children & Teens', 'Úvodní text a nabídka — Skupina Děti a teenageři – název (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'text', 'Skupina Děti a teenageři – název (obecná stránka)', 200), -- from src/components/WorkshopInquiryForm.tsx:140
  ('workshopform_group_kids_description', 'Creative workshops that encourage emotional expression, confidence, imagination, and calm through art, mindfulness, silk painting, and gentle emotional support practices.', 'Creative workshops that encourage emotional expression, confidence, imagination, and calm through art, mindfulness, silk painting, and gentle emotional support practices.', 'Úvodní text a nabídka — Skupina Děti a teenageři – popis (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'textarea', 'Skupina Děti a teenageři – popis (obecná stránka)', 210), -- from src/components/WorkshopInquiryForm.tsx:141
  ('workshopform_group_parents_title', 'For Parents & Children', 'For Parents & Children', 'Úvodní text a nabídka — Skupina Rodiče a děti – název (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'text', 'Skupina Rodiče a děti – název (obecná stránka)', 220), -- from src/components/WorkshopInquiryForm.tsx:147
  ('workshopform_group_parents_description', 'Connection-based workshops designed to create quality time, emotional bonding, communication, and shared creative experiences through expressive art activities.', 'Connection-based workshops designed to create quality time, emotional bonding, communication, and shared creative experiences through expressive art activities.', 'Úvodní text a nabídka — Skupina Rodiče a děti – popis (obecná stránka)', 'workshop-inquiry-form', 'uvod', 'textarea', 'Skupina Rodiče a děti – popis (obecná stránka)', 230) -- from src/components/WorkshopInquiryForm.tsx:148
ON CONFLICT (key) DO NOTHING;
