-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- EndometriosisHub.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('endo_cta_title', 'Ready to Begin?', 'Ready to Begin?', 'Výzva k akci — Nadpis', 'endometriosis', 'cta', 'text', 'Nadpis', 10), -- from src/pages/EndometriosisHub.tsx:168
  ('endo_cta_body', 'Access all three modules plus personal consultation for a one-time fee of €147.', 'Access all three modules plus personal consultation for a one-time fee of €147.', 'Výzva k akci — Odstavec (cena €147 je součástí textu, nepřepisovat číslo)', 'endometriosis', 'cta', 'textarea', 'Odstavec (cena €147 je součástí textu, nepřepisovat číslo)', 20), -- from src/pages/EndometriosisHub.tsx:171
  ('endo_cta_purchase', 'Purchase Access', 'Purchase Access', 'Výzva k akci — Text tlačítka — Purchase Access', 'endometriosis', 'cta', 'text', 'Text tlačítka — Purchase Access', 30), -- from src/pages/EndometriosisHub.tsx:178
  ('endo_cta_consult', 'Book Consultation First', 'Book Consultation First', 'Výzva k akci — Text tlačítka — Book Consultation First', 'endometriosis', 'cta', 'text', 'Text tlačítka — Book Consultation First', 40), -- from src/pages/EndometriosisHub.tsx:185
  ('endo_cta_contact_prefix', 'Questions? Contact me at', 'Questions? Contact me at', 'Výzva k akci — Text před e-mailovým odkazem ("Questions? Contact me at")', 'endometriosis', 'cta', 'text', 'Text před e-mailovým odkazem ("Questions? Contact me at")', 50), -- from src/pages/EndometriosisHub.tsx:189
  ('endo_focus_title', 'What''s Included', 'What''s Included', 'Co je zahrnuto — měsíce programu — Nadpis sekce', 'endometriosis', 'focus', 'text', 'Nadpis sekce', 10), -- from src/pages/EndometriosisHub.tsx:58
  ('endo_focus_subtitle', '1-hour individual session, 1-hour Reiki treatment, and Art Therapy tool kit for chronic pain', '1-hour individual session, 1-hour Reiki treatment, and Art Therapy tool kit for chronic pain', 'Co je zahrnuto — měsíce programu — Podnadpis', 'endometriosis', 'focus', 'textarea', 'Podnadpis', 20), -- from src/pages/EndometriosisHub.tsx:61
  ('endo_focus_month1_label', '1st Month', '1st Month', 'Co je zahrnuto — měsíce programu — Měsíc 1 — štítek ("1st Month")', 'endometriosis', 'focus', 'text', 'Měsíc 1 — štítek ("1st Month")', 30), -- from src/pages/EndometriosisHub.tsx:66
  ('endo_focus_month1_title', 'The Invisible Load', 'The Invisible Load', 'Co je zahrnuto — měsíce programu — Měsíc 1 — nadpis karty', 'endometriosis', 'focus', 'text', 'Měsíc 1 — nadpis karty', 40), -- from src/pages/EndometriosisHub.tsx:67
  ('endo_focus_month1_desc', 'When pain is unseen but ever-present.', 'When pain is unseen but ever-present.', 'Co je zahrnuto — měsíce programu — Měsíc 1 — popis karty', 'endometriosis', 'focus', 'text', 'Měsíc 1 — popis karty', 50), -- from src/pages/EndometriosisHub.tsx:68
  ('endo_focus_month1_item_1', 'Identity erosion through chronic pain', 'Identity erosion through chronic pain', 'Co je zahrnuto — měsíce programu — Měsíc 1 — položka seznamu 1', 'endometriosis', 'focus', 'text', 'Měsíc 1 — položka seznamu 1', 60), -- from src/pages/EndometriosisHub.tsx:72
  ('endo_focus_month1_item_2', 'Shame, minimization, and self-doubt', 'Shame, minimization, and self-doubt', 'Co je zahrnuto — měsíce programu — Měsíc 1 — položka seznamu 2', 'endometriosis', 'focus', 'text', 'Měsíc 1 — položka seznamu 2', 70), -- from src/pages/EndometriosisHub.tsx:76
  ('endo_focus_month1_item_3', 'Grief for the body you used to have', 'Grief for the body you used to have', 'Co je zahrnuto — měsíce programu — Měsíc 1 — položka seznamu 3', 'endometriosis', 'focus', 'text', 'Měsíc 1 — položka seznamu 3', 80), -- from src/pages/EndometriosisHub.tsx:80
  ('endo_focus_month2_label', '2nd Month', '2nd Month', 'Co je zahrnuto — měsíce programu — Měsíc 2 — štítek ("2nd Month")', 'endometriosis', 'focus', 'text', 'Měsíc 2 — štítek ("2nd Month")', 90), -- from src/pages/EndometriosisHub.tsx:86
  ('endo_focus_month2_title', 'Safety Over Strength', 'Safety Over Strength', 'Co je zahrnuto — měsíce programu — Měsíc 2 — nadpis karty', 'endometriosis', 'focus', 'text', 'Měsíc 2 — nadpis karty', 100), -- from src/pages/EndometriosisHub.tsx:87
  ('endo_focus_month2_desc', 'Redefining resilience.', 'Redefining resilience.', 'Co je zahrnuto — měsíce programu — Měsíc 2 — popis karty', 'endometriosis', 'focus', 'text', 'Měsíc 2 — popis karty', 110), -- from src/pages/EndometriosisHub.tsx:88
  ('endo_focus_month2_item_1', 'Pain, stress, and expatriation', 'Pain, stress, and expatriation', 'Co je zahrnuto — měsíce programu — Měsíc 2 — položka seznamu 1', 'endometriosis', 'focus', 'text', 'Měsíc 2 — položka seznamu 1', 120), -- from src/pages/EndometriosisHub.tsx:92
  ('endo_focus_month2_item_2', 'Nervous system prioritization', 'Nervous system prioritization', 'Co je zahrnuto — měsíce programu — Měsíc 2 — položka seznamu 2', 'endometriosis', 'focus', 'text', 'Měsíc 2 — položka seznamu 2', 130), -- from src/pages/EndometriosisHub.tsx:96
  ('endo_focus_month2_item_3', 'Pacing, boundaries, and self-respect', 'Pacing, boundaries, and self-respect', 'Co je zahrnuto — měsíce programu — Měsíc 2 — položka seznamu 3', 'endometriosis', 'focus', 'text', 'Měsíc 2 — položka seznamu 3', 140), -- from src/pages/EndometriosisHub.tsx:100
  ('endo_focus_month3_label', '3rd Month', '3rd Month', 'Co je zahrnuto — měsíce programu — Měsíc 3 — štítek ("3rd Month")', 'endometriosis', 'focus', 'text', 'Měsíc 3 — štítek ("3rd Month")', 150), -- from src/pages/EndometriosisHub.tsx:106
  ('endo_focus_month3_title', 'Living Fully Without Waiting', 'Living Fully Without Waiting', 'Co je zahrnuto — měsíce programu — Měsíc 3 — nadpis karty', 'endometriosis', 'focus', 'text', 'Měsíc 3 — nadpis karty', 160), -- from src/pages/EndometriosisHub.tsx:107
  ('endo_focus_month3_desc', 'Life now, not later.', 'Life now, not later.', 'Co je zahrnuto — měsíce programu — Měsíc 3 — popis karty', 'endometriosis', 'focus', 'text', 'Měsíc 3 — popis karty', 170), -- from src/pages/EndometriosisHub.tsx:108
  ('endo_focus_month3_item_1', 'Releasing the ''I will live when...'' mindset', 'Releasing the ''I will live when...'' mindset', 'Co je zahrnuto — měsíce programu — Měsíc 3 — položka seznamu 1', 'endometriosis', 'focus', 'text', 'Měsíc 3 — položka seznamu 1', 180), -- from src/pages/EndometriosisHub.tsx:112
  ('endo_focus_month3_item_2', 'Joy without denial', 'Joy without denial', 'Co je zahrnuto — měsíce programu — Měsíc 3 — položka seznamu 2', 'endometriosis', 'focus', 'text', 'Měsíc 3 — položka seznamu 2', 190), -- from src/pages/EndometriosisHub.tsx:116
  ('endo_focus_month3_item_3', 'Identity beyond illness', 'Identity beyond illness', 'Co je zahrnuto — měsíce programu — Měsíc 3 — položka seznamu 3', 'endometriosis', 'focus', 'text', 'Měsíc 3 — položka seznamu 3', 200), -- from src/pages/EndometriosisHub.tsx:120
  ('endo_hero_badge', 'Additional Resilient Hub', 'Additional Resilient Hub', 'Úvodní obrazovka — Odznak nad nadpisem', 'endometriosis', 'hero', 'text', 'Odznak nad nadpisem', 10), -- from src/pages/EndometriosisHub.tsx:29
  ('endo_hero_title_prefix', 'Navigating Expat Life with', 'Navigating Expat Life with', 'Úvodní obrazovka — Nadpis — text před zvýrazněním', 'endometriosis', 'hero', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/EndometriosisHub.tsx:34
  ('endo_hero_title_highlight', 'Endometriosis & Chronic Pain', 'Endometriosis & Chronic Pain', 'Úvodní obrazovka — Nadpis — zvýrazněná část', 'endometriosis', 'hero', 'text', 'Nadpis — zvýrazněná část', 30), -- from src/pages/EndometriosisHub.tsx:35
  ('endo_hero_lead', 'This optional module is designed for women living abroad while managing endometriosis or chronic pain. It is not a medical or therapeutic treatment.', 'This optional module is designed for women living abroad while managing endometriosis or chronic pain. It is not a medical or therapeutic treatment.', 'Úvodní obrazovka — Odstavec 1', 'endometriosis', 'hero', 'textarea', 'Odstavec 1', 40), -- from src/pages/EndometriosisHub.tsx:39
  ('endo_hero_body', 'The focus is on nervous system regulation, emotional resilience, self-trust, and identity integrity while living with pain.', 'The focus is on nervous system regulation, emotional resilience, self-trust, and identity integrity while living with pain.', 'Úvodní obrazovka — Odstavec 2', 'endometriosis', 'hero', 'textarea', 'Odstavec 2', 50), -- from src/pages/EndometriosisHub.tsx:43
  ('endo_hero_price_label', 'One-time fee', 'One-time fee', 'Úvodní obrazovka — Popisek u ceny ("One-time fee"), cena €147 je zafixovaná v kódu', 'endometriosis', 'hero', 'text', 'Popisek u ceny ("One-time fee"), cena €147 je zafixovaná v kódu', 60), -- from src/pages/EndometriosisHub.tsx:48
  ('endo_whatget_title', 'What You Get', 'What You Get', 'Co získáte — Nadpis boxu', 'endometriosis', 'whatget', 'text', 'Nadpis boxu', 10), -- from src/pages/EndometriosisHub.tsx:128
  ('endo_whatget_1_title', '1 hour individual session', '1 hour individual session', 'Co získáte — Položka 1 — nadpis', 'endometriosis', 'whatget', 'text', 'Položka 1 — nadpis', 20), -- from src/pages/EndometriosisHub.tsx:134
  ('endo_whatget_1_desc', 'Personalized online consultation', 'Personalized online consultation', 'Co získáte — Položka 1 — popis', 'endometriosis', 'whatget', 'text', 'Položka 1 — popis', 30), -- from src/pages/EndometriosisHub.tsx:136
  ('endo_whatget_2_title', '1 hour Reiki treatment', '1 hour Reiki treatment', 'Co získáte — Položka 2 — nadpis', 'endometriosis', 'whatget', 'text', 'Položka 2 — nadpis', 40), -- from src/pages/EndometriosisHub.tsx:143
  ('endo_whatget_2_desc', 'Energy healing session', 'Energy healing session', 'Co získáte — Položka 2 — popis', 'endometriosis', 'whatget', 'text', 'Položka 2 — popis', 50), -- from src/pages/EndometriosisHub.tsx:145
  ('endo_whatget_3_title', 'Art Therapy tool kit', 'Art Therapy tool kit', 'Co získáte — Položka 3 — nadpis', 'endometriosis', 'whatget', 'text', 'Položka 3 — nadpis', 60), -- from src/pages/EndometriosisHub.tsx:152
  ('endo_whatget_3_desc', 'For managing chronic pain', 'For managing chronic pain', 'Co získáte — Položka 3 — popis', 'endometriosis', 'whatget', 'text', 'Položka 3 — popis', 70) -- from src/pages/EndometriosisHub.tsx:154
ON CONFLICT (key) DO NOTHING;
