-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- WorkshopRegistration.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('workshopform_reg_form_title', 'Register Now', 'Register Now', 'Registrační formulář — Nadpis formuláře', 'workshop-registration', 'formular', 'text', 'Nadpis formuláře', 140), -- from src/components/WorkshopRegistration.tsx:189
  ('workshopform_reg_form_subtitle', 'Fill in your details and I''ll confirm your spot.', 'Fill in your details and I''ll confirm your spot.', 'Registrační formulář — Podnadpis formuláře', 'workshop-registration', 'formular', 'text', 'Podnadpis formuláře', 150), -- from src/components/WorkshopRegistration.tsx:192
  ('workshopform_reg_form_name_placeholder', 'Your full name', 'Your full name', 'Registrační formulář — Placeholder pole Celé jméno', 'workshop-registration', 'formular', 'text', 'Placeholder pole Celé jméno', 160), -- from src/components/WorkshopRegistration.tsx:205
  ('workshopform_reg_form_email_placeholder', 'Your email', 'Your email', 'Registrační formulář — Placeholder pole E-mail', 'workshop-registration', 'formular', 'text', 'Placeholder pole E-mail', 170), -- from src/components/WorkshopRegistration.tsx:220
  ('workshopform_reg_form_phone_placeholder', 'Phone number (optional)', 'Phone number (optional)', 'Registrační formulář — Placeholder pole Telefon (nepovinné)', 'workshop-registration', 'formular', 'text', 'Placeholder pole Telefon (nepovinné)', 180), -- from src/components/WorkshopRegistration.tsx:235
  ('workshopform_reg_form_note_placeholder', 'Any questions or notes? (optional)', 'Any questions or notes? (optional)', 'Registrační formulář — Placeholder pole Poznámka (nepovinné)', 'workshop-registration', 'formular', 'textarea', 'Placeholder pole Poznámka (nepovinné)', 190), -- from src/components/WorkshopRegistration.tsx:243
  ('workshopform_reg_form_submit_loading', 'Registering...', 'Registering...', 'Registrační formulář — Text tlačítka během odesílání', 'workshop-registration', 'formular', 'text', 'Text tlačítka během odesílání', 200), -- from src/components/WorkshopRegistration.tsx:253
  ('workshopform_reg_form_submit_prefix', 'Register —', 'Register —', 'Registrační formulář — Text tlačítka Registrovat před částkou', 'workshop-registration', 'formular', 'text', 'Text tlačítka Registrovat před částkou', 210), -- from src/components/WorkshopRegistration.tsx:253
  ('workshopform_reg_form_footer_note', 'You''ll receive a confirmation email after registering.', 'You''ll receive a confirmation email after registering.', 'Registrační formulář — Poznámka pod tlačítkem (potvrzovací e-mail)', 'workshop-registration', 'formular', 'text', 'Poznámka pod tlačítkem (potvrzovací e-mail)', 220), -- from src/components/WorkshopRegistration.tsx:257
  ('workshopform_reg_success_title', 'You''re Registered!', 'You''re Registered!', 'Poděkování po registraci — Nadpis', 'workshop-registration', 'potvrzeni', 'text', 'Nadpis', 10), -- from src/components/WorkshopRegistration.tsx:111
  ('workshopform_reg_success_text_pre', 'Thank you for registering for', 'Thank you for registering for', 'Poděkování po registraci — Text poděkování – text před názvem workshopu', 'workshop-registration', 'potvrzeni', 'text', 'Text poděkování – text před názvem workshopu', 20), -- from src/components/WorkshopRegistration.tsx:114
  ('workshopform_reg_success_text_post', '. I''ll send you a confirmation email with all the details shortly.', '. I''ll send you a confirmation email with all the details shortly.', 'Poděkování po registraci — Text poděkování – text za názvem workshopu', 'workshop-registration', 'potvrzeni', 'textarea', 'Text poděkování – text za názvem workshopu', 30), -- from src/components/WorkshopRegistration.tsx:114
  ('workshopform_reg_qr_pay_label', 'Scan to pay', 'Scan to pay', 'Poděkování po registraci — Text před částkou u QR platby', 'workshop-registration', 'potvrzeni', 'text', 'Text před částkou u QR platby', 40), -- from src/components/WorkshopRegistration.tsx:120
  ('workshopform_reg_qr_caption', 'QR payment code for your bank app', 'QR payment code for your bank app', 'Poděkování po registraci — Popisek pod QR kódem', 'workshop-registration', 'potvrzeni', 'text', 'Popisek pod QR kódem', 50), -- from src/components/WorkshopRegistration.tsx:126
  ('workshopform_reg_badge', 'Workshop Registration', 'Workshop Registration', 'Úvodní text a platba — Odznak nad nadpisem', 'workshop-registration', 'uvod', 'text', 'Odznak nad nadpisem', 60), -- from src/components/WorkshopRegistration.tsx:147
  ('workshopform_reg_title_pre', 'Reserve Your', 'Reserve Your', 'Úvodní text a platba — Nadpis – první část', 'workshop-registration', 'uvod', 'text', 'Nadpis – první část', 70), -- from src/components/WorkshopRegistration.tsx:152
  ('workshopform_reg_title_highlight', 'Spot', 'Spot', 'Úvodní text a platba — Nadpis – zvýrazněné slovo', 'workshop-registration', 'uvod', 'text', 'Nadpis – zvýrazněné slovo', 80), -- from src/components/WorkshopRegistration.tsx:152
  ('workshopform_reg_desc_pre', 'Register for', 'Register for', 'Úvodní text a platba — Popisek – text před názvem workshopu', 'workshop-registration', 'uvod', 'text', 'Popisek – text před názvem workshopu', 90), -- from src/components/WorkshopRegistration.tsx:156
  ('workshopform_reg_desc_post', 'and secure your place. After registering, you''ll receive a confirmation with all the details.', 'and secure your place. After registering, you''ll receive a confirmation with all the details.', 'Úvodní text a platba — Popisek – text za názvem workshopu', 'workshop-registration', 'uvod', 'textarea', 'Popisek – text za názvem workshopu', 100), -- from src/components/WorkshopRegistration.tsx:156
  ('workshopform_reg_price_label', 'Workshop Price', 'Workshop Price', 'Úvodní text a platba — Popisek u ceny workshopu', 'workshop-registration', 'uvod', 'text', 'Popisek u ceny workshopu', 110), -- from src/components/WorkshopRegistration.tsx:162
  ('workshopform_reg_qr_title', 'Pay via QR code in your bank app', 'Pay via QR code in your bank app', 'Úvodní text a platba — Nadpis nad QR kódem k platbě', 'workshop-registration', 'uvod', 'text', 'Nadpis nad QR kódem k platbě', 120), -- from src/components/WorkshopRegistration.tsx:174
  ('workshopform_reg_qr_scan_caption', 'Scan with your banking app to pay', 'Scan with your banking app to pay', 'Úvodní text a platba — Popisek pod QR kódem k platbě', 'workshop-registration', 'uvod', 'text', 'Popisek pod QR kódem k platbě', 130) -- from src/components/WorkshopRegistration.tsx:180
ON CONFLICT (key) DO NOTHING;
