-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- ResilientHub.tsx + ProgramOverview.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('hub_additional_badge', 'Premium Membership Bonus', 'Premium Membership Bonus', 'Doplňkové Resilient Huby — Odznak', 'resilient-hub', 'additional', 'text', 'Odznak', 10), -- from src/pages/ResilientHub.tsx:393
  ('hub_additional_title_prefix', 'Additional ', 'Additional ', 'Doplňkové Resilient Huby — Nadpis — text před zvýrazněním', 'resilient-hub', 'additional', 'text', 'Nadpis — text před zvýrazněním', 20), -- from src/pages/ResilientHub.tsx:397
  ('hub_additional_title_highlight', 'Resilient Hubs', 'Resilient Hubs', 'Doplňkové Resilient Huby — Nadpis — zvýrazněná část', 'resilient-hub', 'additional', 'text', 'Nadpis — zvýrazněná část', 30), -- from src/pages/ResilientHub.tsx:397
  ('hub_additional_subtitle', 'Specialized modules that go beyond the core 12-month program. These additional hubs are included in the Premium Membership at no extra cost.', 'Specialized modules that go beyond the core 12-month program. These additional hubs are included in the Premium Membership at no extra cost.', 'Doplňkové Resilient Huby — Podnadpis', 'resilient-hub', 'additional', 'textarea', 'Podnadpis', 40), -- from src/pages/ResilientHub.tsx:400
  ('hub_additional_note', 'Each additional hub contains 2 specialized video lessons and 2 workbooks with reflective exercises.', 'Each additional hub contains 2 specialized video lessons and 2 workbooks with reflective exercises.', 'Doplňkové Resilient Huby — Poznámka pod podnadpisem', 'resilient-hub', 'additional', 'textarea', 'Poznámka pod podnadpisem', 50), -- from src/pages/ResilientHub.tsx:403
  ('hub_additional_1_title', 'The Transformed Self: Carrying Your Strength Across Borders', 'The Transformed Self: Carrying Your Strength Across Borders', 'Doplňkový hub 1 — The Transformed Self — Nadpis karty', 'resilient-hub', 'additional_hub1', 'text', 'Nadpis karty', 10), -- from src/pages/ResilientHub.tsx:417
  ('hub_additional_1_quote', 'My journey makes sense when I stop judging the timeline.', 'My journey makes sense when I stop judging the timeline.', 'Doplňkový hub 1 — The Transformed Self — Citát', 'resilient-hub', 'additional_hub1', 'text', 'Citát', 20), -- from src/pages/ResilientHub.tsx:420
  ('hub_additional_1_description', 'Recognizing the profound inner transformation that occurs through expatriation challenges. Embracing your newfound resilience, courage and boundary-setting abilities as permanent aspects of your identity. Honoring how difficult moments shaped your capacity for gratitude and appreciation of everyday joys. Developing a global mindset that sees possibilities rather than obstacles in new beginnings. Creating a personal manifesto that anchors your hard-won wisdom as you navigate future transitions with confidence.', 'Recognizing the profound inner transformation that occurs through expatriation challenges. Embracing your newfound resilience, courage and boundary-setting abilities as permanent aspects of your identity. Honoring how difficult moments shaped your capacity for gratitude and appreciation of everyday joys. Developing a global mindset that sees possibilities rather than obstacles in new beginnings. Creating a personal manifesto that anchors your hard-won wisdom as you navigate future transitions with confidence.', 'Doplňkový hub 1 — The Transformed Self — Popis', 'resilient-hub', 'additional_hub1', 'textarea', 'Popis', 30), -- from src/pages/ResilientHub.tsx:426
  ('hub_additional_1_outcome_text', 'You carry resilience, clarity, and self-trust into any future transition.', 'You carry resilience, clarity, and self-trust into any future transition.', 'Doplňkový hub 1 — The Transformed Self — Výsledek (text za "Outcome:")', 'resilient-hub', 'additional_hub1', 'text', 'Výsledek (text za "Outcome:")', 40), -- from src/pages/ResilientHub.tsx:443
  ('hub_additional_2_title', 'Navigating Expat Life with Endometriosis & Chronic Pain', 'Navigating Expat Life with Endometriosis & Chronic Pain', 'Doplňkový hub 2 — Endometrióza a chronická bolest — Nadpis karty', 'resilient-hub', 'additional_hub2', 'text', 'Nadpis karty', 10), -- from src/pages/ResilientHub.tsx:458
  ('hub_additional_2_quote', 'This optional module is not a medical or therapeutic treatment.', 'This optional module is not a medical or therapeutic treatment.', 'Doplňkový hub 2 — Endometrióza a chronická bolest — Podnadpis/upozornění', 'resilient-hub', 'additional_hub2', 'text', 'Podnadpis/upozornění', 20), -- from src/pages/ResilientHub.tsx:461
  ('hub_additional_2_description', 'Designed for women living abroad while managing endometriosis or chronic pain. The focus is on nervous system regulation, emotional resilience, self-trust, and identity integrity while living with pain.', 'Designed for women living abroad while managing endometriosis or chronic pain. The focus is on nervous system regulation, emotional resilience, self-trust, and identity integrity while living with pain.', 'Doplňkový hub 2 — Endometrióza a chronická bolest — Popis', 'resilient-hub', 'additional_hub2', 'textarea', 'Popis', 30), -- from src/pages/ResilientHub.tsx:467
  ('hub_additional_2_outcome_text', 'You navigate life abroad with chronic pain from a place of inner stability and self-compassion.', 'You navigate life abroad with chronic pain from a place of inner stability and self-compassion.', 'Doplňkový hub 2 — Endometrióza a chronická bolest — Výsledek (text za "Outcome:")', 'resilient-hub', 'additional_hub2', 'textarea', 'Výsledek (text za "Outcome:")', 40), -- from src/pages/ResilientHub.tsx:484
  ('hub_additional_videos_label', '2 specialized videos', '2 specialized videos', 'Doplňkové huby — sdílené štítky a souhrn — Štítek "2 specialized videos" (obě karty)', 'resilient-hub', 'additional_summary', 'text', 'Štítek "2 specialized videos" (obě karty)', 10), -- from src/pages/ResilientHub.tsx:432
  ('hub_additional_workbooks_label', '2 workbooks', '2 workbooks', 'Doplňkové huby — sdílené štítky a souhrn — Štítek "2 workbooks" (obě karty)', 'resilient-hub', 'additional_summary', 'text', 'Štítek "2 workbooks" (obě karty)', 20), -- from src/pages/ResilientHub.tsx:436
  ('hub_additional_outcome_label', 'Outcome:', 'Outcome:', 'Doplňkové huby — sdílené štítky a souhrn — Štítek "Outcome:" (obě karty)', 'resilient-hub', 'additional_summary', 'text', 'Štítek "Outcome:" (obě karty)', 30), -- from src/pages/ResilientHub.tsx:442
  ('hub_additional_summary_count', '52 video lessons in total', '52 video lessons in total', 'Doplňkové huby — sdílené štítky a souhrn — Souhrnný pásek — tučný počet videí', 'resilient-hub', 'additional_summary', 'text', 'Souhrnný pásek — tučný počet videí', 40), -- from src/pages/ResilientHub.tsx:496
  ('hub_additional_summary_detail', ' — 48 core program + 4 from Additional Hubs', ' — 48 core program + 4 from Additional Hubs', 'Doplňkové huby — sdílené štítky a souhrn — Souhrnný pásek — zbytek textu', 'resilient-hub', 'additional_summary', 'text', 'Souhrnný pásek — zbytek textu', 50), -- from src/pages/ResilientHub.tsx:496
  ('hub_hero_badge', 'Building Resilient Mind', 'Building Resilient Mind', 'Úvodní obrazovka — Odznak nad nadpisem', 'resilient-hub', 'hero', 'text', 'Odznak nad nadpisem', 10), -- from src/pages/ResilientHub.tsx:164
  ('hub_hero_title', 'A guided 12-month membership', 'A guided 12-month membership', 'Úvodní obrazovka — Nadpis — zvýrazněná část', 'resilient-hub', 'hero', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/ResilientHub.tsx:169
  ('hub_hero_title_line2', 'for expat women', 'for expat women', 'Úvodní obrazovka — Nadpis — druhý řádek', 'resilient-hub', 'hero', 'text', 'Nadpis — druhý řádek', 30), -- from src/pages/ResilientHub.tsx:170
  ('hub_hero_subtitle', 'Supporting your emotional wellbeing, helping you regulate your nervous system and build inner stability while living abroad.', 'Supporting your emotional wellbeing, helping you regulate your nervous system and build inner stability while living abroad.', 'Úvodní obrazovka — Podnadpis', 'resilient-hub', 'hero', 'textarea', 'Podnadpis', 40), -- from src/pages/ResilientHub.tsx:174
  ('hub_hero_cta', 'Start Your Journey', 'Start Your Journey', 'Úvodní obrazovka — Text tlačítka', 'resilient-hub', 'hero', 'text', 'Text tlačítka', 50), -- from src/pages/ResilientHub.tsx:181
  ('hub_intro_question', 'What if resilience wasn''t about pushing harder — but about learning how to care for your mind and nervous system, step by step?', 'What if resilience wasn''t about pushing harder — but about learning how to care for your mind and nervous system, step by step?', 'Co je odolnost — úvodní text — Nadpis — otázka', 'resilient-hub', 'intro', 'textarea', 'Nadpis — otázka', 10), -- from src/pages/ResilientHub.tsx:209
  ('hub_intro_text_1_prefix', 'Inside ', 'Inside ', 'Co je odolnost — úvodní text — Odstavec 1 — text před zvýrazněním', 'resilient-hub', 'intro', 'text', 'Odstavec 1 — text před zvýrazněním', 20), -- from src/pages/ResilientHub.tsx:212
  ('hub_intro_text_1_highlight', 'Resilient Hub', 'Resilient Hub', 'Co je odolnost — úvodní text — Odstavec 1 — zvýrazněná část', 'resilient-hub', 'intro', 'text', 'Odstavec 1 — zvýrazněná část', 30), -- from src/pages/ResilientHub.tsx:212
  ('hub_intro_text_1_suffix', ', you learn how to care for your mind and nervous system — step by step.', ', you learn how to care for your mind and nervous system — step by step.', 'Co je odolnost — úvodní text — Odstavec 1 — text po zvýraznění', 'resilient-hub', 'intro', 'text', 'Odstavec 1 — text po zvýraznění', 40), -- from src/pages/ResilientHub.tsx:212
  ('hub_intro_text_2', 'Resilient Hub is built on a simple idea: you don''t need more information — you need practical tools you can actually use when life feels overwhelming.', 'Resilient Hub is built on a simple idea: you don''t need more information — you need practical tools you can actually use when life feels overwhelming.', 'Co je odolnost — úvodní text — Odstavec 2', 'resilient-hub', 'intro', 'textarea', 'Odstavec 2', 50), -- from src/pages/ResilientHub.tsx:215
  ('hub_intro_list_label', 'Instead of trying to "fix yourself," you begin to:', 'Instead of trying to "fix yourself," you begin to:', 'Co je odolnost — úvodní text — Text před seznamem', 'resilient-hub', 'intro', 'text', 'Text před seznamem', 60), -- from src/pages/ResilientHub.tsx:219
  ('hub_intro_item_1', 'Understand your reactions', 'Understand your reactions', 'Co je odolnost — úvodní text — Položka seznamu 1', 'resilient-hub', 'intro', 'text', 'Položka seznamu 1', 70), -- from src/pages/ResilientHub.tsx:223
  ('hub_intro_item_2', 'Regulate stress and emotions', 'Regulate stress and emotions', 'Co je odolnost — úvodní text — Položka seznamu 2', 'resilient-hub', 'intro', 'text', 'Položka seznamu 2', 80), -- from src/pages/ResilientHub.tsx:224
  ('hub_intro_item_3', 'Build self-awareness and confidence', 'Build self-awareness and confidence', 'Co je odolnost — úvodní text — Položka seznamu 3', 'resilient-hub', 'intro', 'text', 'Položka seznamu 3', 90), -- from src/pages/ResilientHub.tsx:225
  ('hub_intro_item_4', 'Respond to challenges with more calm and clarity', 'Respond to challenges with more calm and clarity', 'Co je odolnost — úvodní text — Položka seznamu 4', 'resilient-hub', 'intro', 'text', 'Položka seznamu 4', 100), -- from src/pages/ResilientHub.tsx:226
  ('hub_intro_closing', 'This is where resilience becomes something you practise, not something you force.', 'This is where resilience becomes something you practise, not something you force.', 'Co je odolnost — úvodní text — Závěrečná věta', 'resilient-hub', 'intro', 'textarea', 'Závěrečná věta', 110), -- from src/pages/ResilientHub.tsx:238
  ('hub_intro_video', 'https://www.youtube.com/embed/O2plWw__ciY', 'https://www.youtube.com/embed/O2plWw__ciY', 'Úvodní video — Odkaz na video (embed URL)', 'resilient-hub', 'intro_video', 'video_url', 'Odkaz na video (embed URL)', 10), -- from src/pages/ResilientHub.tsx:192
  ('hub_program_badge', 'Program Content', 'Program Content', 'Program — přepínač video/přehled — Odznak', 'resilient-hub', 'program', 'text', 'Odznak', 10), -- from src/pages/ResilientHub.tsx:312
  ('hub_program_title', '12 Months, 12 Pillars of Resilience', '12 Months, 12 Pillars of Resilience', 'Program — přepínač video/přehled — Nadpis sekce', 'resilient-hub', 'program', 'text', 'Nadpis sekce', 20), -- from src/pages/ResilientHub.tsx:316
  ('hub_program_tab_videos', 'Video Lessons', 'Video Lessons', 'Program — přepínač video/přehled — Záložka — video lekce', 'resilient-hub', 'program', 'text', 'Záložka — video lekce', 30), -- from src/pages/ResilientHub.tsx:323
  ('hub_program_tab_overview', 'Overview', 'Overview', 'Program — přepínač video/přehled — Záložka — přehled', 'resilient-hub', 'program', 'text', 'Záložka — přehled', 40), -- from src/pages/ResilientHub.tsx:327
  ('hub_program_q1_title', 'Adaptation in a Foreign Country', 'Adaptation in a Foreign Country', 'Program — 1. čtvrtletí (měsíce 1–3) — Nadpis programu', 'resilient-hub', 'program_q1', 'text', 'Nadpis programu', 10), -- from src/pages/ResilientHub.tsx:23
  ('hub_program_q1_months', 'Months 1-3', 'Months 1-3', 'Program — 1. čtvrtletí (měsíce 1–3) — Období (měsíce)', 'resilient-hub', 'program_q1', 'text', 'Období (měsíce)', 20), -- from src/pages/ResilientHub.tsx:24
  ('hub_program_q1_focus', 'Nervous system regulation, daily safety rituals, inner home, identity beyond location', 'Nervous system regulation, daily safety rituals, inner home, identity beyond location', 'Program — 1. čtvrtletí (měsíce 1–3) — Zaměření', 'resilient-hub', 'program_q1', 'textarea', 'Zaměření', 30), -- from src/pages/ResilientHub.tsx:25
  ('hub_program_q1_quote', 'Fear doesn''t mean I made a mistake – it means I left the familiar.', 'Fear doesn''t mean I made a mistake – it means I left the familiar.', 'Program — 1. čtvrtletí (měsíce 1–3) — Citát', 'resilient-hub', 'program_q1', 'text', 'Citát', 40), -- from src/pages/ResilientHub.tsx:26
  ('hub_program_q1_module_1_name', '1st Month', '1st Month', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 1 — název měsíce', 'resilient-hub', 'program_q1', 'text', 'Modul 1 — název měsíce', 50), -- from src/pages/ResilientHub.tsx:29
  ('hub_program_q1_module_1_title', 'First Steps: Finding Solid Ground When Everything is New', 'First Steps: Finding Solid Ground When Everything is New', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 1 — nadpis', 'resilient-hub', 'program_q1', 'text', 'Modul 1 — nadpis', 60), -- from src/pages/ResilientHub.tsx:30
  ('hub_program_q1_module_1_description', 'Practical techniques for calming your nervous system while navigating cultural differences, building daily certainty in an unfamiliar environment.', 'Practical techniques for calming your nervous system while navigating cultural differences, building daily certainty in an unfamiliar environment.', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 1 — popis', 'resilient-hub', 'program_q1', 'textarea', 'Modul 1 — popis', 70), -- from src/pages/ResilientHub.tsx:31
  ('hub_program_q1_module_2_name', '2nd Month', '2nd Month', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 2 — název měsíce', 'resilient-hub', 'program_q1', 'text', 'Modul 2 — název měsíce', 80), -- from src/pages/ResilientHub.tsx:34
  ('hub_program_q1_module_2_title', 'Creating Your New Roots: Identity Beyond Borders', 'Creating Your New Roots: Identity Beyond Borders', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 2 — nadpis', 'resilient-hub', 'program_q1', 'text', 'Modul 2 — nadpis', 90), -- from src/pages/ResilientHub.tsx:35
  ('hub_program_q1_module_2_description', 'The profound process of identity transformation during cultural transition. Practical steps for creating an ''inner home'' that remains stable regardless of geographic location.', 'The profound process of identity transformation during cultural transition. Practical steps for creating an ''inner home'' that remains stable regardless of geographic location.', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 2 — popis', 'resilient-hub', 'program_q1', 'textarea', 'Modul 2 — popis', 100), -- from src/pages/ResilientHub.tsx:36
  ('hub_program_q1_module_3_name', '3rd Month', '3rd Month', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 3 — název měsíce', 'resilient-hub', 'program_q1', 'text', 'Modul 3 — název měsíce', 110), -- from src/pages/ResilientHub.tsx:39
  ('hub_program_q1_module_3_title', 'The Integration Path: Becoming Part of Your New World', 'The Integration Path: Becoming Part of Your New World', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 3 — nadpis', 'resilient-hub', 'program_q1', 'text', 'Modul 3 — nadpis', 120), -- from src/pages/ResilientHub.tsx:40
  ('hub_program_q1_module_3_description', 'The art of balancing preservation of your cultural identity while opening to new ways of being across cultural differences.', 'The art of balancing preservation of your cultural identity while opening to new ways of being across cultural differences.', 'Program — 1. čtvrtletí (měsíce 1–3) — Modul 3 — popis', 'resilient-hub', 'program_q1', 'textarea', 'Modul 3 — popis', 130), -- from src/pages/ResilientHub.tsx:41
  ('hub_program_q2_title', 'Navigating Inner Landscapes: From Loneliness to Self-Discovery', 'Navigating Inner Landscapes: From Loneliness to Self-Discovery', 'Program — 2. čtvrtletí (měsíce 4–6) — Nadpis programu', 'resilient-hub', 'program_q2', 'text', 'Nadpis programu', 10), -- from src/pages/ResilientHub.tsx:47
  ('hub_program_q2_months', 'Months 4-6', 'Months 4-6', 'Program — 2. čtvrtletí (měsíce 4–6) — Období (měsíce)', 'resilient-hub', 'program_q2', 'text', 'Období (měsíce)', 20), -- from src/pages/ResilientHub.tsx:48
  ('hub_program_q2_focus', 'Loneliness, emotional phases, identity collapse and reconstruction, purpose, vision', 'Loneliness, emotional phases, identity collapse and reconstruction, purpose, vision', 'Program — 2. čtvrtletí (měsíce 4–6) — Zaměření', 'resilient-hub', 'program_q2', 'textarea', 'Zaměření', 30), -- from src/pages/ResilientHub.tsx:49
  ('hub_program_q2_quote', 'I am not broken – I am in transition.', 'I am not broken – I am in transition.', 'Program — 2. čtvrtletí (měsíce 4–6) — Citát', 'resilient-hub', 'program_q2', 'text', 'Citát', 40), -- from src/pages/ResilientHub.tsx:50
  ('hub_program_q2_module_1_name', '4th Month', '4th Month', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 1 — název měsíce', 'resilient-hub', 'program_q2', 'text', 'Modul 1 — název měsíce', 50), -- from src/pages/ResilientHub.tsx:53
  ('hub_program_q2_module_1_title', 'The Emotional Terrain of Expatriation: You Are Not Alone', 'The Emotional Terrain of Expatriation: You Are Not Alone', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 1 — nadpis', 'resilient-hub', 'program_q2', 'text', 'Modul 1 — nadpis', 60), -- from src/pages/ResilientHub.tsx:54
  ('hub_program_q2_module_1_description', 'Uncovering the hidden emotional phases most expats experience. Practical techniques for transforming isolation into deeper self-knowledge.', 'Uncovering the hidden emotional phases most expats experience. Practical techniques for transforming isolation into deeper self-knowledge.', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 1 — popis', 'resilient-hub', 'program_q2', 'textarea', 'Modul 1 — popis', 70), -- from src/pages/ResilientHub.tsx:55
  ('hub_program_q2_module_2_name', '5th Month', '5th Month', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 2 — název měsíce', 'resilient-hub', 'program_q2', 'text', 'Modul 2 — název měsíce', 80), -- from src/pages/ResilientHub.tsx:58
  ('hub_program_q2_module_2_title', 'Reclaiming Your Authentic Self: Identity Beyond Cultural Labels', 'Reclaiming Your Authentic Self: Identity Beyond Cultural Labels', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 2 — nadpis', 'resilient-hub', 'program_q2', 'text', 'Modul 2 — nadpis', 90), -- from src/pages/ResilientHub.tsx:59
  ('hub_program_q2_module_2_description', 'Discovering new dimensions of your identity that awaken only through living between cultures. Transformational work with the Byron Katie method.', 'Discovering new dimensions of your identity that awaken only through living between cultures. Transformational work with the Byron Katie method.', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 2 — popis', 'resilient-hub', 'program_q2', 'textarea', 'Modul 2 — popis', 100), -- from src/pages/ResilientHub.tsx:60
  ('hub_program_q2_module_3_name', '6th Month', '6th Month', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 3 — název měsíce', 'resilient-hub', 'program_q2', 'text', 'Modul 3 — název měsíce', 110), -- from src/pages/ResilientHub.tsx:63
  ('hub_program_q2_module_3_title', 'Soul Alignment: Finding Meaning in Your Expat Journey', 'Soul Alignment: Finding Meaning in Your Expat Journey', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 3 — nadpis', 'resilient-hub', 'program_q2', 'text', 'Modul 3 — nadpis', 120), -- from src/pages/ResilientHub.tsx:64
  ('hub_program_q2_module_3_description', 'Revealing the hidden meaning and purpose behind your expatriation journey through intuitive practices.', 'Revealing the hidden meaning and purpose behind your expatriation journey through intuitive practices.', 'Program — 2. čtvrtletí (měsíce 4–6) — Modul 3 — popis', 'resilient-hub', 'program_q2', 'textarea', 'Modul 3 — popis', 130), -- from src/pages/ResilientHub.tsx:65
  ('hub_program_q3_title', 'Financial Freedom Abroad: Navigate Financial Uncertainty with Ease', 'Financial Freedom Abroad: Navigate Financial Uncertainty with Ease', 'Program — 3. čtvrtletí (měsíce 7–9) — Nadpis programu', 'resilient-hub', 'program_q3', 'text', 'Nadpis programu', 10), -- from src/pages/ResilientHub.tsx:71
  ('hub_program_q3_months', 'Months 7-9', 'Months 7-9', 'Program — 3. čtvrtletí (měsíce 7–9) — Období (měsíce)', 'resilient-hub', 'program_q3', 'text', 'Období (měsíce)', 20), -- from src/pages/ResilientHub.tsx:72
  ('hub_program_q3_focus', 'Money beliefs, self-trust, financial calm, opportunity awareness, intuitive decisions', 'Money beliefs, self-trust, financial calm, opportunity awareness, intuitive decisions', 'Program — 3. čtvrtletí (měsíce 7–9) — Zaměření', 'resilient-hub', 'program_q3', 'textarea', 'Zaměření', 30), -- from src/pages/ResilientHub.tsx:73
  ('hub_program_q3_quote', 'I don''t rely on certainty—I rely on my own inner guidance.', 'I don''t rely on certainty—I rely on my own inner guidance.', 'Program — 3. čtvrtletí (měsíce 7–9) — Citát', 'resilient-hub', 'program_q3', 'text', 'Citát', 40), -- from src/pages/ResilientHub.tsx:74
  ('hub_program_q3_module_1_name', '7th Month', '7th Month', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 1 — název měsíce', 'resilient-hub', 'program_q3', 'text', 'Modul 1 — název měsíce', 50), -- from src/pages/ResilientHub.tsx:77
  ('hub_program_q3_module_1_title', 'Money Energy Mastery: Uncovering Your Expat Money Story', 'Money Energy Mastery: Uncovering Your Expat Money Story', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 1 — nadpis', 'resilient-hub', 'program_q3', 'text', 'Modul 1 — nadpis', 60), -- from src/pages/ResilientHub.tsx:78
  ('hub_program_q3_module_1_description', 'Practical techniques for identifying inherited money beliefs, understanding how your financial mindset shifts when navigating different cultural money values.', 'Practical techniques for identifying inherited money beliefs, understanding how your financial mindset shifts when navigating different cultural money values.', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 1 — popis', 'resilient-hub', 'program_q3', 'textarea', 'Modul 1 — popis', 70), -- from src/pages/ResilientHub.tsx:79
  ('hub_program_q3_module_2_name', '8th Month', '8th Month', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 2 — název měsíce', 'resilient-hub', 'program_q3', 'text', 'Modul 2 — název měsíce', 80), -- from src/pages/ResilientHub.tsx:82
  ('hub_program_q3_module_2_title', 'Trust & Abundance: Creating Financial Security Anywhere', 'Trust & Abundance: Creating Financial Security Anywhere', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 2 — nadpis', 'resilient-hub', 'program_q3', 'text', 'Modul 2 — nadpis', 90), -- from src/pages/ResilientHub.tsx:83
  ('hub_program_q3_module_2_description', 'Building inner certainty independent of external circumstances, how to develop trust in yourself and your ability to thrive in any environment.', 'Building inner certainty independent of external circumstances, how to develop trust in yourself and your ability to thrive in any environment.', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 2 — popis', 'resilient-hub', 'program_q3', 'textarea', 'Modul 2 — popis', 100), -- from src/pages/ResilientHub.tsx:84
  ('hub_program_q3_module_3_name', '9th Month', '9th Month', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 3 — název měsíce', 'resilient-hub', 'program_q3', 'text', 'Modul 3 — název měsíce', 110), -- from src/pages/ResilientHub.tsx:87
  ('hub_program_q3_module_3_title', 'Prosperity Consciousness: Living in Alignment with Abundance', 'Prosperity Consciousness: Living in Alignment with Abundance', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 3 — nadpis', 'resilient-hub', 'program_q3', 'text', 'Modul 3 — nadpis', 120), -- from src/pages/ResilientHub.tsx:88
  ('hub_program_q3_module_3_description', 'Creating a personal manifestation process for attracting opportunities, techniques for recognizing and utilizing hidden financial opportunities.', 'Creating a personal manifestation process for attracting opportunities, techniques for recognizing and utilizing hidden financial opportunities.', 'Program — 3. čtvrtletí (měsíce 7–9) — Modul 3 — popis', 'resilient-hub', 'program_q3', 'textarea', 'Modul 3 — popis', 130), -- from src/pages/ResilientHub.tsx:89
  ('hub_program_q4_title', 'Life Beyond Family Borders: Redefining Family When Worlds Apart', 'Life Beyond Family Borders: Redefining Family When Worlds Apart', 'Program — 4. čtvrtletí (měsíce 10–12) — Nadpis programu', 'resilient-hub', 'program_q4', 'text', 'Nadpis programu', 10), -- from src/pages/ResilientHub.tsx:95
  ('hub_program_q4_months', 'Months 10-12', 'Months 10-12', 'Program — 4. čtvrtletí (měsíce 10–12) — Období (měsíce)', 'resilient-hub', 'program_q4', 'text', 'Období (měsíce)', 20), -- from src/pages/ResilientHub.tsx:96
  ('hub_program_q4_focus', 'Guilt release, emotional closeness, building authentic community, integration, life vision', 'Guilt release, emotional closeness, building authentic community, integration, life vision', 'Program — 4. čtvrtletí (měsíce 10–12) — Zaměření', 'resilient-hub', 'program_q4', 'textarea', 'Zaměření', 30), -- from src/pages/ResilientHub.tsx:97
  ('hub_program_q4_quote', 'Belonging isn''t found, it''s created—through your courageous presence, the seeds of trust, and the daily tending of meaningful connections.', 'Belonging isn''t found, it''s created—through your courageous presence, the seeds of trust, and the daily tending of meaningful connections.', 'Program — 4. čtvrtletí (měsíce 10–12) — Citát', 'resilient-hub', 'program_q4', 'textarea', 'Citát', 40), -- from src/pages/ResilientHub.tsx:98
  ('hub_program_q4_module_1_name', '10th Month', '10th Month', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 1 — název měsíce', 'resilient-hub', 'program_q4', 'text', 'Modul 1 — název měsíce', 50), -- from src/pages/ResilientHub.tsx:101
  ('hub_program_q4_module_1_title', 'Heart Bridges: Nurturing Love Across Distances', 'Heart Bridges: Nurturing Love Across Distances', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 1 — nadpis', 'resilient-hub', 'program_q4', 'text', 'Modul 1 — nadpis', 60), -- from src/pages/ResilientHub.tsx:102
  ('hub_program_q4_module_1_description', 'Rituals for maintaining deep emotional closeness despite physical distance, creative ways of sharing life beyond texts and calls.', 'Rituals for maintaining deep emotional closeness despite physical distance, creative ways of sharing life beyond texts and calls.', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 1 — popis', 'resilient-hub', 'program_q4', 'textarea', 'Modul 1 — popis', 70), -- from src/pages/ResilientHub.tsx:103
  ('hub_program_q4_module_2_name', '11th Month', '11th Month', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 2 — název měsíce', 'resilient-hub', 'program_q4', 'text', 'Modul 2 — název měsíce', 80), -- from src/pages/ResilientHub.tsx:106
  ('hub_program_q4_module_2_title', 'Soul Family: Creating Your Tribe in a New Land', 'Soul Family: Creating Your Tribe in a New Land', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 2 — nadpis', 'resilient-hub', 'program_q4', 'text', 'Modul 2 — nadpis', 90), -- from src/pages/ResilientHub.tsx:107
  ('hub_program_q4_module_2_description', 'Strategies for finding authentic friendships in a foreign environment, recognizing potential ''kindred spirits,'' courage to be vulnerable.', 'Strategies for finding authentic friendships in a foreign environment, recognizing potential ''kindred spirits,'' courage to be vulnerable.', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 2 — popis', 'resilient-hub', 'program_q4', 'textarea', 'Modul 2 — popis', 100), -- from src/pages/ResilientHub.tsx:108
  ('hub_program_q4_module_3_name', '12th Month', '12th Month', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 3 — název měsíce', 'resilient-hub', 'program_q4', 'text', 'Modul 3 — název měsíce', 110), -- from src/pages/ResilientHub.tsx:111
  ('hub_program_q4_module_3_title', 'The Integrated Self: Embracing Your Multi-Dimensional Life', 'The Integrated Self: Embracing Your Multi-Dimensional Life', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 3 — nadpis', 'resilient-hub', 'program_q4', 'text', 'Modul 3 — nadpis', 120), -- from src/pages/ResilientHub.tsx:112
  ('hub_program_q4_module_3_description', 'The culmination of your transformation journey, where separate skills integrate into your new resilient identity.', 'The culmination of your transformation journey, where separate skills integrate into your new resilient identity.', 'Program — 4. čtvrtletí (měsíce 10–12) — Modul 3 — popis', 'resilient-hub', 'program_q4', 'textarea', 'Modul 3 — popis', 130), -- from src/pages/ResilientHub.tsx:113
  ('hub_receive_title', 'What You Will Receive', 'What You Will Receive', 'Co v programu získáte — Nadpis sekce', 'resilient-hub', 'receive', 'text', 'Nadpis sekce', 10), -- from src/pages/ResilientHub.tsx:279
  ('hub_receive_1_title', '4 Video Lessons', '4 Video Lessons', 'Co v programu získáte — Karta 1 — nadpis', 'resilient-hub', 'receive', 'text', 'Karta 1 — nadpis', 20), -- from src/pages/ResilientHub.tsx:284
  ('hub_receive_1_desc', 'Each month', 'Each month', 'Co v programu získáte — Karta 1 — popis', 'resilient-hub', 'receive', 'text', 'Karta 1 — popis', 30), -- from src/pages/ResilientHub.tsx:284
  ('hub_receive_2_title', 'Worksheets', 'Worksheets', 'Co v programu získáte — Karta 2 — nadpis', 'resilient-hub', 'receive', 'text', 'Karta 2 — nadpis', 40), -- from src/pages/ResilientHub.tsx:285
  ('hub_receive_2_desc', 'Printable PDFs', 'Printable PDFs', 'Co v programu získáte — Karta 2 — popis', 'resilient-hub', 'receive', 'text', 'Karta 2 — popis', 50), -- from src/pages/ResilientHub.tsx:285
  ('hub_receive_3_title', 'Meditation', 'Meditation', 'Co v programu získáte — Karta 3 — nadpis', 'resilient-hub', 'receive', 'text', 'Karta 3 — nadpis', 60), -- from src/pages/ResilientHub.tsx:286
  ('hub_receive_3_desc', 'Guided audio', 'Guided audio', 'Co v programu získáte — Karta 3 — popis', 'resilient-hub', 'receive', 'text', 'Karta 3 — popis', 70), -- from src/pages/ResilientHub.tsx:286
  ('hub_receive_4_title', 'Community', 'Community', 'Co v programu získáte — Karta 4 — nadpis', 'resilient-hub', 'receive', 'text', 'Karta 4 — nadpis', 80), -- from src/pages/ResilientHub.tsx:287
  ('hub_receive_4_desc', 'Private access', 'Private access', 'Co v programu získáte — Karta 4 — popis', 'resilient-hub', 'receive', 'text', 'Karta 4 — popis', 90), -- from src/pages/ResilientHub.tsx:287
  ('hub_videos_loading', 'Loading program content...', 'Loading program content...', 'Video lekce — stavy a CTA — Text při načítání', 'resilient-hub', 'videos_tab', 'text', 'Text při načítání', 10), -- from src/components/ProgramOverview.tsx:116
  ('hub_videos_empty_title', 'Content in Preparation', 'Content in Preparation', 'Video lekce — stavy a CTA — Prázdný stav — nadpis', 'resilient-hub', 'videos_tab', 'text', 'Prázdný stav — nadpis', 20), -- from src/components/ProgramOverview.tsx:125
  ('hub_videos_empty_text', 'We''re preparing video lessons and materials. Subscribe for updates!', 'We''re preparing video lessons and materials. Subscribe for updates!', 'Video lekce — stavy a CTA — Prázdný stav — text', 'resilient-hub', 'videos_tab', 'text', 'Prázdný stav — text', 30), -- from src/components/ProgramOverview.tsx:127
  ('hub_videos_coming_soon', 'Videos coming soon', 'Videos coming soon', 'Video lekce — stavy a CTA — Text u kategorie bez videí', 'resilient-hub', 'videos_tab', 'text', 'Text u kategorie bez videí', 40), -- from src/components/ProgramOverview.tsx:179
  ('hub_videos_more_prefix', 'Show More Months (', 'Show More Months (', 'Video lekce — stavy a CTA — Tlačítko "Zobrazit další měsíce" — text před počtem', 'resilient-hub', 'videos_tab', 'text', 'Tlačítko "Zobrazit další měsíce" — text před počtem', 50), -- from src/components/ProgramOverview.tsx:195
  ('hub_videos_more_suffix', ' remaining)', ' remaining)', 'Video lekce — stavy a CTA — Tlačítko "Zobrazit další měsíce" — text za počtem', 'resilient-hub', 'videos_tab', 'text', 'Tlačítko "Zobrazit další měsíce" — text za počtem', 60), -- from src/components/ProgramOverview.tsx:195
  ('hub_videos_cta_title', 'Get Full Program Access', 'Get Full Program Access', 'Video lekce — stavy a CTA — CTA box (nepřihlášení) — nadpis', 'resilient-hub', 'videos_tab', 'text', 'CTA box (nepřihlášení) — nadpis', 70), -- from src/components/ProgramOverview.tsx:202
  ('hub_videos_cta_text', 'Sign up or log in and unlock all video lessons, workbooks and exclusive content.', 'Sign up or log in and unlock all video lessons, workbooks and exclusive content.', 'Video lekce — stavy a CTA — CTA box (nepřihlášení) — text', 'resilient-hub', 'videos_tab', 'text', 'CTA box (nepřihlášení) — text', 80), -- from src/components/ProgramOverview.tsx:205
  ('hub_videos_cta_start', 'Start Free', 'Start Free', 'Video lekce — stavy a CTA — CTA box — tlačítko "Start Free"', 'resilient-hub', 'videos_tab', 'text', 'CTA box — tlačítko "Start Free"', 90), -- from src/components/ProgramOverview.tsx:209
  ('hub_videos_cta_pricing', 'View Pricing', 'View Pricing', 'Video lekce — stavy a CTA — CTA box — tlačítko "View Pricing"', 'resilient-hub', 'videos_tab', 'text', 'CTA box — tlačítko "View Pricing"', 100), -- from src/components/ProgramOverview.tsx:212
  ('hub_what_title_prefix', 'What is ', 'What is ', 'Co je Resilient Hub — Nadpis — text před zvýrazněním', 'resilient-hub', 'what', 'text', 'Nadpis — text před zvýrazněním', 10), -- from src/pages/ResilientHub.tsx:249
  ('hub_what_title_highlight', 'Resilient Hub?', 'Resilient Hub?', 'Co je Resilient Hub — Nadpis — zvýrazněná část', 'resilient-hub', 'what', 'text', 'Nadpis — zvýrazněná část', 20), -- from src/pages/ResilientHub.tsx:249
  ('hub_what_text_1', 'Resilient Hub is a structured 12-month online membership combining EFT (Emotional Freedom Techniques), nervous system regulation practices and reflective tools to support your emotional wellbeing while living abroad.', 'Resilient Hub is a structured 12-month online membership combining EFT (Emotional Freedom Techniques), nervous system regulation practices and reflective tools to support your emotional wellbeing while living abroad.', 'Co je Resilient Hub — Odstavec 1', 'resilient-hub', 'what', 'textarea', 'Odstavec 1', 30), -- from src/pages/ResilientHub.tsx:252
  ('hub_what_text_2', 'Living abroad can be enriching, but it can also bring loneliness, uncertainty and emotional challenges.', 'Living abroad can be enriching, but it can also bring loneliness, uncertainty and emotional challenges.', 'Co je Resilient Hub — Odstavec 2', 'resilient-hub', 'what', 'textarea', 'Odstavec 2', 40), -- from src/pages/ResilientHub.tsx:255
  ('hub_what_text_3', 'Resilient Hub was created to offer steady support, practical tools and a gentle structure to help you feel more grounded and at home within yourself.', 'Resilient Hub was created to offer steady support, practical tools and a gentle structure to help you feel more grounded and at home within yourself.', 'Co je Resilient Hub — Odstavec 3', 'resilient-hub', 'what', 'textarea', 'Odstavec 3', 50), -- from src/pages/ResilientHub.tsx:258
  ('hub_what_list_label', 'This is for you if:', 'This is for you if:', 'Co je Resilient Hub — Nadpis nad seznamem "Toto je pro tebe, pokud:"', 'resilient-hub', 'what', 'text', 'Nadpis nad seznamem "Toto je pro tebe, pokud:"', 60), -- from src/pages/ResilientHub.tsx:262
  ('hub_what_item_1', 'you live abroad and feel emotionally overwhelmed', 'you live abroad and feel emotionally overwhelmed', 'Co je Resilient Hub — Položka seznamu 1', 'resilient-hub', 'what', 'text', 'Položka seznamu 1', 70), -- from src/pages/ResilientHub.tsx:264
  ('hub_what_item_2', 'you miss stability and inner safety', 'you miss stability and inner safety', 'Co je Resilient Hub — Položka seznamu 2', 'resilient-hub', 'what', 'text', 'Položka seznamu 2', 80), -- from src/pages/ResilientHub.tsx:265
  ('hub_what_item_3', 'you want gentle, practical tools', 'you want gentle, practical tools', 'Co je Resilient Hub — Položka seznamu 3', 'resilient-hub', 'what', 'text', 'Položka seznamu 3', 90), -- from src/pages/ResilientHub.tsx:266
  ('hub_what_item_4', 'you value continuity over quick fixes', 'you value continuity over quick fixes', 'Co je Resilient Hub — Položka seznamu 4', 'resilient-hub', 'what', 'text', 'Položka seznamu 4', 100) -- from src/pages/ResilientHub.tsx:267
ON CONFLICT (key) DO NOTHING;
