-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- BookingSuccess.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('booking_success_calendar_button', 'Add to Google Calendar', 'Add to Google Calendar', 'Tlačítka pod detaily rezervace — Text tlačítka „Přidat do Google Kalendáře"', 'booking-success', 'akce', 'text', 'Text tlačítka „Přidat do Google Kalendáře"', 230), -- from src/pages/BookingSuccess.tsx:232
  ('booking_success_home_button', 'Back to Homepage', 'Back to Homepage', 'Tlačítka pod detaily rezervace — Text tlačítka „Zpět na hlavní stránku"', 'booking-success', 'akce', 'text', 'Text tlačítka „Zpět na hlavní stránku"', 240), -- from src/pages/BookingSuccess.tsx:238
  ('booking_success_error_title', 'Something went wrong', 'Something went wrong', 'Stav: rezervace nenalezena — Nadpis', 'booking-success', 'chyba', 'text', 'Nadpis', 20), -- from src/pages/BookingSuccess.tsx:106
  ('booking_success_error_fallback', 'Reservation not found', 'Reservation not found', 'Stav: rezervace nenalezena — Výchozí chybová hláška', 'booking-success', 'chyba', 'text', 'Výchozí chybová hláška', 30), -- from src/pages/BookingSuccess.tsx:107
  ('booking_success_error_button', 'Back to Booking', 'Back to Booking', 'Stav: rezervace nenalezena — Text tlačítka zpět', 'booking-success', 'chyba', 'text', 'Text tlačítka zpět', 40), -- from src/pages/BookingSuccess.tsx:110
  ('booking_success_next_title', 'What''s next?', 'What''s next?', 'Box „Co bude dál?" — Nadpis', 'booking-success', 'co_dal', 'text', 'Nadpis', 250), -- from src/pages/BookingSuccess.tsx:246
  ('booking_success_next_1_confirmed', 'Confirmation email has been sent to your email address', 'Confirmation email has been sent to your email address', 'Box „Co bude dál?" — Krok 1 – potvrzeno', 'booking-success', 'co_dal', 'text', 'Krok 1 – potvrzeno', 260), -- from src/pages/BookingSuccess.tsx:255
  ('booking_success_next_1_pending', 'Complete payment to confirm your reservation', 'Complete payment to confirm your reservation', 'Box „Co bude dál?" — Krok 1 – čeká na platbu', 'booking-success', 'co_dal', 'text', 'Krok 1 – čeká na platbu', 270), -- from src/pages/BookingSuccess.tsx:256
  ('booking_success_next_2', 'You will receive a reminder 24 hours before your session', 'You will receive a reminder 24 hours before your session', 'Box „Co bude dál?" — Krok 2', 'booking-success', 'co_dal', 'text', 'Krok 2', 280), -- from src/pages/BookingSuccess.tsx:264
  ('booking_success_next_3', 'You will receive the online session link by email one day before your appointment', 'You will receive the online session link by email one day before your appointment', 'Box „Co bude dál?" — Krok 3', 'booking-success', 'co_dal', 'text', 'Krok 3', 290), -- from src/pages/BookingSuccess.tsx:272
  ('booking_success_details_title', 'Booking Details', 'Booking Details', 'Karta „Detaily rezervace" — Nadpis karty', 'booking-success', 'detaily', 'text', 'Nadpis karty', 150), -- from src/pages/BookingSuccess.tsx:159
  ('booking_success_label_date', 'Date', 'Date', 'Karta „Detaily rezervace" — Popisek „Datum"', 'booking-success', 'detaily', 'text', 'Popisek „Datum"', 160), -- from src/pages/BookingSuccess.tsx:165
  ('booking_success_label_time', 'Time', 'Time', 'Karta „Detaily rezervace" — Popisek „Čas"', 'booking-success', 'detaily', 'text', 'Popisek „Čas"', 170), -- from src/pages/BookingSuccess.tsx:175
  ('booking_success_label_session_type', 'Session Type', 'Session Type', 'Karta „Detaily rezervace" — Popisek „Typ sezení"', 'booking-success', 'detaily', 'text', 'Popisek „Typ sezení"', 180), -- from src/pages/BookingSuccess.tsx:190
  ('booking_success_label_client', 'Client:', 'Client:', 'Karta „Detaily rezervace" — Popisek „Klient:"', 'booking-success', 'detaily', 'text', 'Popisek „Klient:"', 190), -- from src/pages/BookingSuccess.tsx:199
  ('booking_success_label_email', 'Email:', 'Email:', 'Karta „Detaily rezervace" — Popisek „E-mail:"', 'booking-success', 'detaily', 'text', 'Popisek „E-mail:"', 200), -- from src/pages/BookingSuccess.tsx:203
  ('booking_success_label_price', 'Price:', 'Price:', 'Karta „Detaily rezervace" — Popisek „Cena:" (částka zůstává mimo CMS)', 'booking-success', 'detaily', 'text', 'Popisek „Cena:" (částka zůstává mimo CMS)', 210), -- from src/pages/BookingSuccess.tsx:208
  ('booking_success_label_note', 'Note:', 'Note:', 'Karta „Detaily rezervace" — Popisek „Poznámka:"', 'booking-success', 'detaily', 'text', 'Popisek „Poznámka:"', 220), -- from src/pages/BookingSuccess.tsx:214
  ('booking_success_title_confirmed', 'Booking Confirmed!', 'Booking Confirmed!', 'Hlavička — potvrzeno / vytvořeno — Nadpis — rezervace potvrzena', 'booking-success', 'hlavicka', 'text', 'Nadpis — rezervace potvrzena', 110), -- from src/pages/BookingSuccess.tsx:145
  ('booking_success_title_created', 'Booking Created', 'Booking Created', 'Hlavička — potvrzeno / vytvořeno — Nadpis — rezervace vytvořena (čeká na platbu)', 'booking-success', 'hlavicka', 'text', 'Nadpis — rezervace vytvořena (čeká na platbu)', 120), -- from src/pages/BookingSuccess.tsx:146
  ('booking_success_subtitle_confirmed', 'Your booking has been successfully confirmed. Confirmation email has been sent.', 'Your booking has been successfully confirmed. Confirmation email has been sent.', 'Hlavička — potvrzeno / vytvořeno — Podnadpis — rezervace potvrzena', 'booking-success', 'hlavicka', 'textarea', 'Podnadpis — rezervace potvrzena', 130), -- from src/pages/BookingSuccess.tsx:151
  ('booking_success_subtitle_pending', 'Booking is awaiting payment completion.', 'Booking is awaiting payment completion.', 'Hlavička — potvrzeno / vytvořeno — Podnadpis — čeká na platbu', 'booking-success', 'hlavicka', 'text', 'Podnadpis — čeká na platbu', 140), -- from src/pages/BookingSuccess.tsx:152
  ('booking_success_contact_text', 'Have questions? Contact us at', 'Have questions? Contact us at', 'Kontaktní informace úplně dole — Text „Máte otázky? Kontaktujte nás na"', 'booking-success', 'kontakt', 'text', 'Text „Máte otázky? Kontaktujte nás na"', 300), -- from src/pages/BookingSuccess.tsx:280
  ('booking_success_loading_text', 'Loading reservation...', 'Loading reservation...', 'Stav: načítání rezervace — Text', 'booking-success', 'nacitani', 'text', 'Text', 10), -- from src/pages/BookingSuccess.tsx:92
  ('booking_success_type_discovery', 'Discovery Call', 'Discovery Call', 'Názvy typů sezení — Discovery Call', 'booking-success', 'typy_sluzeb', 'text', 'Discovery Call', 50), -- from src/pages/BookingSuccess.tsx:60
  ('booking_success_type_one_on_one', 'Individual Consultation', 'Individual Consultation', 'Názvy typů sezení — Individual Consultation', 'booking-success', 'typy_sluzeb', 'text', 'Individual Consultation', 60), -- from src/pages/BookingSuccess.tsx:61
  ('booking_success_type_family', 'Family Session', 'Family Session', 'Názvy typů sezení — Family Session', 'booking-success', 'typy_sluzeb', 'text', 'Family Session', 70), -- from src/pages/BookingSuccess.tsx:62
  ('booking_success_type_endometriosis_support', 'Endometriosis & Chronic Pain Support', 'Endometriosis & Chronic Pain Support', 'Názvy typů sezení — Endometriosis & Chronic Pain Support', 'booking-success', 'typy_sluzeb', 'text', 'Endometriosis & Chronic Pain Support', 80), -- from src/pages/BookingSuccess.tsx:63
  ('booking_success_type_individual_eft_reiki_offer', 'EFT Tapping & Reiki Session', 'EFT Tapping & Reiki Session', 'Názvy typů sezení — EFT Tapping & Reiki Session', 'booking-success', 'typy_sluzeb', 'text', 'EFT Tapping & Reiki Session', 90), -- from src/pages/BookingSuccess.tsx:64
  ('booking_success_type_premium_consultation', 'Premium Consultation', 'Premium Consultation', 'Názvy typů sezení — Premium Consultation', 'booking-success', 'typy_sluzeb', 'text', 'Premium Consultation', 100) -- from src/pages/BookingSuccess.tsx:65
ON CONFLICT (key) DO NOTHING;
