-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- Workshopy.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('workshops_adults_title', 'Expressive Art Workshops — Adults', 'Expressive Art Workshops — Adults', 'Sekce – Workshopy pro dospělé — Nadpis sekce', 'workshopy', 'adults', 'text', 'Nadpis sekce', 130), -- from src/pages/Workshopy.tsx:183
  ('workshops_adults_text_1', 'In this space, adults allow themselves to slow down and reconnect with their creativity. Through expressive art, participants release stress, explore emotions, and embrace playfulness. Many leave feeling lighter, refreshed, and inspired — carrying with them not only the artworks they created but also the joy and relaxation of a day fully spent expressing themselves.', 'In this space, adults allow themselves to slow down and reconnect with their creativity. Through expressive art, participants release stress, explore emotions, and embrace playfulness. Many leave feeling lighter, refreshed, and inspired — carrying with them not only the artworks they created but also the joy and relaxation of a day fully spent expressing themselves.', 'Sekce – Workshopy pro dospělé — První odstavec textu', 'workshopy', 'adults', 'textarea', 'První odstavec textu', 140), -- from src/pages/Workshopy.tsx:188
  ('workshops_adults_text_2', 'People leave not only with a unique piece of art that tells their story, but also with a sense of calm, clarity, and a little spark of joy.', 'People leave not only with a unique piece of art that tells their story, but also with a sense of calm, clarity, and a little spark of joy.', 'Sekce – Workshopy pro dospělé — Druhý odstavec textu', 'workshopy', 'adults', 'textarea', 'Druhý odstavec textu', 150), -- from src/pages/Workshopy.tsx:191
  ('workshops_adults_alt', 'Adult expressive art workshop', 'Adult expressive art workshop', 'Sekce – Workshopy pro dospělé — Popisek (alt) fotek – používá se pro všechny 4 fotky', 'workshopy', 'adults', 'text', 'Popisek (alt) fotek – používá se pro všechny 4 fotky', 160), -- from src/pages/Workshopy.tsx:198
  ('workshops_hero_badge', 'Interactive Learning', 'Interactive Learning', 'Úvodní hlavička — Odznak nad hlavním nadpisem', 'workshopy', 'hero', 'text', 'Odznak nad hlavním nadpisem', 10), -- from src/pages/Workshopy.tsx:73
  ('workshops_hero_title_pre', 'Transformative', 'Transformative', 'Úvodní hlavička — Nadpis – první část', 'workshopy', 'hero', 'text', 'Nadpis – první část', 20), -- from src/pages/Workshopy.tsx:78
  ('workshops_hero_title_highlight', 'Workshops', 'Workshops', 'Úvodní hlavička — Nadpis – zvýrazněné slovo', 'workshopy', 'hero', 'text', 'Nadpis – zvýrazněné slovo', 30), -- from src/pages/Workshopy.tsx:78
  ('workshops_hero_subtitle', 'Hands-on workshops combining art expressive therapy and creative practices to help you build resilience and thrive in your expat journey.', 'Hands-on workshops combining art expressive therapy and creative practices to help you build resilience and thrive in your expat journey.', 'Úvodní hlavička — Podnadpis pod hlavním nadpisem', 'workshopy', 'hero', 'textarea', 'Podnadpis pod hlavním nadpisem', 40), -- from src/pages/Workshopy.tsx:82
  ('workshops_kids_title', 'Expressive Art Workshops — Kids & Parents', 'Expressive Art Workshops — Kids & Parents', 'Sekce – Workshopy pro děti a rodiče — Nadpis sekce', 'workshopy', 'kids_parents', 'text', 'Nadpis sekce', 90), -- from src/pages/Workshopy.tsx:143
  ('workshops_kids_text_1', 'These workshops are a wonderful opportunity for parents and children to spend valuable time together, creating, learning, and discovering more about each other. They are full of laughter, curiosity, and shared exploration. Parents and children paint side by side, experimenting with colors, shapes, and textures, while gently connecting in a space that encourages creativity and presence.', 'These workshops are a wonderful opportunity for parents and children to spend valuable time together, creating, learning, and discovering more about each other. They are full of laughter, curiosity, and shared exploration. Parents and children paint side by side, experimenting with colors, shapes, and textures, while gently connecting in a space that encourages creativity and presence.', 'Sekce – Workshopy pro děti a rodiče — První odstavec textu', 'workshopy', 'kids_parents', 'textarea', 'První odstavec textu', 100), -- from src/pages/Workshopy.tsx:148
  ('workshops_kids_text_2', 'It''s amazing to watch everyone relax, let go, and connect through art. By the end of the session, the room is alive with happiness, gentle pride, and colorful creations that tell stories only your hearts can tell.', 'It''s amazing to watch everyone relax, let go, and connect through art. By the end of the session, the room is alive with happiness, gentle pride, and colorful creations that tell stories only your hearts can tell.', 'Sekce – Workshopy pro děti a rodiče — Druhý odstavec textu', 'workshopy', 'kids_parents', 'textarea', 'Druhý odstavec textu', 110), -- from src/pages/Workshopy.tsx:151
  ('workshops_kids_alt', 'Kids and parents workshop', 'Kids and parents workshop', 'Sekce – Workshopy pro děti a rodiče — Popisek (alt) fotek – používá se pro obě fotky', 'workshopy', 'kids_parents', 'text', 'Popisek (alt) fotek – používá se pro obě fotky', 120), -- from src/pages/Workshopy.tsx:158
  ('workshops_upcoming_title', 'Upcoming Workshops', 'Upcoming Workshops', 'Nadcházející workshopy (ze systému) — Nadpis sekce', 'workshopy', 'nadchazejici', 'text', 'Nadpis sekce', 170), -- from src/pages/Workshopy.tsx:234
  ('workshops_view_workshop_label', 'View Workshop', 'View Workshop', 'Nadcházející workshopy (ze systému) — Text odkazu na detail workshopu', 'workshopy', 'nadchazejici', 'text', 'Text odkazu na detail workshopu', 180), -- from src/pages/Workshopy.tsx:311
  ('workshops_silk_title', 'My Creations — Silk Paintings', 'My Creations — Silk Paintings', 'Sekce – Malby na hedvábí — Nadpis sekce', 'workshopy', 'silk_paintings', 'text', 'Nadpis sekce', 50), -- from src/pages/Workshopy.tsx:96
  ('workshops_silk_text_1', 'I discovered silk painting as my personal way to relax my mind — a space where time seemed to stop, and all the usual thoughts quieted down. It became my "power of now," a moment to simply be and let creativity flow.', 'I discovered silk painting as my personal way to relax my mind — a space where time seemed to stop, and all the usual thoughts quieted down. It became my "power of now," a moment to simply be and let creativity flow.', 'Sekce – Malby na hedvábí — První odstavec textu', 'workshopy', 'silk_paintings', 'textarea', 'První odstavec textu', 60), -- from src/pages/Workshopy.tsx:101
  ('workshops_silk_text_2', 'Stepping into a world of color and texture, participants often pause, smile, and breathe a little deeper. These silk painting sessions offer a space to explore creativity without pressure, where each brushstroke can capture a feeling, a thought, or a moment.', 'Stepping into a world of color and texture, participants often pause, smile, and breathe a little deeper. These silk painting sessions offer a space to explore creativity without pressure, where each brushstroke can capture a feeling, a thought, or a moment.', 'Sekce – Malby na hedvábí — Druhý odstavec textu', 'workshopy', 'silk_paintings', 'textarea', 'Druhý odstavec textu', 70), -- from src/pages/Workshopy.tsx:104
  ('workshops_silk_alt', 'Silk painting artwork', 'Silk painting artwork', 'Sekce – Malby na hedvábí — Popisek (alt) fotek malby na hedvábí – používá se pro všechny 3 fotky', 'workshopy', 'silk_paintings', 'text', 'Popisek (alt) fotek malby na hedvábí – používá se pro všechny 3 fotky', 80) -- from src/pages/Workshopy.tsx:111
ON CONFLICT (key) DO NOTHING;
