-- Seed the homepage Services section keys, generated from the fallbacks in
-- Services.tsx so the seeded copy matches what the page renders today.

INSERT INTO public.cms_content (key, value, description, page, section, field_type) VALUES
  ('homepage_services_1_title', 'Resilient Hubs', 'Homepage — services 1 title', 'homepage', 'services', 'text'),
  ('homepage_services_1_subtitle', 'Membership Programs', 'Homepage — services 1 subtitle', 'homepage', 'services', 'text'),
  ('homepage_services_1_description', '4 transformational programs combining evidence-based techniques, expressive arts, and energy work for lasting resilience.', 'Homepage — services 1 description', 'homepage', 'services', 'textarea'),
  ('homepage_services_1_price', 'from €37', 'Homepage — services 1 price', 'homepage', 'services', 'text'),
  ('homepage_services_2_title', 'Individual Consultations', 'Homepage — services 2 title', 'homepage', 'services', 'text'),
  ('homepage_services_2_subtitle', '1:1 Personalized Guidance', 'Homepage — services 2 subtitle', 'homepage', 'services', 'text'),
  ('homepage_services_2_description', 'Personalized one-on-one guidance tailored to your unique experience. Book your session through our calendar.', 'Homepage — services 2 description', 'homepage', 'services', 'textarea'),
  ('homepage_services_2_price', '€107/hour', 'Homepage — services 2 price', 'homepage', 'services', 'text'),
  ('homepage_services_3_title', 'Workshops', 'Homepage — services 3 title', 'homepage', 'services', 'text'),
  ('homepage_services_3_subtitle', 'For Groups & Organizations', 'Homepage — services 3 subtitle', 'homepage', 'services', 'text'),
  ('homepage_services_3_description', 'Interactive workshops for organizations and groups. Innovative approaches to building resilience abroad.', 'Homepage — services 3 description', 'homepage', 'services', 'textarea'),
  ('homepage_services_3_price', 'Contact for details', 'Homepage — services 3 price', 'homepage', 'services', 'text'),
  ('homepage_approach_1_title', 'Expatriate-Specific Techniques', 'Homepage — approach 1 title', 'homepage', 'approach', 'text'),
  ('homepage_approach_1_description', 'Strategies developed specifically for the unique challenges of living abroad', 'Homepage — approach 1 description', 'homepage', 'approach', 'text'),
  ('homepage_approach_2_title', 'Creative Expression', 'Homepage — approach 2 title', 'homepage', 'approach', 'text'),
  ('homepage_approach_2_description', 'Process complex emotions through art and expressive techniques when words aren''t enough', 'Homepage — approach 2 description', 'homepage', 'approach', 'text'),
  ('homepage_approach_3_title', 'Holistic Integration', 'Homepage — approach 3 title', 'homepage', 'approach', 'text'),
  ('homepage_approach_3_description', 'Combining mind, body, and energy work for complete resilience', 'Homepage — approach 3 description', 'homepage', 'approach', 'text'),
  ('homepage_who_1', 'Expat women navigating new cultures while staying connected to who they truly are', 'Homepage — who 1', 'homepage', 'who_its_for', 'text'),
  ('homepage_who_2', 'Women living abroad who feel emotionally stretched or unsupported, seeking grounded tools they can rely on anywhere', 'Homepage — who 2', 'homepage', 'who_its_for', 'textarea'),
  ('homepage_who_3', 'Globally mobile women facing constant change and wanting deeper inner stability, confidence, and clarity', 'Homepage — who 3', 'homepage', 'who_its_for', 'textarea'),
  ('homepage_whyjoin_1_title', 'Learn to regulate your nervous system', 'Homepage — whyjoin 1 title', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_1_description', 'and create a greater sense of calm and emotional safety.', 'Homepage — whyjoin 1 description', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_2_title', 'Develop practical tools', 'Homepage — whyjoin 2 title', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_2_description', 'to navigate life''s challenges with more confidence, clarity, and resilience.', 'Homepage — whyjoin 2 description', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_3_title', 'Discover EFT, expressive art, meditation,', 'Homepage — whyjoin 3 title', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_3_description', 'and other holistic practices you can use in everyday life.', 'Homepage — whyjoin 3 description', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_4_title', 'Join a supportive community', 'Homepage — whyjoin 4 title', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_4_description', 'of like-minded expat women from around the world.', 'Homepage — whyjoin 4 description', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_5_title', 'Follow a step-by-step journey', 'Homepage — whyjoin 5 title', 'homepage', 'why_join', 'text'),
  ('homepage_whyjoin_5_description', 'that helps you build lasting emotional resilience, deepen your self-awareness, and reconnect with who you truly are.', 'Homepage — whyjoin 5 description', 'homepage', 'why_join', 'textarea'),
  ('homepage_ways_1_title', 'Resilient Hub Membership', 'Homepage — ways 1 title', 'homepage', 'ways_to_work', 'text'),
  ('homepage_ways_1_description', 'Ongoing guidance, practical tools, and self-paced learning to build emotional resilience.', 'Homepage — ways 1 description', 'homepage', 'ways_to_work', 'text'),
  ('homepage_ways_2_title', 'Individual Consultations', 'Homepage — ways 2 title', 'homepage', 'ways_to_work', 'text'),
  ('homepage_ways_2_description', 'Personalised one-to-one holistic counselling tailored to your unique needs and goals.', 'Homepage — ways 2 description', 'homepage', 'ways_to_work', 'text'),
  ('homepage_ways_3_title', 'Workshops & Group Sessions', 'Homepage — ways 3 title', 'homepage', 'ways_to_work', 'text'),
  ('homepage_ways_3_description', 'Interactive wellbeing experiences featuring Expressive Art, Silk Painting, EFT Tapping, and mindfulness for communities and organisations.', 'Homepage — ways 3 description', 'homepage', 'ways_to_work', 'textarea')
ON CONFLICT (key) DO NOTHING;
