-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- Terms.tsx + Privacy.tsx + Cookies.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('cookies_hero_badge', 'Cookies', 'Cookies', 'Zásady používání cookies — Úvodní hlavička — Text štítku nad nadpisem', 'legal', 'cookies_hero', 'text', 'Text štítku nad nadpisem', 10), -- from src/pages/Cookies.tsx:26
  ('cookies_hero_title', 'Cookies Policy', 'Cookies Policy', 'Zásady používání cookies — Úvodní hlavička — Hlavní nadpis (H1)', 'legal', 'cookies_hero', 'text', 'Hlavní nadpis (H1)', 20), -- from src/pages/Cookies.tsx:31
  ('cookies_hero_updated', 'Last updated: February 2026', 'Last updated: February 2026', 'Zásady používání cookies — Úvodní hlavička — Datum poslední aktualizace', 'legal', 'cookies_hero', 'text', 'Datum poslední aktualizace', 30), -- from src/pages/Cookies.tsx:35
  ('cookies_intro_p1', 'This Cookies Policy explains how Resilient Mind ("we," "our," "us") uses cookies and similar technologies on our website. It also explains your options for managing or disabling cookies.', 'This Cookies Policy explains how Resilient Mind ("we," "our," "us") uses cookies and similar technologies on our website. It also explains your options for managing or disabling cookies.', 'Zásady používání cookies — Úvod — Úvodní odstavec 1', 'legal', 'cookies_intro', 'textarea', 'Úvodní odstavec 1', 10), -- from src/pages/Cookies.tsx:45
  ('cookies_intro_p2', 'By using our website, you consent to our use of cookies as described in this policy.', 'By using our website, you consent to our use of cookies as described in this policy.', 'Zásady používání cookies — Úvod — Úvodní odstavec 2', 'legal', 'cookies_intro', 'text', 'Úvodní odstavec 2', 20), -- from src/pages/Cookies.tsx:51
  ('cookies_s1_title', '1. What Are Cookies?', '1. What Are Cookies?', 'Zásady používání cookies — 1. Co jsou cookies? — Nadpis sekce', 'legal', 'cookies_s1', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:56
  ('cookies_s1_p1', 'A cookie is a small file that is downloaded to your computer or device when you visit a website. Cookies help websites recognize your device, store preferences, analyze usage, and provide personalized content or advertisements.', 'A cookie is a small file that is downloaded to your computer or device when you visit a website. Cookies help websites recognize your device, store preferences, analyze usage, and provide personalized content or advertisements.', 'Zásady používání cookies — 1. Co jsou cookies? — Odstavec', 'legal', 'cookies_s1', 'textarea', 'Odstavec', 20), -- from src/pages/Cookies.tsx:58
  ('cookies_s2_title', '2. Types of Cookies We Use', '2. Types of Cookies We Use', 'Zásady používání cookies — 2. Typy cookies, které používáme — Nadpis sekce', 'legal', 'cookies_s2', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:66
  ('cookies_s2a_title', 'a) Analytical / Performance Cookies', 'a) Analytical / Performance Cookies', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies — Nadpis podsekce', 'legal', 'cookies_s2a', 'text', 'Nadpis podsekce', 10), -- from src/pages/Cookies.tsx:69
  ('cookies_s2a_li1', 'These cookies help us measure how users interact with our website.', 'These cookies help us measure how users interact with our website.', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies — Položka seznamu 1', 'legal', 'cookies_s2a', 'text', 'Položka seznamu 1', 20), -- from src/pages/Cookies.tsx:71
  ('cookies_s2a_li2', 'Examples: Google Analytics cookies to track page visits, time on site, and navigation patterns.', 'Examples: Google Analytics cookies to track page visits, time on site, and navigation patterns.', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies — Položka seznamu 2', 'legal', 'cookies_s2a', 'textarea', 'Položka seznamu 2', 30), -- from src/pages/Cookies.tsx:72
  ('cookies_s2a_purpose_label', 'Purpose:', 'Purpose:', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies — Popisek "Účel:"', 'legal', 'cookies_s2a', 'text', 'Popisek "Účel:"', 40), -- from src/pages/Cookies.tsx:75
  ('cookies_s2a_purpose', 'To improve website performance and enhance your experience.', 'To improve website performance and enhance your experience.', 'Zásady používání cookies — 2a) Analytické / výkonnostní cookies — Text — účel', 'legal', 'cookies_s2a', 'text', 'Text — účel', 50), -- from src/pages/Cookies.tsx:75
  ('cookies_s2b_title', 'b) Functional / Preference Cookies', 'b) Functional / Preference Cookies', 'Zásady používání cookies — 2b) Funkční cookies / cookies pro předvolby — Nadpis podsekce', 'legal', 'cookies_s2b', 'text', 'Nadpis podsekce', 10), -- from src/pages/Cookies.tsx:80
  ('cookies_s2b_li1', 'Remember your preferences, such as language or settings in tools like video/audio players.', 'Remember your preferences, such as language or settings in tools like video/audio players.', 'Zásady používání cookies — 2b) Funkční cookies / cookies pro předvolby — Položka seznamu 1', 'legal', 'cookies_s2b', 'text', 'Položka seznamu 1', 20), -- from src/pages/Cookies.tsx:82
  ('cookies_s2b_purpose_label', 'Purpose:', 'Purpose:', 'Zásady používání cookies — 2b) Funkční cookies / cookies pro předvolby — Popisek "Účel:"', 'legal', 'cookies_s2b', 'text', 'Popisek "Účel:"', 30), -- from src/pages/Cookies.tsx:85
  ('cookies_s2b_purpose', 'To ensure the website works as you expect each time you visit.', 'To ensure the website works as you expect each time you visit.', 'Zásady používání cookies — 2b) Funkční cookies / cookies pro předvolby — Text — účel', 'legal', 'cookies_s2b', 'text', 'Text — účel', 40), -- from src/pages/Cookies.tsx:85
  ('cookies_s2c_title', 'c) Registration / Authentication Cookies', 'c) Registration / Authentication Cookies', 'Zásady používání cookies — 2c) Registrační / autentizační cookies — Nadpis podsekce', 'legal', 'cookies_s2c', 'text', 'Nadpis podsekce', 10), -- from src/pages/Cookies.tsx:90
  ('cookies_s2c_li1', 'Used when you register or log in to a service on our website.', 'Used when you register or log in to a service on our website.', 'Zásady používání cookies — 2c) Registrační / autentizační cookies — Položka seznamu 1', 'legal', 'cookies_s2c', 'text', 'Položka seznamu 1', 20), -- from src/pages/Cookies.tsx:92
  ('cookies_s2c_purpose_label', 'Purpose:', 'Purpose:', 'Zásady používání cookies — 2c) Registrační / autentizační cookies — Popisek "Účel:"', 'legal', 'cookies_s2c', 'text', 'Popisek "Účel:"', 30), -- from src/pages/Cookies.tsx:95
  ('cookies_s2c_purpose', 'To keep you logged in and identify authorized users for restricted areas.', 'To keep you logged in and identify authorized users for restricted areas.', 'Zásady používání cookies — 2c) Registrační / autentizační cookies — Text — účel', 'legal', 'cookies_s2c', 'text', 'Text — účel', 40), -- from src/pages/Cookies.tsx:95
  ('cookies_s2d_title', 'd) Advertising / Marketing Cookies', 'd) Advertising / Marketing Cookies', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies — Nadpis podsekce', 'legal', 'cookies_s2d', 'text', 'Nadpis podsekce', 10), -- from src/pages/Cookies.tsx:100
  ('cookies_s2d_li1', 'Used to show personalized content or advertisements.', 'Used to show personalized content or advertisements.', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies — Položka seznamu 1', 'legal', 'cookies_s2d', 'text', 'Položka seznamu 1', 20), -- from src/pages/Cookies.tsx:102
  ('cookies_s2d_li2', 'May be set by us or by third-party advertising partners.', 'May be set by us or by third-party advertising partners.', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies — Položka seznamu 2', 'legal', 'cookies_s2d', 'text', 'Položka seznamu 2', 30), -- from src/pages/Cookies.tsx:103
  ('cookies_s2d_purpose_label', 'Purpose:', 'Purpose:', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies — Popisek "Účel:"', 'legal', 'cookies_s2d', 'text', 'Popisek "Účel:"', 40), -- from src/pages/Cookies.tsx:106
  ('cookies_s2d_purpose', 'To deliver relevant ads based on browsing behavior.', 'To deliver relevant ads based on browsing behavior.', 'Zásady používání cookies — 2d) Reklamní / marketingové cookies — Text — účel', 'legal', 'cookies_s2d', 'text', 'Text — účel', 50), -- from src/pages/Cookies.tsx:106
  ('cookies_s2e_title', 'e) Geolocation Cookies', 'e) Geolocation Cookies', 'Zásady používání cookies — 2e) Geolokační cookies — Nadpis podsekce', 'legal', 'cookies_s2e', 'text', 'Nadpis podsekce', 10), -- from src/pages/Cookies.tsx:111
  ('cookies_s2e_li1', 'Identify the country or region of your visit to provide relevant content.', 'Identify the country or region of your visit to provide relevant content.', 'Zásady používání cookies — 2e) Geolokační cookies — Položka seznamu 1', 'legal', 'cookies_s2e', 'text', 'Položka seznamu 1', 20), -- from src/pages/Cookies.tsx:113
  ('cookies_s2e_li2', 'Fully anonymous and only used for content targeting purposes.', 'Fully anonymous and only used for content targeting purposes.', 'Zásady používání cookies — 2e) Geolokační cookies — Položka seznamu 2', 'legal', 'cookies_s2e', 'text', 'Položka seznamu 2', 30), -- from src/pages/Cookies.tsx:114
  ('cookies_s3_title', '3. Session vs Persistent Cookies', '3. Session vs Persistent Cookies', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies — Nadpis sekce', 'legal', 'cookies_s3', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:120
  ('cookies_s3_li1_label', 'Session cookies:', 'Session cookies:', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies — Popisek — Session cookies', 'legal', 'cookies_s3', 'text', 'Popisek — Session cookies', 20), -- from src/pages/Cookies.tsx:122
  ('cookies_s3_li1', 'Deleted when you close your browser.', 'Deleted when you close your browser.', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies — Text — Session cookies', 'legal', 'cookies_s3', 'text', 'Text — Session cookies', 30), -- from src/pages/Cookies.tsx:122
  ('cookies_s3_li2_label', 'Persistent cookies:', 'Persistent cookies:', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies — Popisek — Persistent cookies', 'legal', 'cookies_s3', 'text', 'Popisek — Persistent cookies', 40), -- from src/pages/Cookies.tsx:123
  ('cookies_s3_li2', 'Stored until they expire or are manually deleted, e.g., to keep you logged in.', 'Stored until they expire or are manually deleted, e.g., to keep you logged in.', 'Zásady používání cookies — 3. Krátkodobé (session) vs. trvalé cookies — Text — Persistent cookies', 'legal', 'cookies_s3', 'text', 'Text — Persistent cookies', 50), -- from src/pages/Cookies.tsx:123
  ('cookies_s4_title', '4. First-Party vs Third-Party Cookies', '4. First-Party vs Third-Party Cookies', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran — Nadpis sekce', 'legal', 'cookies_s4', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:128
  ('cookies_s4_li1_label', 'First-party cookies:', 'First-party cookies:', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran — Popisek — First-party cookies', 'legal', 'cookies_s4', 'text', 'Popisek — First-party cookies', 20), -- from src/pages/Cookies.tsx:130
  ('cookies_s4_li1', 'Set directly by Resilient Mind to provide our services.', 'Set directly by Resilient Mind to provide our services.', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran — Text — First-party cookies', 'legal', 'cookies_s4', 'text', 'Text — First-party cookies', 30), -- from src/pages/Cookies.tsx:130
  ('cookies_s4_li2_label', 'Third-party cookies:', 'Third-party cookies:', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran — Popisek — Third-party cookies', 'legal', 'cookies_s4', 'text', 'Popisek — Third-party cookies', 40), -- from src/pages/Cookies.tsx:131
  ('cookies_s4_li2', 'Set by external services (e.g., Google Analytics, social media platforms) that may track your interactions with our website.', 'Set by external services (e.g., Google Analytics, social media platforms) that may track your interactions with our website.', 'Zásady používání cookies — 4. Vlastní vs. cookies třetích stran — Text — Third-party cookies', 'legal', 'cookies_s4', 'textarea', 'Text — Third-party cookies', 50), -- from src/pages/Cookies.tsx:131
  ('cookies_s5_title', '5. Social Media Cookies', '5. Social Media Cookies', 'Zásady používání cookies — 5. Cookies sociálních sítí — Nadpis sekce', 'legal', 'cookies_s5', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:136
  ('cookies_s5_p1', 'If you interact with our content on social media platforms (e.g., Facebook, Instagram, YouTube), these platforms may set cookies to measure engagement.', 'If you interact with our content on social media platforms (e.g., Facebook, Instagram, YouTube), these platforms may set cookies to measure engagement.', 'Zásady používání cookies — 5. Cookies sociálních sítí — Odstavec', 'legal', 'cookies_s5', 'textarea', 'Odstavec', 20), -- from src/pages/Cookies.tsx:138
  ('cookies_s5_li1', 'Their use is governed by the social platform''s own privacy policy.', 'Their use is governed by the social platform''s own privacy policy.', 'Zásady používání cookies — 5. Cookies sociálních sítí — Položka seznamu 1', 'legal', 'cookies_s5', 'text', 'Položka seznamu 1', 30), -- from src/pages/Cookies.tsx:144
  ('cookies_s5_li2', 'We do not control how these third-party cookies are used.', 'We do not control how these third-party cookies are used.', 'Zásady používání cookies — 5. Cookies sociálních sítí — Položka seznamu 2', 'legal', 'cookies_s5', 'text', 'Položka seznamu 2', 40), -- from src/pages/Cookies.tsx:145
  ('cookies_s6_title', '6. Managing or Disabling Cookies', '6. Managing or Disabling Cookies', 'Zásady používání cookies — 6. Správa a zakázání cookies — Nadpis sekce', 'legal', 'cookies_s6', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:150
  ('cookies_s6_intro', 'You can manage, block, or delete cookies via your browser settings. Options are available for most browsers, such as:', 'You can manage, block, or delete cookies via your browser settings. Options are available for most browsers, such as:', 'Zásady používání cookies — 6. Správa a zakázání cookies — Úvodní věta', 'legal', 'cookies_s6', 'text', 'Úvodní věta', 20), -- from src/pages/Cookies.tsx:152
  ('cookies_s6_chrome_label', 'Chrome:', 'Chrome:', 'Zásady používání cookies — 6. Správa a zakázání cookies — Popisek — Chrome', 'legal', 'cookies_s6', 'text', 'Popisek — Chrome', 30), -- from src/pages/Cookies.tsx:155
  ('cookies_s6_firefox_label', 'Firefox:', 'Firefox:', 'Zásady používání cookies — 6. Správa a zakázání cookies — Popisek — Firefox', 'legal', 'cookies_s6', 'text', 'Popisek — Firefox', 40), -- from src/pages/Cookies.tsx:158
  ('cookies_s6_safari_label', 'Safari:', 'Safari:', 'Zásady používání cookies — 6. Správa a zakázání cookies — Popisek — Safari', 'legal', 'cookies_s6', 'text', 'Popisek — Safari', 50), -- from src/pages/Cookies.tsx:161
  ('cookies_s6_end', 'You can choose to accept all cookies, reject all cookies, or be notified when a cookie is sent.', 'You can choose to accept all cookies, reject all cookies, or be notified when a cookie is sent.', 'Zásady používání cookies — 6. Správa a zakázání cookies — Závěrečná věta', 'legal', 'cookies_s6', 'text', 'Závěrečná věta', 60), -- from src/pages/Cookies.tsx:166
  ('cookies_s7_title', '7. Cookie Consent', '7. Cookie Consent', 'Zásady používání cookies — 7. Souhlas s cookies — Nadpis sekce', 'legal', 'cookies_s7', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:171
  ('cookies_s7_p1', 'When you first visit our website, you will see a cookie notice asking for your consent. Non-essential cookies (analytics, marketing) are only installed after you provide consent.', 'When you first visit our website, you will see a cookie notice asking for your consent. Non-essential cookies (analytics, marketing) are only installed after you provide consent.', 'Zásady používání cookies — 7. Souhlas s cookies — Odstavec', 'legal', 'cookies_s7', 'textarea', 'Odstavec', 20), -- from src/pages/Cookies.tsx:173
  ('cookies_s8_title', '8. Updates to This Policy', '8. Updates to This Policy', 'Zásady používání cookies — 8. Aktualizace zásad — Nadpis sekce', 'legal', 'cookies_s8', 'text', 'Nadpis sekce', 10), -- from src/pages/Cookies.tsx:181
  ('cookies_s8_p1', 'We may update this Cookies Policy to comply with new legal requirements or to reflect changes in our services. Updates will be published on this page. We recommend checking this page periodically.', 'We may update this Cookies Policy to comply with new legal requirements or to reflect changes in our services. Updates will be published on this page. We recommend checking this page periodically.', 'Zásady používání cookies — 8. Aktualizace zásad — Odstavec', 'legal', 'cookies_s8', 'textarea', 'Odstavec', 20), -- from src/pages/Cookies.tsx:183
  ('privacy_hero_badge', 'Privacy', 'Privacy', 'Zásady ochrany osobních údajů (GDPR) — Úvodní hlavička — Text štítku nad nadpisem', 'legal', 'privacy_hero', 'text', 'Text štítku nad nadpisem', 10), -- from src/pages/Privacy.tsx:26
  ('privacy_hero_title', 'Personal Data Protection (GDPR)', 'Personal Data Protection (GDPR)', 'Zásady ochrany osobních údajů (GDPR) — Úvodní hlavička — Hlavní nadpis (H1)', 'legal', 'privacy_hero', 'text', 'Hlavní nadpis (H1)', 20), -- from src/pages/Privacy.tsx:31
  ('privacy_hero_updated', 'Last updated: February 2026', 'Last updated: February 2026', 'Zásady ochrany osobních údajů (GDPR) — Úvodní hlavička — Datum poslední aktualizace', 'legal', 'privacy_hero', 'text', 'Datum poslední aktualizace', 30), -- from src/pages/Privacy.tsx:35
  ('privacy_intro_p1', 'Statement on the Processing of Personal Data in accordance with Regulation (EU) 2016/679 (GDPR)', 'Statement on the Processing of Personal Data in accordance with Regulation (EU) 2016/679 (GDPR)', 'Zásady ochrany osobních údajů (GDPR) — Úvod — Úvodní text (kurzíva)', 'legal', 'privacy_intro', 'text', 'Úvodní text (kurzíva)', 10), -- from src/pages/Privacy.tsx:45
  ('privacy_intro_p2', 'If you are a customer, newsletter subscriber, or visitor of this website, you entrust us with your personal data. We are responsible for protecting it and ensuring its security. Please read this statement to understand how we handle your personal data and your rights under GDPR.', 'If you are a customer, newsletter subscriber, or visitor of this website, you entrust us with your personal data. We are responsible for protecting it and ensuring its security. Please read this statement to understand how we handle your personal data and your rights under GDPR.', 'Zásady ochrany osobních údajů (GDPR) — Úvod — Úvodní odstavec', 'legal', 'privacy_intro', 'textarea', 'Úvodní odstavec', 20), -- from src/pages/Privacy.tsx:52
  ('privacy_s1_title', '1. Data Controller', '1. Data Controller', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů — Nadpis sekce', 'legal', 'privacy_s1', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:60
  ('privacy_s1_p1', 'The data controller for personal data on the website resilientmind.io is:', 'The data controller for personal data on the website resilientmind.io is:', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů — Úvodní věta', 'legal', 'privacy_s1', 'text', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:62
  ('privacy_s1_company_name', 'Resilient Mind', 'Resilient Mind', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů — Firma — název', 'legal', 'privacy_s1', 'text', 'Firma — název', 30), -- from src/pages/Privacy.tsx:65
  ('privacy_s1_company_owner', 'Owner: Silvie Bogdanova', 'Owner: Silvie Bogdanova', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů — Firma — vlastník', 'legal', 'privacy_s1', 'text', 'Firma — vlastník', 40), -- from src/pages/Privacy.tsx:66
  ('privacy_s1_company_country', 'Country: Spain', 'Country: Spain', 'Zásady ochrany osobních údajů (GDPR) — 1. Správce údajů — Firma — země', 'legal', 'privacy_s1', 'text', 'Firma — země', 50), -- from src/pages/Privacy.tsx:67
  ('privacy_s10_title', '10. Confidentiality', '10. Confidentiality', 'Zásady ochrany osobních údajů (GDPR) — 10. Mlčenlivost — Nadpis sekce', 'legal', 'privacy_s10', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:179
  ('privacy_s10_p1', 'We are bound by confidentiality regarding personal data and our security measures. This obligation continues even after the end of any contractual relationship. Personal data will not be shared with third parties without your consent, unless required by law.', 'We are bound by confidentiality regarding personal data and our security measures. This obligation continues even after the end of any contractual relationship. Personal data will not be shared with third parties without your consent, unless required by law.', 'Zásady ochrany osobních údajů (GDPR) — 10. Mlčenlivost — Odstavec', 'legal', 'privacy_s10', 'textarea', 'Odstavec', 20), -- from src/pages/Privacy.tsx:181
  ('privacy_s2_title', '2. Contact Details', '2. Contact Details', 'Zásady ochrany osobních údajů (GDPR) — 2. Kontaktní údaje — Nadpis sekce', 'legal', 'privacy_s2', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:72
  ('privacy_s2_p1', 'If you wish to contact the controller regarding personal data processing, you may email us at:', 'If you wish to contact the controller regarding personal data processing, you may email us at:', 'Zásady ochrany osobních údajů (GDPR) — 2. Kontaktní údaje — Text — před e-mailem', 'legal', 'privacy_s2', 'textarea', 'Text — před e-mailem', 20), -- from src/pages/Privacy.tsx:74
  ('privacy_s3_title', '3. Controller''s Declaration', '3. Controller''s Declaration', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce — Nadpis sekce', 'legal', 'privacy_s3', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:80
  ('privacy_s3_intro', 'As the controller of your personal data, we declare that:', 'As the controller of your personal data, we declare that:', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce — Úvodní věta', 'legal', 'privacy_s3', 'text', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:82
  ('privacy_s3_li1', 'We process personal data only on a valid legal basis: performance of a contract, legitimate interest, legal obligation, or your consent.', 'We process personal data only on a valid legal basis: performance of a contract, legitimate interest, legal obligation, or your consent.', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce — Položka seznamu 1', 'legal', 'privacy_s3', 'textarea', 'Položka seznamu 1', 30), -- from src/pages/Privacy.tsx:85
  ('privacy_s3_li2', 'We fulfill our information obligations in accordance with Article 13 of GDPR.', 'We fulfill our information obligations in accordance with Article 13 of GDPR.', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce — Položka seznamu 2', 'legal', 'privacy_s3', 'text', 'Položka seznamu 2', 40), -- from src/pages/Privacy.tsx:86
  ('privacy_s3_li3', 'We enable and support the exercise of your rights under GDPR.', 'We enable and support the exercise of your rights under GDPR.', 'Zásady ochrany osobních údajů (GDPR) — 3. Prohlášení správce — Položka seznamu 3', 'legal', 'privacy_s3', 'text', 'Položka seznamu 3', 50), -- from src/pages/Privacy.tsx:87
  ('privacy_s4_title', '4. Scope of Personal Data Processed', '4. Scope of Personal Data Processed', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Nadpis sekce', 'legal', 'privacy_s4', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:92
  ('privacy_s4_intro', 'We process personal data only for the purposes, duration, and extent necessary to provide our services, which may include:', 'We process personal data only for the purposes, duration, and extent necessary to provide our services, which may include:', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Úvodní věta', 'legal', 'privacy_s4', 'textarea', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:94
  ('privacy_s4_li1', 'First and last name', 'First and last name', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 1', 'legal', 'privacy_s4', 'text', 'Položka seznamu 1', 30), -- from src/pages/Privacy.tsx:100
  ('privacy_s4_li2', 'Email address', 'Email address', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 2', 'legal', 'privacy_s4', 'text', 'Položka seznamu 2', 40), -- from src/pages/Privacy.tsx:101
  ('privacy_s4_li3', 'Phone number', 'Phone number', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 3', 'legal', 'privacy_s4', 'text', 'Položka seznamu 3', 50), -- from src/pages/Privacy.tsx:102
  ('privacy_s4_li4', 'Postal address', 'Postal address', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 4', 'legal', 'privacy_s4', 'text', 'Položka seznamu 4', 60), -- from src/pages/Privacy.tsx:103
  ('privacy_s4_li5', 'Billing details (company name, VAT number, bank details)', 'Billing details (company name, VAT number, bank details)', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 5', 'legal', 'privacy_s4', 'text', 'Položka seznamu 5', 70), -- from src/pages/Privacy.tsx:104
  ('privacy_s4_li6', 'Other information required depending on the service provided', 'Other information required depending on the service provided', 'Zásady ochrany osobních údajů (GDPR) — 4. Rozsah zpracovávaných osobních údajů — Položka seznamu 6', 'legal', 'privacy_s4', 'text', 'Položka seznamu 6', 80), -- from src/pages/Privacy.tsx:105
  ('privacy_s5_title', '5. Photos and Audio-Visual Recordings', '5. Photos and Audio-Visual Recordings', 'Zásady ochrany osobních údajů (GDPR) — 5. Fotografie a audiovizuální záznamy — Nadpis sekce', 'legal', 'privacy_s5', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:110
  ('privacy_s5_p1', 'During certain events, courses, or webinars, photographs or audio-visual recordings may be made. These materials may be used for promotional or educational purposes. Participants'' names are never published without explicit consent.', 'During certain events, courses, or webinars, photographs or audio-visual recordings may be made. These materials may be used for promotional or educational purposes. Participants'' names are never published without explicit consent.', 'Zásady ochrany osobních údajů (GDPR) — 5. Fotografie a audiovizuální záznamy — Odstavec', 'legal', 'privacy_s5', 'textarea', 'Odstavec', 20), -- from src/pages/Privacy.tsx:112
  ('privacy_s6_title', '6. Cookies', '6. Cookies', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies — Nadpis sekce', 'legal', 'privacy_s6', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:120
  ('privacy_s6_intro', 'When browsing our website, we may record your IP address, time spent on the site, and referring page.', 'When browsing our website, we may record your IP address, time spent on the site, and referring page.', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies — Úvodní věta', 'legal', 'privacy_s6', 'textarea', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:122
  ('privacy_s6_li1', 'Analytical cookies are processed based on our legitimate interest to improve our services.', 'Analytical cookies are processed based on our legitimate interest to improve our services.', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies — Položka seznamu 1', 'legal', 'privacy_s6', 'textarea', 'Položka seznamu 1', 30), -- from src/pages/Privacy.tsx:125
  ('privacy_s6_li2', 'Marketing cookies are processed only with your consent.', 'Marketing cookies are processed only with your consent.', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies — Položka seznamu 2', 'legal', 'privacy_s6', 'text', 'Položka seznamu 2', 40), -- from src/pages/Privacy.tsx:126
  ('privacy_s6_end', 'You can manage or disable cookies through your browser settings.', 'You can manage or disable cookies through your browser settings.', 'Zásady ochrany osobních údajů (GDPR) — 6. Cookies — Závěrečná věta', 'legal', 'privacy_s6', 'text', 'Závěrečná věta', 50), -- from src/pages/Privacy.tsx:129
  ('privacy_s7_title', '7. Data Security', '7. Data Security', 'Zásady ochrany osobních údajů (GDPR) — 7. Zabezpečení údajů — Nadpis sekce', 'legal', 'privacy_s7', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:134
  ('privacy_s7_p1', 'We use modern technical and organizational measures to protect personal data against misuse, damage, or loss. Our security measures are designed to match current technological standards.', 'We use modern technical and organizational measures to protect personal data against misuse, damage, or loss. Our security measures are designed to match current technological standards.', 'Zásady ochrany osobních údajů (GDPR) — 7. Zabezpečení údajů — Odstavec', 'legal', 'privacy_s7', 'textarea', 'Odstavec', 20), -- from src/pages/Privacy.tsx:136
  ('privacy_s8_title', '8. Transfer of Personal Data to Third Parties', '8. Transfer of Personal Data to Third Parties', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Nadpis sekce', 'legal', 'privacy_s8', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:144
  ('privacy_s8_intro', 'For certain processing operations, we rely on trusted processors who comply with GDPR, including:', 'For certain processing operations, we rely on trusted processors who comply with GDPR, including:', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Úvodní věta', 'legal', 'privacy_s8', 'textarea', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:146
  ('privacy_s8_li1', 'Stripe (payments)', 'Stripe (payments)', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Položka seznamu 1', 'legal', 'privacy_s8', 'text', 'Položka seznamu 1', 30), -- from src/pages/Privacy.tsx:149
  ('privacy_s8_li2', 'Email marketing platforms', 'Email marketing platforms', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Položka seznamu 2', 'legal', 'privacy_s8', 'text', 'Položka seznamu 2', 40), -- from src/pages/Privacy.tsx:150
  ('privacy_s8_li3', 'Website analytics providers', 'Website analytics providers', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Položka seznamu 3', 'legal', 'privacy_s8', 'text', 'Položka seznamu 3', 50), -- from src/pages/Privacy.tsx:151
  ('privacy_s8_end', 'Personal data may also be disclosed if required by law.', 'Personal data may also be disclosed if required by law.', 'Zásady ochrany osobních údajů (GDPR) — 8. Předávání osobních údajů třetím stranám — Závěrečná věta', 'legal', 'privacy_s8', 'text', 'Závěrečná věta', 60), -- from src/pages/Privacy.tsx:154
  ('privacy_s9_title', '9. Your Rights', '9. Your Rights', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Nadpis sekce', 'legal', 'privacy_s9', 'text', 'Nadpis sekce', 10), -- from src/pages/Privacy.tsx:159
  ('privacy_s9_intro', 'Under GDPR, you have the following rights:', 'Under GDPR, you have the following rights:', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Úvodní věta', 'legal', 'privacy_s9', 'text', 'Úvodní věta', 20), -- from src/pages/Privacy.tsx:161
  ('privacy_s9_li1', 'Access your personal data', 'Access your personal data', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 1', 'legal', 'privacy_s9', 'text', 'Položka seznamu 1', 30), -- from src/pages/Privacy.tsx:164
  ('privacy_s9_li2', 'Rectify inaccurate data', 'Rectify inaccurate data', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 2', 'legal', 'privacy_s9', 'text', 'Položka seznamu 2', 40), -- from src/pages/Privacy.tsx:165
  ('privacy_s9_li3', 'Request erasure ("right to be forgotten")', 'Request erasure ("right to be forgotten")', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 3', 'legal', 'privacy_s9', 'text', 'Položka seznamu 3', 50), -- from src/pages/Privacy.tsx:166
  ('privacy_s9_li4', 'Restrict processing', 'Restrict processing', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 4', 'legal', 'privacy_s9', 'text', 'Položka seznamu 4', 60), -- from src/pages/Privacy.tsx:167
  ('privacy_s9_li5', 'Data portability', 'Data portability', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 5', 'legal', 'privacy_s9', 'text', 'Položka seznamu 5', 70), -- from src/pages/Privacy.tsx:168
  ('privacy_s9_li6', 'Object to processing', 'Object to processing', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 6', 'legal', 'privacy_s9', 'text', 'Položka seznamu 6', 80), -- from src/pages/Privacy.tsx:169
  ('privacy_s9_li7', 'Withdraw consent at any time', 'Withdraw consent at any time', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Položka seznamu 7', 'legal', 'privacy_s9', 'text', 'Položka seznamu 7', 90), -- from src/pages/Privacy.tsx:170
  ('privacy_s9_end', 'To exercise your rights, contact us at:', 'To exercise your rights, contact us at:', 'Zásady ochrany osobních údajů (GDPR) — 9. Vaše práva — Text před e-mailem', 'legal', 'privacy_s9', 'text', 'Text před e-mailem', 100), -- from src/pages/Privacy.tsx:173
  ('terms_hero_badge', 'Legal', 'Legal', 'Obchodní podmínky — Úvodní hlavička — Text štítku nad nadpisem', 'legal', 'terms_hero', 'text', 'Text štítku nad nadpisem', 10), -- from src/pages/Terms.tsx:26
  ('terms_hero_title', 'General Terms and Conditions', 'General Terms and Conditions', 'Obchodní podmínky — Úvodní hlavička — Hlavní nadpis (H1)', 'legal', 'terms_hero', 'text', 'Hlavní nadpis (H1)', 20), -- from src/pages/Terms.tsx:31
  ('terms_hero_updated', 'Last updated: February 2026', 'Last updated: February 2026', 'Obchodní podmínky — Úvodní hlavička — Datum poslední aktualizace', 'legal', 'terms_hero', 'text', 'Datum poslední aktualizace', 30), -- from src/pages/Terms.tsx:35
  ('terms_intro_subtitle', 'for the Sale of Digital Products — Resilient Mind', 'for the Sale of Digital Products — Resilient Mind', 'Obchodní podmínky — Podnadpis — Podtitulek pod nadpisem', 'legal', 'terms_intro', 'text', 'Podtitulek pod nadpisem', 10), -- from src/pages/Terms.tsx:44
  ('terms_s1_title', '1. General Provisions', '1. General Provisions', 'Obchodní podmínky — 1. Obecná ustanovení — Nadpis sekce', 'legal', 'terms_s1', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:48
  ('terms_s1_p1', '1.1 These General Terms and Conditions ("Terms") apply to the sale of digital products ("Products") by the Seller:', '1.1 These General Terms and Conditions ("Terms") apply to the sale of digital products ("Products") by the Seller:', 'Obchodní podmínky — 1. Obecná ustanovení — Odstavec 1.1', 'legal', 'terms_s1', 'textarea', 'Odstavec 1.1', 20), -- from src/pages/Terms.tsx:50
  ('terms_s1_company_name', 'Resilient Mind', 'Resilient Mind', 'Obchodní podmínky — 1. Obecná ustanovení — Firma — název', 'legal', 'terms_s1', 'text', 'Firma — název', 30), -- from src/pages/Terms.tsx:56
  ('terms_s1_company_owner', 'Owner: Silvie Bogdanova', 'Owner: Silvie Bogdanova', 'Obchodní podmínky — 1. Obecná ustanovení — Firma — vlastník', 'legal', 'terms_s1', 'text', 'Firma — vlastník', 40), -- from src/pages/Terms.tsx:57
  ('terms_s1_company_website', 'Website: www.resilientmind.io', 'Website: www.resilientmind.io', 'Obchodní podmínky — 1. Obecná ustanovení — Firma — web', 'legal', 'terms_s1', 'text', 'Firma — web', 50), -- from src/pages/Terms.tsx:58
  ('terms_s1_company_country', 'Country: Spain', 'Country: Spain', 'Obchodní podmínky — 1. Obecná ustanovení — Firma — země', 'legal', 'terms_s1', 'text', 'Firma — země', 60), -- from src/pages/Terms.tsx:59
  ('terms_s1_p2', '1.2 These Terms define the rights and obligations of the Seller and the Buyer (also referred to as "Customer" or "Participant").', '1.2 These Terms define the rights and obligations of the Seller and the Buyer (also referred to as "Customer" or "Participant").', 'Obchodní podmínky — 1. Obecná ustanovení — Odstavec 1.2', 'legal', 'terms_s1', 'textarea', 'Odstavec 1.2', 70), -- from src/pages/Terms.tsx:62
  ('terms_s1_p3', '1.3 These Terms form an integral part of the purchase contract.', '1.3 These Terms form an integral part of the purchase contract.', 'Obchodní podmínky — 1. Obecná ustanovení — Odstavec 1.3', 'legal', 'terms_s1', 'text', 'Odstavec 1.3', 80), -- from src/pages/Terms.tsx:68
  ('terms_s1_p4', '1.4 If the contracting party is a consumer, relationships not governed by these Terms are subject to applicable consumer protection and civil law regulations.', '1.4 If the contracting party is a consumer, relationships not governed by these Terms are subject to applicable consumer protection and civil law regulations.', 'Obchodní podmínky — 1. Obecná ustanovení — Odstavec 1.4', 'legal', 'terms_s1', 'textarea', 'Odstavec 1.4', 90), -- from src/pages/Terms.tsx:71
  ('terms_s1_p5', '1.5 These Terms are published on the Seller''s website: www.resilientmind.io', '1.5 These Terms are published on the Seller''s website: www.resilientmind.io', 'Obchodní podmínky — 1. Obecná ustanovení — Odstavec 1.5', 'legal', 'terms_s1', 'text', 'Odstavec 1.5', 100), -- from src/pages/Terms.tsx:77
  ('terms_s10_title', '10. Personal Data Protection', '10. Personal Data Protection', 'Obchodní podmínky — 10. Ochrana osobních údajů — Nadpis sekce', 'legal', 'terms_s10', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:253
  ('terms_s10_p1_pre', '10.1 Personal data is processed in accordance with GDPR and the', '10.1 Personal data is processed in accordance with GDPR and the', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.1 — před odkazem na Zásady ochrany osobních údajů', 'legal', 'terms_s10', 'text', 'Odstavec 10.1 — před odkazem na Zásady ochrany osobních údajů', 20), -- from src/pages/Terms.tsx:255
  ('terms_s10_p1_link', 'Privacy Policy', 'Privacy Policy', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.1 — text odkazu', 'legal', 'terms_s10', 'text', 'Odstavec 10.1 — text odkazu', 30), -- from src/pages/Terms.tsx:256
  ('terms_s10_p2_pre', '10.2 Customers may request information, corrections, or deletion via', '10.2 Customers may request information, corrections, or deletion via', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.2 — před odkazem na e-mail', 'legal', 'terms_s10', 'text', 'Odstavec 10.2 — před odkazem na e-mail', 40), -- from src/pages/Terms.tsx:259
  ('terms_s10_p3', '10.3 Data may be collected automatically when visiting the website.', '10.3 Data may be collected automatically when visiting the website.', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.3', 'legal', 'terms_s10', 'text', 'Odstavec 10.3', 50), -- from src/pages/Terms.tsx:263
  ('terms_s10_p4', '10.4 Marketing communications are voluntary and can be unsubscribed at any time.', '10.4 Marketing communications are voluntary and can be unsubscribed at any time.', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.4', 'legal', 'terms_s10', 'text', 'Odstavec 10.4', 60), -- from src/pages/Terms.tsx:266
  ('terms_s10_p5', '10.5 By submitting the order form, the Customer consents to personal data processing for marketing purposes until consent is withdrawn.', '10.5 By submitting the order form, the Customer consents to personal data processing for marketing purposes until consent is withdrawn.', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.5', 'legal', 'terms_s10', 'textarea', 'Odstavec 10.5', 70), -- from src/pages/Terms.tsx:269
  ('terms_s10_p6', '10.6 Cookies may be used to improve website functionality.', '10.6 Cookies may be used to improve website functionality.', 'Obchodní podmínky — 10. Ochrana osobních údajů — Odstavec 10.6', 'legal', 'terms_s10', 'text', 'Odstavec 10.6', 80), -- from src/pages/Terms.tsx:275
  ('terms_s11_title', '11. Final Provisions', '11. Final Provisions', 'Obchodní podmínky — 11. Závěrečná ustanovení — Nadpis sekce', 'legal', 'terms_s11', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:280
  ('terms_s11_p1', '11.1 These Terms are published on the Seller''s website.', '11.1 These Terms are published on the Seller''s website.', 'Obchodní podmínky — 11. Závěrečná ustanovení — Odstavec 11.1', 'legal', 'terms_s11', 'text', 'Odstavec 11.1', 20), -- from src/pages/Terms.tsx:282
  ('terms_s11_p2_pre', '11.2 Complaints may be submitted via email to', '11.2 Complaints may be submitted via email to', 'Obchodní podmínky — 11. Závěrečná ustanovení — Odstavec 11.2 — před odkazem na e-mail', 'legal', 'terms_s11', 'text', 'Odstavec 11.2 — před odkazem na e-mail', 30), -- from src/pages/Terms.tsx:285
  ('terms_s11_p3', '11.3 Any disputes shall be resolved by courts of the Seller''s registered country unless mandatory consumer laws apply.', '11.3 Any disputes shall be resolved by courts of the Seller''s registered country unless mandatory consumer laws apply.', 'Obchodní podmínky — 11. Závěrečná ustanovení — Odstavec 11.3', 'legal', 'terms_s11', 'textarea', 'Odstavec 11.3', 40), -- from src/pages/Terms.tsx:289
  ('terms_s11_p4', '11.4 The Seller reserves the right to amend these Terms.', '11.4 The Seller reserves the right to amend these Terms.', 'Obchodní podmínky — 11. Závěrečná ustanovení — Odstavec 11.4', 'legal', 'terms_s11', 'text', 'Odstavec 11.4', 50), -- from src/pages/Terms.tsx:295
  ('terms_s11_p5', '11.5 The valid and effective version of these Terms is effective from February 2026.', '11.5 The valid and effective version of these Terms is effective from February 2026.', 'Obchodní podmínky — 11. Závěrečná ustanovení — Odstavec 11.5', 'legal', 'terms_s11', 'text', 'Odstavec 11.5', 60), -- from src/pages/Terms.tsx:298
  ('terms_s2_title', '2. Order and Conclusion of Contract', '2. Order and Conclusion of Contract', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Nadpis sekce', 'legal', 'terms_s2', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:82
  ('terms_s2_p1', '2.1 The Product description, main features, and price (including applicable taxes) are stated on the Seller''s website. The offer remains valid while displayed on the website.', '2.1 The Product description, main features, and price (including applicable taxes) are stated on the Seller''s website. The offer remains valid while displayed on the website.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.1', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.1', 20), -- from src/pages/Terms.tsx:84
  ('terms_s2_p2', '2.2 The order form contains Customer information, selected Product, price (including taxes and fees), payment method, and delivery method. Costs incurred when using remote communication means are borne by the Customer.', '2.2 The order form contains Customer information, selected Product, price (including taxes and fees), payment method, and delivery method. Costs incurred when using remote communication means are borne by the Customer.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.2', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.2', 30), -- from src/pages/Terms.tsx:90
  ('terms_s2_p3', '2.3 The contract arises when the Customer submits the order by clicking the "Submit" button. By submitting the order, the Customer confirms acceptance of these Terms. The Seller does not accept offers with amendments or deviations.', '2.3 The contract arises when the Customer submits the order by clicking the "Submit" button. By submitting the order, the Customer confirms acceptance of these Terms. The Seller does not accept offers with amendments or deviations.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.3', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.3', 40), -- from src/pages/Terms.tsx:96
  ('terms_s2_p4', '2.4 The Customer may review and correct entered data before submitting the order. Submitted data is considered accurate.', '2.4 The Customer may review and correct entered data before submitting the order. Submitted data is considered accurate.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.4', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.4', 50), -- from src/pages/Terms.tsx:102
  ('terms_s2_p5', '2.5 The Customer agrees to use remote communication means for concluding the contract.', '2.5 The Customer agrees to use remote communication means for concluding the contract.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.5', 'legal', 'terms_s2', 'text', 'Odstavec 2.5', 60), -- from src/pages/Terms.tsx:108
  ('terms_s2_p6', '2.6 The contract is concluded in English and stored electronically by the Seller for three (3) years.', '2.6 The contract is concluded in English and stored electronically by the Seller for three (3) years.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.6', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.6', 70), -- from src/pages/Terms.tsx:111
  ('terms_s2_p7', '2.7 The Seller undertakes to deliver the ordered Product, and the Customer undertakes to pay the purchase price.', '2.7 The Seller undertakes to deliver the ordered Product, and the Customer undertakes to pay the purchase price.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.7', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.7', 80), -- from src/pages/Terms.tsx:117
  ('terms_s2_p8', '2.8 The Customer acknowledges that proper use of digital Products requires up-to-date software and internet browsers.', '2.8 The Customer acknowledges that proper use of digital Products requires up-to-date software and internet browsers.', 'Obchodní podmínky — 2. Objednávka a uzavření smlouvy — Odstavec 2.8', 'legal', 'terms_s2', 'textarea', 'Odstavec 2.8', 90), -- from src/pages/Terms.tsx:123
  ('terms_s3_title', '3. Price and Payment Terms', '3. Price and Payment Terms', 'Obchodní podmínky — 3. Cena a platební podmínky — Nadpis sekce', 'legal', 'terms_s3', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:131
  ('terms_s3_p1', '3.1 The Product price is listed on the Seller''s website and in the order form.', '3.1 The Product price is listed on the Seller''s website and in the order form.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.1', 'legal', 'terms_s3', 'text', 'Odstavec 3.1', 20), -- from src/pages/Terms.tsx:133
  ('terms_s3_p2', '3.2 The Seller issues an invoice as proof of purchase. The Seller is not a VAT payer unless stated otherwise.', '3.2 The Seller issues an invoice as proof of purchase. The Seller is not a VAT payer unless stated otherwise.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.2', 'legal', 'terms_s3', 'textarea', 'Odstavec 3.2', 30), -- from src/pages/Terms.tsx:136
  ('terms_s3_p3', '3.3 Payment is cashless according to the order and invoice.', '3.3 Payment is cashless according to the order and invoice.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.3', 'legal', 'terms_s3', 'text', 'Odstavec 3.3', 40), -- from src/pages/Terms.tsx:142
  ('terms_s3_p4', '3.4 Payments may be processed via secure third-party gateways, such as Stripe.', '3.4 Payments may be processed via secure third-party gateways, such as Stripe.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.4', 'legal', 'terms_s3', 'text', 'Odstavec 3.4', 50), -- from src/pages/Terms.tsx:145
  ('terms_s3_p5', '3.5 Available payment methods are listed in the order form.', '3.5 Available payment methods are listed in the order form.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.5', 'legal', 'terms_s3', 'text', 'Odstavec 3.5', 60), -- from src/pages/Terms.tsx:148
  ('terms_s3_p6', '3.6 Payment is made as a one-time transaction unless otherwise stated.', '3.6 Payment is made as a one-time transaction unless otherwise stated.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.6', 'legal', 'terms_s3', 'text', 'Odstavec 3.6', 70), -- from src/pages/Terms.tsx:151
  ('terms_s3_p7', '3.7 The Customer must provide correct payment identification details.', '3.7 The Customer must provide correct payment identification details.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.7', 'legal', 'terms_s3', 'text', 'Odstavec 3.7', 80), -- from src/pages/Terms.tsx:154
  ('terms_s3_p8', '3.8 The purchase price is due within five (5) days of invoice issuance.', '3.8 The purchase price is due within five (5) days of invoice issuance.', 'Obchodní podmínky — 3. Cena a platební podmínky — Odstavec 3.8', 'legal', 'terms_s3', 'text', 'Odstavec 3.8', 90), -- from src/pages/Terms.tsx:157
  ('terms_s4_title', '4. Delivery Terms', '4. Delivery Terms', 'Obchodní podmínky — 4. Dodací podmínky — Nadpis sekce', 'legal', 'terms_s4', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:162
  ('terms_s4_p1', '4.1 Delivery of digital Products consists of sending access credentials or a URL link to the Customer''s email address.', '4.1 Delivery of digital Products consists of sending access credentials or a URL link to the Customer''s email address.', 'Obchodní podmínky — 4. Dodací podmínky — Odstavec 4.1', 'legal', 'terms_s4', 'textarea', 'Odstavec 4.1', 20), -- from src/pages/Terms.tsx:164
  ('terms_s4_p2', '4.2 Access is granted after full payment, no later than three (3) days unless stated otherwise.', '4.2 Access is granted after full payment, no later than three (3) days unless stated otherwise.', 'Obchodní podmínky — 4. Dodací podmínky — Odstavec 4.2', 'legal', 'terms_s4', 'textarea', 'Odstavec 4.2', 30), -- from src/pages/Terms.tsx:170
  ('terms_s5_title', '5. Copyright and Access Security', '5. Copyright and Access Security', 'Obchodní podmínky — 5. Autorská práva a zabezpečení přístupu — Nadpis sekce', 'legal', 'terms_s5', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:175
  ('terms_s5_p1', '5.1 Access credentials are for personal use only. The Customer must keep login details confidential.', '5.1 Access credentials are for personal use only. The Customer must keep login details confidential.', 'Obchodní podmínky — 5. Autorská práva a zabezpečení přístupu — Odstavec 5.1', 'legal', 'terms_s5', 'textarea', 'Odstavec 5.1', 20), -- from src/pages/Terms.tsx:177
  ('terms_s5_p2', '5.2 All Products and content are protected by copyright law. Unauthorized distribution is prohibited.', '5.2 All Products and content are protected by copyright law. Unauthorized distribution is prohibited.', 'Obchodní podmínky — 5. Autorská práva a zabezpečení přístupu — Odstavec 5.2', 'legal', 'terms_s5', 'textarea', 'Odstavec 5.2', 30), -- from src/pages/Terms.tsx:183
  ('terms_s6_title', '6. Withdrawal from Contract', '6. Withdrawal from Contract', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Nadpis sekce', 'legal', 'terms_s6', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:188
  ('terms_s6_p1_label', '6.1 Consumer withdrawal', '6.1 Consumer withdrawal', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Popisek 6.1', 'legal', 'terms_s6', 'text', 'Popisek 6.1', 20), -- from src/pages/Terms.tsx:190
  ('terms_s6_p1', 'Consumers may withdraw from the contract within fourteen (14) days of delivery without giving reasons.', 'Consumers may withdraw from the contract within fourteen (14) days of delivery without giving reasons.', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Text 6.1', 'legal', 'terms_s6', 'textarea', 'Text 6.1', 30), -- from src/pages/Terms.tsx:191
  ('terms_s6_p2_label', '6.2 Withdrawal procedure', '6.2 Withdrawal procedure', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Popisek 6.2', 'legal', 'terms_s6', 'text', 'Popisek 6.2', 40), -- from src/pages/Terms.tsx:197
  ('terms_s6_p2_pre', 'Notice of withdrawal must be sent by email to', 'Notice of withdrawal must be sent by email to', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Text 6.2 — před odkazem na e-mail', 'legal', 'terms_s6', 'text', 'Text 6.2 — před odkazem na e-mail', 50), -- from src/pages/Terms.tsx:198
  ('terms_s6_p2_post', 'Refunds are processed within 14 days.', 'Refunds are processed within 14 days.', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Text 6.2 — za odkazem na e-mail', 'legal', 'terms_s6', 'text', 'Text 6.2 — za odkazem na e-mail', 60), -- from src/pages/Terms.tsx:200
  ('terms_s6_p3_label', '6.3 Seller withdrawal', '6.3 Seller withdrawal', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Popisek 6.3', 'legal', 'terms_s6', 'text', 'Popisek 6.3', 70), -- from src/pages/Terms.tsx:203
  ('terms_s6_p3', 'The Seller may withdraw from the contract if the Customer materially breaches obligations, including non-payment or copyright infringement.', 'The Seller may withdraw from the contract if the Customer materially breaches obligations, including non-payment or copyright infringement.', 'Obchodní podmínky — 6. Odstoupení od smlouvy — Text 6.3', 'legal', 'terms_s6', 'textarea', 'Text 6.3', 80), -- from src/pages/Terms.tsx:204
  ('terms_s7_title', '7. Defective Performance', '7. Defective Performance', 'Obchodní podmínky — 7. Vadné plnění — Nadpis sekce', 'legal', 'terms_s7', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:212
  ('terms_s7_p1', '7.1 Rights arising from defective performance are governed by applicable law.', '7.1 Rights arising from defective performance are governed by applicable law.', 'Obchodní podmínky — 7. Vadné plnění — Odstavec 7.1', 'legal', 'terms_s7', 'text', 'Odstavec 7.1', 20), -- from src/pages/Terms.tsx:214
  ('terms_s7_p2', '7.2 The Seller is not liable for issues caused by insufficient technical conditions or improper use.', '7.2 The Seller is not liable for issues caused by insufficient technical conditions or improper use.', 'Obchodní podmínky — 7. Vadné plnění — Odstavec 7.2', 'legal', 'terms_s7', 'textarea', 'Odstavec 7.2', 30), -- from src/pages/Terms.tsx:217
  ('terms_s8_title', '8. Money-Back Guarantee', '8. Money-Back Guarantee', 'Obchodní podmínky — 8. Záruka vrácení peněz — Nadpis sekce', 'legal', 'terms_s8', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:225
  ('terms_s8_p1', '8.1 Selected Products may include a satisfaction guarantee under conditions stated on the Product page.', '8.1 Selected Products may include a satisfaction guarantee under conditions stated on the Product page.', 'Obchodní podmínky — 8. Záruka vrácení peněz — Odstavec 8.1', 'legal', 'terms_s8', 'textarea', 'Odstavec 8.1', 20), -- from src/pages/Terms.tsx:227
  ('terms_s8_p2_pre', '8.2 Withdrawal requests must be sent to', '8.2 Withdrawal requests must be sent to', 'Obchodní podmínky — 8. Záruka vrácení peněz — Odstavec 8.2 — před odkazem na e-mail', 'legal', 'terms_s8', 'text', 'Odstavec 8.2 — před odkazem na e-mail', 30), -- from src/pages/Terms.tsx:233
  ('terms_s8_p2_post', 'with proof of purchase.', 'with proof of purchase.', 'Obchodní podmínky — 8. Záruka vrácení peněz — Odstavec 8.2 — za odkazem na e-mail', 'legal', 'terms_s8', 'text', 'Odstavec 8.2 — za odkazem na e-mail', 40), -- from src/pages/Terms.tsx:235
  ('terms_s8_p3', '8.3 Refunds are processed within 14 days, and access will be deactivated.', '8.3 Refunds are processed within 14 days, and access will be deactivated.', 'Obchodní podmínky — 8. Záruka vrácení peněz — Odstavec 8.3', 'legal', 'terms_s8', 'text', 'Odstavec 8.3', 50), -- from src/pages/Terms.tsx:238
  ('terms_s9_title', '9. Disclaimer of Liability', '9. Disclaimer of Liability', 'Obchodní podmínky — 9. Vyloučení odpovědnosti — Nadpis sekce', 'legal', 'terms_s9', 'text', 'Nadpis sekce', 10), -- from src/pages/Terms.tsx:243
  ('terms_s9_p1', '9.1 Products are provided for educational and informational purposes only and do not replace professional medical or psychological care.', '9.1 Products are provided for educational and informational purposes only and do not replace professional medical or psychological care.', 'Obchodní podmínky — 9. Vyloučení odpovědnosti — Odstavec 9.1', 'legal', 'terms_s9', 'textarea', 'Odstavec 9.1', 20) -- from src/pages/Terms.tsx:245
ON CONFLICT (key) DO NOTHING;
