-- Auto-generated seed for CMS phase 2 (docs/cms-final-seed.md).
-- FreeGuide.tsx.
-- value/default_value copied verbatim from the t("key", "fallback") call in the source file
-- named in each row's trailing comment (TypeScript compiler API, not regex -- see
-- scripts/cms-seed.mjs). page/section/field_type/label/sort_order come from the metadata the
-- CMS agents collected while wiring this page (docs/cms-keys-*.json), not guessed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have edited through
-- the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('freeguide_form_title', 'Download Your Free Practice Kit', 'Download Your Free Practice Kit', 'Formulář pro stažení — Nadpis formuláře', 'free-guide', 'formular', 'text', 'Nadpis formuláře', 140), -- from src/pages/FreeGuide.tsx:212
  ('freeguide_form_subtitle', 'Get instant access to both workbooks + the guided EFT video', 'Get instant access to both workbooks + the guided EFT video', 'Formulář pro stažení — Podnadpis formuláře', 'free-guide', 'formular', 'text', 'Podnadpis formuláře', 150), -- from src/pages/FreeGuide.tsx:215
  ('freeguide_form_name_label', 'Your Name', 'Your Name', 'Formulář pro stažení — Popisek pole Jméno', 'free-guide', 'formular', 'text', 'Popisek pole Jméno', 160), -- from src/pages/FreeGuide.tsx:220
  ('freeguide_form_name_placeholder', 'Jane Doe', 'Jane Doe', 'Formulář pro stažení — Placeholder pole Jméno', 'free-guide', 'formular', 'text', 'Placeholder pole Jméno', 170), -- from src/pages/FreeGuide.tsx:224
  ('freeguide_form_email_label', 'Email Address', 'Email Address', 'Formulář pro stažení — Popisek pole E-mail', 'free-guide', 'formular', 'text', 'Popisek pole E-mail', 180), -- from src/pages/FreeGuide.tsx:233
  ('freeguide_form_email_placeholder', 'you@example.com', 'you@example.com', 'Formulář pro stažení — Placeholder pole E-mail', 'free-guide', 'formular', 'text', 'Placeholder pole E-mail', 190), -- from src/pages/FreeGuide.tsx:237
  ('freeguide_form_agree_label', 'I''d like to receive resilience tips and updates (optional)', 'I''d like to receive resilience tips and updates (optional)', 'Formulář pro stažení — Text u zaškrtávacího políčka (souhlas s odběrem)', 'free-guide', 'formular', 'text', 'Text u zaškrtávacího políčka (souhlas s odběrem)', 200), -- from src/pages/FreeGuide.tsx:255
  ('freeguide_form_submit_label', 'Get My Free 7-Day Practice Kit', 'Get My Free 7-Day Practice Kit', 'Formulář pro stažení — Text tlačítka Odeslat', 'free-guide', 'formular', 'text', 'Text tlačítka Odeslat', 210), -- from src/pages/FreeGuide.tsx:272
  ('freeguide_form_submit_loading', 'Sending...', 'Sending...', 'Formulář pro stažení — Text tlačítka během odesílání', 'free-guide', 'formular', 'text', 'Text tlačítka během odesílání', 220), -- from src/pages/FreeGuide.tsx:267
  ('freeguide_form_badge_pdfs', '2 PDF Workbooks', '2 PDF Workbooks', 'Formulář pro stažení — Odznak – počet PDF workbooků', 'free-guide', 'formular', 'text', 'Odznak – počet PDF workbooků', 230), -- from src/pages/FreeGuide.tsx:279
  ('freeguide_form_badge_video', 'Guided Video', 'Guided Video', 'Formulář pro stažení — Odznak – video s návodem', 'free-guide', 'formular', 'text', 'Odznak – video s návodem', 240), -- from src/pages/FreeGuide.tsx:282
  ('freeguide_form_badge_nospam', 'No spam', 'No spam', 'Formulář pro stažení — Odznak – bez spamu', 'free-guide', 'formular', 'text', 'Odznak – bez spamu', 250), -- from src/pages/FreeGuide.tsx:285
  ('freeguide_form_spam_notice_title', '📧 Important: Check your Promotions or Spam folder', '📧 Important: Check your Promotions or Spam folder', 'Formulář pro stažení — Upozornění na spam – nadpis', 'free-guide', 'formular', 'text', 'Upozornění na spam – nadpis', 260), -- from src/pages/FreeGuide.tsx:291
  ('freeguide_form_spam_notice_text_pre', 'Add', 'Add', 'Formulář pro stažení — Upozornění na spam – text před e-mailem', 'free-guide', 'formular', 'text', 'Upozornění na spam – text před e-mailem', 270), -- from src/pages/FreeGuide.tsx:294
  ('freeguide_form_spam_notice_email', 'contact@resilientmind.io', 'contact@resilientmind.io', 'Formulář pro stažení — Upozornění na spam – zvýrazněný e-mail', 'free-guide', 'formular', 'text', 'Upozornění na spam – zvýrazněný e-mail', 280), -- from src/pages/FreeGuide.tsx:294
  ('freeguide_form_spam_notice_text_post', 'to your contacts so you don''t miss your free practice materials.', 'to your contacts so you don''t miss your free practice materials.', 'Formulář pro stažení — Upozornění na spam – text za e-mailem', 'free-guide', 'formular', 'text', 'Upozornění na spam – text za e-mailem', 290), -- from src/pages/FreeGuide.tsx:294
  ('freeguide_form_legal_pre', 'By signing up, you agree to our', 'By signing up, you agree to our', 'Formulář pro stažení — Souhlas s podmínkami – text před odkazy', 'free-guide', 'formular', 'text', 'Souhlas s podmínkami – text před odkazy', 300), -- from src/pages/FreeGuide.tsx:299
  ('freeguide_form_legal_terms', 'Terms', 'Terms', 'Formulář pro stažení — Souhlas s podmínkami – odkaz "Terms"', 'free-guide', 'formular', 'text', 'Souhlas s podmínkami – odkaz "Terms"', 310), -- from src/pages/FreeGuide.tsx:300
  ('freeguide_form_legal_and', 'and', 'and', 'Formulář pro stažení — Souhlas s podmínkami – spojka "and"', 'free-guide', 'formular', 'text', 'Souhlas s podmínkami – spojka "and"', 320), -- from src/pages/FreeGuide.tsx:301
  ('freeguide_form_legal_privacy', 'Privacy Policy', 'Privacy Policy', 'Formulář pro stažení — Souhlas s podmínkami – odkaz "Privacy Policy"', 'free-guide', 'formular', 'text', 'Souhlas s podmínkami – odkaz "Privacy Policy"', 330), -- from src/pages/FreeGuide.tsx:302
  ('freeguide_hero_title_line1', '3 Tools to Shift Your Energy:', '3 Tools to Shift Your Energy:', 'Úvodní obrazovka — Nadpis, první řádek', 'free-guide', 'hero', 'text', 'Nadpis, první řádek', 20), -- from src/pages/FreeGuide.tsx:145
  ('freeguide_hero_title_line2', '7 Days to Calm, Clarity & Resilience Overseas', '7 Days to Calm, Clarity & Resilience Overseas', 'Úvodní obrazovka — Nadpis, druhý řádek (zvýrazněný)', 'free-guide', 'hero', 'text', 'Nadpis, druhý řádek (zvýrazněný)', 30), -- from src/pages/FreeGuide.tsx:146
  ('freeguide_hero_subtitle', 'Practical daily exercises to release stress, calm your nervous system, and regain focus — even during challenging times abroad.', 'Practical daily exercises to release stress, calm your nervous system, and regain focus — even during challenging times abroad.', 'Úvodní obrazovka — Podnadpis pod hlavním nadpisem', 'free-guide', 'hero', 'textarea', 'Podnadpis pod hlavním nadpisem', 40), -- from src/pages/FreeGuide.tsx:149
  ('freeguide_back_link', 'Back to home', 'Back to home', 'Navigace — Odkaz zpět na hlavní stránku', 'free-guide', 'navigace', 'text', 'Odkaz zpět na hlavní stránku', 10), -- from src/pages/FreeGuide.tsx:124
  ('freeguide_included_title', 'Your Free 7-Day Practice Includes', 'Your Free 7-Day Practice Includes', 'Co balíček obsahuje — Nadpis sekce', 'free-guide', 'obsah_baliku', 'text', 'Nadpis sekce', 50), -- from src/pages/FreeGuide.tsx:157
  ('freeguide_included_1_title', '🌅 Morning Gratitude Workbook', '🌅 Morning Gratitude Workbook', 'Co balíček obsahuje — Bod 1 – název (ranní workbook)', 'free-guide', 'obsah_baliku', 'text', 'Bod 1 – název (ranní workbook)', 60), -- from src/pages/FreeGuide.tsx:164
  ('freeguide_included_1_description', 'Start your day noticing small wins and strengths. Feel calmer, more grounded, and ready to face the challenges of a new country.', 'Start your day noticing small wins and strengths. Feel calmer, more grounded, and ready to face the challenges of a new country.', 'Co balíček obsahuje — Bod 1 – popis', 'free-guide', 'obsah_baliku', 'textarea', 'Bod 1 – popis', 70), -- from src/pages/FreeGuide.tsx:166
  ('freeguide_included_2_title', '🌤 Midday EFT Tapping Video + Workbook', '🌤 Midday EFT Tapping Video + Workbook', 'Co balíček obsahuje — Bod 2 – název (video + EFT workbook)', 'free-guide', 'obsah_baliku', 'text', 'Bod 2 – název (video + EFT workbook)', 80), -- from src/pages/FreeGuide.tsx:175
  ('freeguide_included_2_description', 'Release stress, anxiety, and tension from language barriers, job uncertainty, or feeling out of place. Calm your nervous system and regain focus.', 'Release stress, anxiety, and tension from language barriers, job uncertainty, or feeling out of place. Calm your nervous system and regain focus.', 'Co balíček obsahuje — Bod 2 – popis', 'free-guide', 'obsah_baliku', 'textarea', 'Bod 2 – popis', 90), -- from src/pages/FreeGuide.tsx:177
  ('freeguide_included_3_title', '🌙 Evening Reflection', '🌙 Evening Reflection', 'Co balíček obsahuje — Bod 3 – název (večerní reflexe)', 'free-guide', 'obsah_baliku', 'text', 'Bod 3 – název (večerní reflexe)', 100), -- from src/pages/FreeGuide.tsx:186
  ('freeguide_included_3_description', 'Pause, reflect, and gently reframe your thoughts. End the day with clarity and a calmer mindset — ready to rest and recharge.', 'Pause, reflect, and gently reframe your thoughts. End the day with clarity and a calmer mindset — ready to rest and recharge.', 'Co balíček obsahuje — Bod 3 – popis', 'free-guide', 'obsah_baliku', 'textarea', 'Bod 3 – popis', 110), -- from src/pages/FreeGuide.tsx:188
  ('freeguide_social_quote', '"In just 30 minutes a day, you''ll notice your energy shifting, your nervous system relaxing, and your mind becoming clearer."', '"In just 30 minutes a day, you''ll notice your energy shifting, your nervous system relaxing, and your mind becoming clearer."', 'Reference / citát — Citát v uvozovkách', 'free-guide', 'reference', 'textarea', 'Citát v uvozovkách', 120), -- from src/pages/FreeGuide.tsx:200
  ('freeguide_social_note', 'No perfection, no pressure — just simple, realistic tools for expats who want to feel stronger and more in control.', 'No perfection, no pressure — just simple, realistic tools for expats who want to feel stronger and more in control.', 'Reference / citát — Doplňující poznámka pod citátem', 'free-guide', 'reference', 'textarea', 'Doplňující poznámka pod citátem', 130), -- from src/pages/FreeGuide.tsx:203
  ('freeguide_upsell_text_pre', 'Curious to go deeper? This is just the beginning of your', 'Curious to go deeper? This is just the beginning of your', 'Doplňkový text pod formulářem — Text před názvem značky', 'free-guide', 'upsell', 'textarea', 'Text před názvem značky', 340), -- from src/pages/FreeGuide.tsx:311
  ('freeguide_upsell_brand', 'Resilient Mind', 'Resilient Mind', 'Doplňkový text pod formulářem — Zvýrazněný název značky', 'free-guide', 'upsell', 'text', 'Zvýrazněný název značky', 350), -- from src/pages/FreeGuide.tsx:311
  ('freeguide_upsell_text_post', 'journey — designed to show you the kind of transformation possible when you consistently care for your nervous system, mindset, and self-awareness.', 'journey — designed to show you the kind of transformation possible when you consistently care for your nervous system, mindset, and self-awareness.', 'Doplňkový text pod formulářem — Text za názvem značky', 'free-guide', 'upsell', 'textarea', 'Text za názvem značky', 360) -- from src/pages/FreeGuide.tsx:311
ON CONFLICT (key) DO NOTHING;
