-- CMS SEO seed: meta title/description/keywords for every public page's
-- <SEO> component (src/components/SEO.tsx), the last piece of the CMS
-- rollout (docs/cms-seo.md). These texts are not visible on the page itself
-- -- they only feed <title>, <meta name="description">, <meta name="keywords">
-- and the Open Graph/Twitter tags react-helmet-async renders into <head>.
-- value/default_value copied verbatim from the existing title/description
-- string in the source file named in each row's trailing comment.
-- pricing_seo_title_prefix/suffix and pricing_seo_description_prefix/middle/
-- suffix are split around the live membership prices (Pricing.tsx interpolates
-- basicMonthlyPrice/basic_yearly price from useMembershipTiers) so the prices
-- stay dynamic and are never hardcoded into a CMS field -- same reasoning as
-- checkout_pay_button_prefix in Checkout.tsx. blog_post_seo_title_suffix and
-- workshop_post_seo_title_suffix are the only static part of those two pages'
-- titles -- the rest of the title/description comes from the blog post /
-- workshop row itself and has no fixed fallback to seed.
-- ON CONFLICT (key) DO NOTHING: production already has rows a client may have
-- edited through the admin -- this migration must never overwrite them.

INSERT INTO public.cms_content (key, value, default_value, description, page, section, field_type, label, sort_order) VALUES
  ('homepage_seo_title', 'Resilient Mind — Transform Uncertainty Into Your Greatest Strength | Support for Expats', 'Resilient Mind — Transform Uncertainty Into Your Greatest Strength | Support for Expats', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'homepage', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/Index.tsx:18
  ('homepage_seo_description', 'Build inner strength through art expressive therapy. Monthly video lessons, workbooks & consultations for expatriates navigating life abroad.', 'Build inner strength through art expressive therapy. Monthly video lessons, workbooks & consultations for expatriates navigating life abroad.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'homepage', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Index.tsx:19
  ('about_seo_title', 'About Silvie Bogdanova — Art Expressive Therapist for Expatriates | Resilient Mind', 'About Silvie Bogdanova — Art Expressive Therapist for Expatriates | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'about', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/About.tsx:26
  ('about_seo_description', 'Meet Silvie Bogdanova, art expressive therapist helping expatriates build resilience and navigate life transitions abroad.', 'Meet Silvie Bogdanova, art expressive therapist helping expatriates build resilience and navigate life transitions abroad.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'about', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/About.tsx:27
  ('blog_seo_title', 'Blog — Resilience Tips for Expatriates | Resilient Mind', 'Blog — Resilience Tips for Expatriates | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'blog', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/Blog.tsx:81
  ('blog_seo_description', 'Read articles on building resilience, managing expat stress, art therapy techniques and thriving while living abroad.', 'Read articles on building resilience, managing expat stress, art therapy techniques and thriving while living abroad.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'blog', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Blog.tsx:82
  ('blog_post_seo_title_suffix', 'Resilient Mind Blog', 'Resilient Mind Blog', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky — text za názvem článku ("Název článku | ...")', 'blog-post', 'seo', 'text', 'Titulek stránky — text za názvem článku ("Název článku | ...")', 10), -- from src/pages/BlogPost.tsx:103
  ('booking_seo_title', 'Book a Session — Individual Consultations €107/hour | Resilient Mind', 'Book a Session — Individual Consultations €107/hour | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'booking', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/Booking.tsx:380
  ('booking_seo_description', 'Schedule a free discovery call or book an individual art expressive therapy session with Silvie Bogdanova. Online consultations from €107/hour.', 'Schedule a free discovery call or book an individual art expressive therapy session with Silvie Bogdanova. Online consultations from €107/hour.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'booking', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Booking.tsx:381
  ('booking_success_seo_title', 'Booking Confirmed | Resilient Mind', 'Booking Confirmed | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'booking-success', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/BookingSuccess.tsx:127
  ('booking_success_seo_description', 'Your booking has been confirmed.', 'Your booking has been confirmed.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'booking-success', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/BookingSuccess.tsx:128
  ('cookies_seo_title', 'Cookies Policy | Resilient Mind', 'Cookies Policy | Resilient Mind', 'Zásady používání cookies — Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'legal', 'cookies_seo', 'text', 'Titulek stránky', 10), -- from src/pages/Cookies.tsx:14
  ('cookies_seo_description', 'Learn how Resilient Mind uses cookies and similar technologies on our website, and how you can manage your preferences.', 'Learn how Resilient Mind uses cookies and similar technologies on our website, and how you can manage your preferences.', 'Zásady používání cookies — Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'legal', 'cookies_seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Cookies.tsx:15
  ('endometriosis_seo_title', 'Endometriosis Management Hub for Expats Living Abroad | Resilient Mind', 'Endometriosis Management Hub for Expats Living Abroad | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'endometriosis', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/EndometriosisHub.tsx:16
  ('endometriosis_seo_description', 'Support module for women managing endometriosis and chronic pain while living abroad. Creative techniques for daily resilience.', 'Support module for women managing endometriosis and chronic pain while living abroad. Creative techniques for daily resilience.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'endometriosis', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/EndometriosisHub.tsx:17
  ('free_guide_seo_title', 'Free 7-Day Practice Kit — Calm, Clarity & Resilience Overseas | Resilient Mind', 'Free 7-Day Practice Kit — Calm, Clarity & Resilience Overseas | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'free-guide', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/FreeGuide.tsx:100
  ('free_guide_seo_description', 'Download a free 7-day EFT practice kit with workbooks and guided exercises. Build calm and clarity as an expatriate.', 'Download a free 7-day EFT practice kit with workbooks and guided exercises. Build calm and clarity as an expatriate.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'free-guide', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/FreeGuide.tsx:101
  ('thank_you_seo_title', 'Thank You — Your Free Practice Kit Is Ready! | Resilient Mind', 'Thank You — Your Free Practice Kit Is Ready! | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'thank-you', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/FreeGuideThankYou.tsx:29
  ('thank_you_seo_description', 'Download your free 7-day practice kit with workbooks and guided EFT video.', 'Download your free 7-day practice kit with workbooks and guided EFT video.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'thank-you', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/FreeGuideThankYou.tsx:30
  ('checkout_success_seo_title', 'Checkout Confirmed | Resilient Mind', 'Checkout Confirmed | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'checkout-success', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/CheckoutSuccess.tsx:120
  ('checkout_success_seo_description', 'Your purchase was confirmed.', 'Your purchase was confirmed.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'checkout-success', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/CheckoutSuccess.tsx:121
  ('membership_seo_title', 'Resilient Mind Membership — Feel Like Yourself Again | Online Support for Expat Women', 'Resilient Mind Membership — Feel Like Yourself Again | Online Support for Expat Women', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'membership', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/Membership.tsx:72
  ('membership_seo_description', 'A gentle online membership for expat women who feel overwhelmed, disconnected, or not quite themselves. EFT tapping, expressive arts and nervous system regulation — feel calm, grounded, and at home within.', 'A gentle online membership for expat women who feel overwhelmed, disconnected, or not quite themselves. EFT tapping, expressive arts and nervous system regulation — feel calm, grounded, and at home within.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'membership', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Membership.tsx:73
  ('membership_seo_keywords', 'expat women membership, EFT for expats, expat emotional support, feel like yourself abroad, nervous system regulation, expat loneliness, online therapy membership', 'expat women membership, EFT for expats, expat emotional support, feel like yourself abroad, nervous system regulation, expat loneliness, online therapy membership', 'Pro vyhledávače (nezobrazuje se na stránce) — Klíčová slova', 'membership', 'seo', 'text', 'Klíčová slova', 30), -- from src/pages/Membership.tsx:75
  ('notfound_seo_title', 'Page Not Found (404) | Resilient Mind', 'Page Not Found (404) | Resilient Mind', 'Stránka 404 — Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'shared', 'not_found_seo', 'text', 'Titulek stránky', 10), -- from src/pages/NotFound.tsx:14
  ('notfound_seo_description', 'The page you''re looking for doesn''t exist or has been moved.', 'The page you''re looking for doesn''t exist or has been moved.', 'Stránka 404 — Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'shared', 'not_found_seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/NotFound.tsx:15
  ('pricing_seo_title_prefix', 'Pricing — Membership Plans from €', 'Pricing — Membership Plans from €', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky — text před cenou (cena se dosazuje automaticky)', 'pricing', 'seo', 'text', 'Titulek stránky — text před cenou (cena se dosazuje automaticky)', 10), -- from src/pages/Pricing.tsx:26
  ('pricing_seo_title_suffix', ' | Resilient Mind', ' | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky — text za cenou', 'pricing', 'seo', 'text', 'Titulek stránky — text za cenou', 20), -- from src/pages/Pricing.tsx:26
  ('pricing_seo_description_prefix', 'Choose from Basic or Premium membership plans. Pay as you go from €', 'Choose from Basic or Premium membership plans. Pay as you go from €', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání — text před 1. cenou (cena se dosazuje automaticky)', 'pricing', 'seo', 'text', 'Popisek ve výsledcích vyhledávání — text před 1. cenou (cena se dosazuje automaticky)', 30), -- from src/pages/Pricing.tsx:27
  ('pricing_seo_description_middle', ' or yearly from €', ' or yearly from €', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání — text mezi 1. a 2. cenou', 'pricing', 'seo', 'text', 'Popisek ve výsledcích vyhledávání — text mezi 1. a 2. cenou', 40), -- from src/pages/Pricing.tsx:27
  ('pricing_seo_description_suffix', '. One-time payments, no auto-renewal. Includes video lessons, workbooks and more.', '. One-time payments, no auto-renewal. Includes video lessons, workbooks and more.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání — text za 2. cenou', 'pricing', 'seo', 'text', 'Popisek ve výsledcích vyhledávání — text za 2. cenou', 50), -- from src/pages/Pricing.tsx:27
  ('pricing_success_seo_title', 'Welcome to Resilient Mind Membership', 'Welcome to Resilient Mind Membership', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'pricing-success', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/PricingSuccess.tsx:126
  ('pricing_success_seo_description', 'Your membership is active.', 'Your membership is active.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'pricing-success', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/PricingSuccess.tsx:127
  ('privacy_seo_title', 'Personal Data Protection (GDPR) | Resilient Mind', 'Personal Data Protection (GDPR) | Resilient Mind', 'Zásady ochrany osobních údajů (GDPR) — Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'legal', 'privacy_seo', 'text', 'Titulek stránky', 10), -- from src/pages/Privacy.tsx:14
  ('privacy_seo_description', 'Statement on the Processing of Personal Data in accordance with GDPR. How Resilient Mind handles your personal data and your rights.', 'Statement on the Processing of Personal Data in accordance with GDPR. How Resilient Mind handles your personal data and your rights.', 'Zásady ochrany osobních údajů (GDPR) — Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'legal', 'privacy_seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Privacy.tsx:15
  ('resilient_hub_seo_title', 'Resilient Hub — A Guided 12-Month Membership for Expat Women | Resilient Mind', 'Resilient Hub — A Guided 12-Month Membership for Expat Women | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'resilient-hub', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/ResilientHub.tsx:131
  ('resilient_hub_seo_description', 'A structured 12-month online membership combining EFT, nervous system regulation and reflective tools. Monthly themes, video lessons, and guided practices to support your emotional wellbeing while living abroad.', 'A structured 12-month online membership combining EFT, nervous system regulation and reflective tools. Monthly themes, video lessons, and guided practices to support your emotional wellbeing while living abroad.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'resilient-hub', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/ResilientHub.tsx:132
  ('resilient_hub_seo_keywords', '12-month membership, expat women, EFT tapping, nervous system regulation, expressive art therapy, expatriate wellbeing, online program for expats', '12-month membership, expat women, EFT tapping, nervous system regulation, expressive art therapy, expatriate wellbeing, online program for expats', 'Pro vyhledávače (nezobrazuje se na stránce) — Klíčová slova', 'resilient-hub', 'seo', 'text', 'Klíčová slova', 30), -- from src/pages/ResilientHub.tsx:134
  ('resilient_hubs_seo_title', '12-Month Membership Program to Inner Strength | Resilient Mind', '12-Month Membership Program to Inner Strength | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'resilient-hubs', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/ResilientHubs.tsx:62
  ('resilient_hubs_seo_description', 'Join a 12-month guided membership program with video lessons, workbooks and community support designed for expatriates seeking inner strength. From €37 — pay as you go.', 'Join a 12-month guided membership program with video lessons, workbooks and community support designed for expatriates seeking inner strength. From €37 — pay as you go.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'resilient-hubs', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/ResilientHubs.tsx:63
  ('terms_seo_title', 'General Terms and Conditions | Resilient Mind', 'General Terms and Conditions | Resilient Mind', 'Obchodní podmínky — Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'legal', 'terms_seo', 'text', 'Titulek stránky', 10), -- from src/pages/Terms.tsx:14
  ('terms_seo_description', 'General Terms and Conditions for the sale of digital products by Resilient Mind. Rights, obligations, payments, refunds and data protection.', 'General Terms and Conditions for the sale of digital products by Resilient Mind. Rights, obligations, payments, refunds and data protection.', 'Obchodní podmínky — Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'legal', 'terms_seo', 'text', 'Popisek ve výsledcích vyhledávání', 20), -- from src/pages/Terms.tsx:15
  ('workshop_post_seo_title_suffix', 'Resilient Mind Workshops', 'Resilient Mind Workshops', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky — text za názvem workshopu ("Název workshopu | ...")', 'workshop-post', 'seo', 'text', 'Titulek stránky — text za názvem workshopu ("Název workshopu | ...")', 10), -- from src/pages/WorkshopPost.tsx:111
  ('workshopy_seo_title', 'Workshops — Interactive Sessions for Organizations | Resilient Mind', 'Workshops — Interactive Sessions for Organizations | Resilient Mind', 'Pro vyhledávače (nezobrazuje se na stránce) — Titulek stránky', 'workshopy', 'seo', 'text', 'Titulek stránky', 10), -- from src/pages/Workshopy.tsx:60
  ('workshopy_seo_description', 'Interactive art expressive therapy workshops for organizations and groups. Build team resilience through creative sessions.', 'Interactive art expressive therapy workshops for organizations and groups. Build team resilience through creative sessions.', 'Pro vyhledávače (nezobrazuje se na stránce) — Popisek ve výsledcích vyhledávání', 'workshopy', 'seo', 'text', 'Popisek ve výsledcích vyhledávání', 20) -- from src/pages/Workshopy.tsx:61
ON CONFLICT (key) DO NOTHING;

-- cms_sections rows for the 'seo' sections above (docs/cms-keys-seo.json).
-- ON CONFLICT (page, section_key) DO NOTHING, same reasoning as cms_content.
INSERT INTO public.cms_sections (page, section_key, title, description, anchor, route, sort_order) VALUES
  ('homepage', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/', 200),
  ('about', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/about', 200),
  ('blog', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/blog', 200),
  ('blog-post', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Zbytek titulku se skládá z názvu článku, který se edituje ve správě blogu. Nejsou vidět na stránce.', NULL, '/blog/:slug', 200),
  ('booking', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/booking', 200),
  ('booking-success', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/booking/success', 200),
  ('legal', 'cookies_seo', 'Zásady používání cookies — Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání pro stránku /cookies. Nejsou vidět na stránce.', NULL, '/cookies', 410),
  ('endometriosis', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/endometriosis-hub', 200),
  ('free-guide', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/free-guide', 200),
  ('thank-you', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/thank-you', 200),
  ('checkout-success', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/checkout/success', 200),
  ('membership', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek, popisek a klíčová slova, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/membership', 200),
  ('shared', 'not_found_seo', 'Stránka 404 — Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání pro stránku /404. Nejsou vidět na stránce.', NULL, '/404', 200),
  ('pricing', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek jsou rozdělené na části před/za cenou, protože cena se dosazuje automaticky podle aktuálního ceníku. Nejsou vidět na stránce.', NULL, '/pricing', 200),
  ('pricing-success', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/pricing/success', 200),
  ('legal', 'privacy_seo', 'Zásady ochrany osobních údajů (GDPR) — Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání pro stránku /privacy. Nejsou vidět na stránce.', NULL, '/privacy', 420),
  ('resilient-hub', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek, popisek a klíčová slova, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/resilient-hub', 200),
  ('resilient-hubs', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/resilient-hubs', 200),
  ('legal', 'terms_seo', 'Obchodní podmínky — Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání pro stránku /terms. Nejsou vidět na stránce.', NULL, '/terms', 400),
  ('workshop-post', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Zbytek titulku se skládá z názvu workshopu, který se edituje ve správě workshopů. Nejsou vidět na stránce.', NULL, '/workshopy/:slug', 200),
  ('workshopy', 'seo', 'Pro vyhledávače (nezobrazuje se na stránce)', 'Titulek a popisek, které Google zobrazí ve výsledcích vyhledávání. Nejsou vidět na stránce.', NULL, '/workshopy', 200)
ON CONFLICT (page, section_key) DO NOTHING;
