// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isPreviewFrame } from '@/lib/previewMode';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// CMS section previews (see src/components/admin/AdminCMS.tsx) load in a
// same-origin iframe, so this module is re-evaluated inside it too. GoTrue
// writing to localStorage there fires a `storage` event the parent window's
// own client picks up (cross-tab session sync), causing a spurious re-check
// and flicker of the admin's auth state. Preview instances never need a
// session, so they get a no-op storage and skip persistence entirely.
const noopStorage = {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: isPreviewFrame()
    ? { storage: noopStorage, persistSession: false, autoRefreshToken: false }
    : { storage: localStorage, persistSession: true, autoRefreshToken: true },
});